In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

In [2]:
task = 'cell'
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 16:42:20,278] Using an existing study with name 'GATv2' instead of creating a new one.

(1, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
18,0.5191 (± 0.0394),0.682 (± 0.1076),0.6607 (± 0.112),0.5191 (± 0.0394),0.0695 (± 0.1329),0.0426 (± 0.0857),0.2715 (± 0.4304),47.0,gelu,0.1,0.1,2,639,224,205,0.002499,AdamW,Cosine,0.000002

In [3]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
18,0.5191 (± 0.0394),0.682 (± 0.1076),0.6607 (± 0.112),0.5191 (± 0.0394),0.0695 (± 0.1329),0.0426 (± 0.0857),0.2715 (± 0.4304),47.0,gelu,0.1,0.1,2,639,224,205,0.002499,AdamW,Cosine,0.000002

In [4]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
18,0.5191 (± 0.0394),0.682 (± 0.1076),0.6607 (± 0.112),0.5191 (± 0.0394),0.0695 (± 0.1329),0.0426 (± 0.0857),0.2715 (± 0.4304),47.0,gelu,0.1,0.1,2,639,224,205,0.002499,AdamW,Cosine,0.000002

In [5]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
18,0.5191 (± 0.0394),0.682 (± 0.1076),0.6607 (± 0.112),0.5191 (± 0.0394),0.0695 (± 0.1329),0.0426 (± 0.0857),0.2715 (± 0.4304),47.0,gelu,0.1,0.1,2,639,224,205,0.002499,AdamW,Cosine,0.000002

In [6]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-12 16:42:29,495] Using an existing study with name 'Transformer' instead of creating a new one.

(1, 22)

In [7]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
10,0.6297 (± 0.0817),0.8401 (± 0.0737),0.8296 (± 0.0756),0.6297 (± 0.0817),0.4002 (± 0.2212),0.2809 (± 0.1743),0.7984 (± 0.3414),23.0,gelu,0.2,0.1,2,526,357,149,0.000375,AdamW,Cosine,0.006728

In [8]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
10,0.6297 (± 0.0817),0.8401 (± 0.0737),0.8296 (± 0.0756),0.6297 (± 0.0817),0.4002 (± 0.2212),0.2809 (± 0.1743),0.7984 (± 0.3414),23.0,gelu,0.2,0.1,2,526,357,149,0.000375,AdamW,Cosine,0.006728

In [9]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
10,0.6297 (± 0.0817),0.8401 (± 0.0737),0.8296 (± 0.0756),0.6297 (± 0.0817),0.4002 (± 0.2212),0.2809 (± 0.1743),0.7984 (± 0.3414),23.0,gelu,0.2,0.1,2,526,357,149,0.000375,AdamW,Cosine,0.006728

In [10]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df.head() if n > 0 else None

[I 2025-04-12 16:42:38,492] Using an existing study with name 'GAT' instead of creating a new one.

(22, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.5004 (± 0.0235),0.5332 (± 0.064),0.4993 (± 0.076),0.5004 (± 0.0235),0.2981 (± 0.3147),0.4166 (± 0.4646),0.2571 (± 0.2591),NaN,relu,0.10,0.25,5,588,138,84,0.000097,AdamW,None,0.000381
1,0.4983 (± 0.0198),0.5282 (± 0.0584),0.4893 (± 0.0717),0.4983 (± 0.0198),0.2743 (± 0.3123),0.3868 (± 0.4627),0.2415 (± 0.2603),NaN,gelu,0.30,0.10,6,1013,97,38,0.000822,AdamW,None,0.000028
2,0.5002 (± 0.0201),0.5443 (± 0.0658),0.5106 (± 0.0763),0.5002 (± 0.0201),0.2649 (± 0.3147),0.3762 (± 0.4641),0.2242 (± 0.2569),2.0,relu,0.15,0.10,2,673,380,208,0.008548,Adam,Cosine,0.007701
4,0.5003 (± 0.0231),0.5312 (± 0.061),0.4942 (± 0.0709),0.5003 (± 0.0231),0.2841 (± 0.3126),0.3956 (± 0.4598),0.2573 (± 0.2699),2.0,gelu,0.25,0.40,2,967,431,129,0.000029,Adam,Cosine,0.000003
5,0.4989 (± 0.0136),0.5302 (± 0.0643),0.4945 (± 0.0769),0.4989 (± 0.0136),0.192 (± 0.2938),0.2758 (± 0.4331),0.1584 (± 0.2368),1.0,relu,0.40,0.30,3,801,419,224,0.001521,Adam,Cosine,0.000008

In [11]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
33,0.5017 (± 0.0205),0.5357 (± 0.063),0.4994 (± 0.0739),0.5017 (± 0.0205),0.3206 (± 0.3149),0.4493 (± 0.4698),0.2929 (± 0.2721),NaN,relu,0.10,0.35,2,864,223,196,0.000040,Adam,None,0.001192
26,0.5015 (± 0.0181),0.5351 (± 0.0623),0.4986 (± 0.0734),0.5015 (± 0.0181),0.2402 (± 0.3069),0.3362 (± 0.4494),0.2097 (± 0.2573),NaN,gelu,0.45,0.40,3,904,175,133,0.000301,AdamW,None,0.000006
10,0.5011 (± 0.0219),0.5291 (± 0.061),0.4915 (± 0.0723),0.5011 (± 0.0219),0.2765 (± 0.3113),0.3839 (± 0.4574),0.2529 (± 0.273),NaN,gelu,0.35,0.50,2,635,185,149,0.000094,AdamW,None,0.000007

In [12]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
2,0.5002 (± 0.0201),0.5443 (± 0.0658),0.5106 (± 0.0763),0.5002 (± 0.0201),0.2649 (± 0.3147),0.3762 (± 0.4641),0.2242 (± 0.2569),2.0,relu,0.15,0.10,2,673,380,208,0.008548,Adam,Cosine,0.007701
16,0.5007 (± 0.0122),0.5425 (± 0.0681),0.5127 (± 0.08),0.5007 (± 0.0122),0.2056 (± 0.2994),0.2932 (± 0.4402),0.1696 (± 0.2401),NaN,relu,0.45,0.50,4,707,178,102,0.007298,Adam,None,0.000460
33,0.5017 (± 0.0205),0.5357 (± 0.063),0.4994 (± 0.0739),0.5017 (± 0.0205),0.3206 (± 0.3149),0.4493 (± 0.4698),0.2929 (± 0.2721),NaN,relu,0.10,0.35,2,864,223,196,0.000040,Adam,None,0.001192

In [13]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
16,0.5007 (± 0.0122),0.5425 (± 0.0681),0.5127 (± 0.08),0.5007 (± 0.0122),0.2056 (± 0.2994),0.2932 (± 0.4402),0.1696 (± 0.2401),NaN,relu,0.45,0.50,4,707,178,102,0.007298,Adam,None,0.000460
2,0.5002 (± 0.0201),0.5443 (± 0.0658),0.5106 (± 0.0763),0.5002 (± 0.0201),0.2649 (± 0.3147),0.3762 (± 0.4641),0.2242 (± 0.2569),2.0,relu,0.15,0.10,2,673,380,208,0.008548,Adam,Cosine,0.007701
33,0.5017 (± 0.0205),0.5357 (± 0.063),0.4994 (± 0.0739),0.5017 (± 0.0205),0.3206 (± 0.3149),0.4493 (± 0.4698),0.2929 (± 0.2721),NaN,relu,0.10,0.35,2,864,223,196,0.000040,Adam,None,0.001192

In [14]:
method = "MPNN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 19:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 16:42:41,790] Using an existing study with name 'MPNN' instead of creating a new one.

(3, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.5 (± 0.0),0.5579 (± 0.0607),0.5386 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),relu,0.50,0.45,4,833,260,217,0.000613,AdamW,None,0.000006
1,0.5 (± 0.0),0.5706 (± 0.0625),0.5335 (± 0.065),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.15,0.30,6,787,139,85,0.000019,AdamW,None,0.000158
2,0.5 (± 0.0),0.5577 (± 0.0634),0.5373 (± 0.0665),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.40,0.40,3,314,70,49,0.001388,AdamW,None,0.002241

In [15]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.5 (± 0.0),0.5579 (± 0.0607),0.5386 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),relu,0.50,0.45,4,833,260,217,0.000613,AdamW,None,0.000006
1,0.5 (± 0.0),0.5706 (± 0.0625),0.5335 (± 0.065),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.15,0.30,6,787,139,85,0.000019,AdamW,None,0.000158
2,0.5 (± 0.0),0.5577 (± 0.0634),0.5373 (± 0.0665),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.40,0.40,3,314,70,49,0.001388,AdamW,None,0.002241

In [16]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1,0.5 (± 0.0),0.5706 (± 0.0625),0.5335 (± 0.065),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.15,0.30,6,787,139,85,0.000019,AdamW,None,0.000158
0,0.5 (± 0.0),0.5579 (± 0.0607),0.5386 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),relu,0.50,0.45,4,833,260,217,0.000613,AdamW,None,0.000006
2,0.5 (± 0.0),0.5577 (± 0.0634),0.5373 (± 0.0665),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.40,0.40,3,314,70,49,0.001388,AdamW,None,0.002241

In [17]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.5 (± 0.0),0.5579 (± 0.0607),0.5386 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),relu,0.50,0.45,4,833,260,217,0.000613,AdamW,None,0.000006
2,0.5 (± 0.0),0.5577 (± 0.0634),0.5373 (± 0.0665),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.40,0.40,3,314,70,49,0.001388,AdamW,None,0.002241
1,0.5 (± 0.0),0.5706 (± 0.0625),0.5335 (± 0.065),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),gelu,0.15,0.30,6,787,139,85,0.000019,AdamW,None,0.000158

In [18]:
for i in parsed_df['ACC']:
    if '0.5' in i:
        print(i)

0.5 (± 0.0)
0.5 (± 0.0)
0.5 (± 0.0)

In [19]:
method = "GCN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 16:42:46,408] Using an existing study with name 'GCN' instead of creating a new one.

(7, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4999 (± 0.0009),0.5431 (± 0.0558),0.5084 (± 0.069),0.4999 (± 0.0009),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),21.0,relu,0.45,0.30,6,258,177,57,0.000095,AdamW,Cosine,0.001172
1,0.5 (± 0.0),0.5386 (± 0.0578),0.5263 (± 0.0684),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.40,0.35,6,579,213,160,0.004967,AdamW,None,0.000001
2,0.5 (± 0.0),0.5399 (± 0.0576),0.519 (± 0.0671),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.10,0.35,2,476,192,80,0.005710,Adam,None,0.001869
3,0.5 (± 0.0),0.5635 (± 0.0591),0.5439 (± 0.0666),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.15,0.25,2,536,159,95,0.000192,AdamW,None,0.000001
4,0.5 (± 0.0),0.5467 (± 0.0587),0.5323 (± 0.0678),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),39.0,gelu,0.30,0.25,3,785,330,215,0.001227,AdamW,Cosine,0.008804
5,0.5 (± 0.0007),0.5502 (± 0.0562),0.5157 (± 0.0679),0.5 (± 0.0007),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),44.0,relu,0.10,0.15,5,868,345,60,0.000071,Adam,Cosine,0.000001
6,0.5 (± 0.0),0.5532 (± 0.0584),0.522 (± 0.0693),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.15,0.20,8,299,174,49,0.000126,Adam,None,0.000001

In [22]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
5,0.5 (± 0.0007),0.5502 (± 0.0562),0.5157 (± 0.0679),0.5 (± 0.0007),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),44.0,relu,0.1,0.15,5,868,345,60,0.000071,Adam,Cosine,0.000001
1,0.5 (± 0.0),0.5386 (± 0.0578),0.5263 (± 0.0684),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.4,0.35,6,579,213,160,0.004967,AdamW,None,0.000001
2,0.5 (± 0.0),0.5399 (± 0.0576),0.519 (± 0.0671),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.1,0.35,2,476,192,80,0.005710,Adam,None,0.001869

In [23]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3,0.5 (± 0.0),0.5635 (± 0.0591),0.5439 (± 0.0666),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.15,0.25,2,536,159,95,0.000192,AdamW,None,0.000001
6,0.5 (± 0.0),0.5532 (± 0.0584),0.522 (± 0.0693),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.15,0.20,8,299,174,49,0.000126,Adam,None,0.000001
5,0.5 (± 0.0007),0.5502 (± 0.0562),0.5157 (± 0.0679),0.5 (± 0.0007),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),44.0,relu,0.10,0.15,5,868,345,60,0.000071,Adam,Cosine,0.000001

In [24]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3,0.5 (± 0.0),0.5635 (± 0.0591),0.5439 (± 0.0666),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.15,0.25,2,536,159,95,0.000192,AdamW,None,0.000001
4,0.5 (± 0.0),0.5467 (± 0.0587),0.5323 (± 0.0678),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),39.0,gelu,0.30,0.25,3,785,330,215,0.001227,AdamW,Cosine,0.008804
1,0.5 (± 0.0),0.5386 (± 0.0578),0.5263 (± 0.0684),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.40,0.35,6,579,213,160,0.004967,AdamW,None,0.000001