In [6]:
import pandas as pd
import optuna

In [7]:
task = 'drug'
method = 'GATv2'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 11:57:33,611] Using an existing study with name 'GATv2' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 22:23:49.485942,2025-04-09 00:55:52.338273,0 days 02:32:02.852331,29.0,relu,...,2,512,248,210,0.000242,Adam,Cosine,0.000008,0,FAIL
1,1,None,None,None,None,2025-04-09 11:12:06.227200,2025-04-09 11:12:14.289762,0 days 00:00:08.062562,NaN,gelu,...,5,960,438,137,0.000096,AdamW,None,0.000014,0,PRUNED
2,2,None,None,None,None,2025-04-09 11:12:14.314952,NaT,NaT,39.0,gelu,...,4,431,78,72,0.000430,Adam,Cosine,0.003149,0,RUNNING

In [8]:
method = 'GAT'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 11:57:33,749] Using an existing study with name 'GAT' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 22:26:21.487451,2025-04-08 22:26:26.132588,0 days 00:00:04.645137,37.0,relu,...,7,706,479,142,0.002694,AdamW,Cosine,0.000001,0,PRUNED
1,1,None,None,None,None,2025-04-08 22:26:26.158679,2025-04-08 22:26:30.587074,0 days 00:00:04.428395,NaN,relu,...,3,456,389,225,0.000282,Adam,None,0.005547,0,PRUNED
2,2,None,None,None,None,2025-04-08 22:26:30.611740,2025-04-08 22:26:34.619521,0 days 00:00:04.007781,NaN,relu,...,6,544,396,40,0.000476,AdamW,None,0.004675,0,PRUNED
3,3,None,None,None,None,2025-04-08 22:26:34.644305,2025-04-09 00:22:42.065358,0 days 01:56:07.421053,NaN,gelu,...,3,952,174,139,0.000124,AdamW,None,0.000014,0,FAIL
4,4,None,None,None,None,2025-04-09 11:02:36.363092,NaT,NaT,27.0,relu,...,3,544,352,33,0.000217,Adam,Cosine,0.004254,0,RUNNING

In [12]:
method = 'Transformer'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 11:57:37,237] Using an existing study with name 'Transformer' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_activation,params_dropout1,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-09 11:53:15.760731,None,None,gelu,0.3,...,2,372,171,70,0.000695,AdamW,None,0.000249,0,RUNNING

In [13]:
method = 'GCN'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 11:57:38,535] Using an existing study with name 'GCN' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 22:15:29.902305,2025-04-08 22:15:39.632388,0 days 00:00:09.730083,NaN,relu,...,3,423,93,90,0.000188,Adam,None,0.000349,0,FAIL
1,1,None,None,None,None,2025-04-08 23:00:10.076345,2025-04-08 23:32:22.431107,0 days 00:32:12.354762,NaN,relu,...,3,381,368,179,0.002157,Adam,None,0.000094,0,FAIL
2,2,None,None,None,None,2025-04-09 11:15:17.589021,2025-04-09 11:51:50.190958,0 days 00:36:32.601937,31.0,gelu,...,3,711,473,181,0.000152,Adam,Cosine,0.004557,0,FAIL

In [14]:
method = 'MPNN'
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
study.trials_dataframe()

[I 2025-04-09 11:57:38,782] Using an existing study with name 'MPNN' instead of creating a new one.

,number,values_0,values_1,values_2,values_3,datetime_start,datetime_complete,duration,params_T_max,params_activation,...,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay,system_attrs_nsga2:generation,state
0,0,None,None,None,None,2025-04-08 22:19:04.439422,2025-04-08 22:19:29.598201,0 days 00:00:25.158779,42.0,gelu,...,7,488,173,94,0.000023,AdamW,Cosine,0.000254,0,FAIL
1,1,None,None,None,None,2025-04-08 22:55:38.831113,2025-04-08 23:30:06.123145,0 days 00:34:27.292032,NaN,gelu,...,5,420,73,62,0.000117,AdamW,None,0.000004,0,FAIL
2,2,None,None,None,None,2025-04-09 11:12:06.235109,2025-04-09 11:50:29.447375,0 days 00:38:23.212266,NaN,relu,...,8,257,241,59,0.000014,AdamW,None,0.000003,0,FAIL