In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

In [2]:
task = "cell"
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-17 10:43:45,952] Using an existing study with name 'GATv2' instead of creating a new one.

(12, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
14,0.5709 (± 0.0342),0.6376 (± 0.0399),0.6283 (± 0.0386),0.571 (± 0.0342),0.3897 (± 0.1477),0.3021 (± 0.1499),0.666 (± 0.1224),NaN,relu,0.40,0.45,2,499,235,143,0.000176,AdamW,None,0.000057
15,0.5603 (± 0.0386),0.6329 (± 0.0426),0.6283 (± 0.0433),0.5604 (± 0.0385),0.3167 (± 0.1629),0.2288 (± 0.1437),0.6717 (± 0.1722),NaN,relu,0.10,0.25,6,370,163,72,0.000613,AdamW,None,0.000935
16,0.5019 (± 0.0072),0.5621 (± 0.0308),0.5524 (± 0.0304),0.5021 (± 0.0072),0.0224 (± 0.0397),0.0121 (± 0.0226),0.3034 (± 0.3557),27.0,gelu,0.50,0.45,5,408,128,83,0.000041,Adam,Cosine,0.000092
19,0.5015 (± 0.0059),0.5687 (± 0.0316),0.5621 (± 0.0314),0.5016 (± 0.0055),0.0158 (± 0.0404),0.0092 (± 0.0376),0.3107 (± 0.4106),37.0,relu,0.30,0.35,2,982,214,169,0.000020,AdamW,Cosine,0.000002
25,0.5358 (± 0.0376),0.5971 (± 0.0506),0.5886 (± 0.0502),0.5359 (± 0.0376),0.1964 (± 0.1708),0.1317 (± 0.1223),0.4718 (± 0.3334),30.0,relu,0.10,0.15,2,511,158,60,0.004840,Adam,Cosine,0.003926
27,0.5519 (± 0.0454),0.6201 (± 0.0586),0.61 (± 0.0549),0.552 (± 0.0454),0.2521 (± 0.179),0.173 (± 0.136),0.5981 (± 0.2851),NaN,gelu,0.30,0.25,3,445,284,98,0.001302,AdamW,None,0.000209
28,0.5138 (± 0.0256),0.5779 (± 0.0473),0.572 (± 0.0466),0.514 (± 0.0254),0.0817 (± 0.1303),0.0523 (± 0.0882),0.2616 (± 0.35),31.0,relu,0.20,0.50,2,475,222,37,0.001084,AdamW,Cosine,0.005113
35,0.5751 (± 0.0432),0.6508 (± 0.0536),0.6385 (± 0.0509),0.5752 (± 0.0433),0.3486 (± 0.1462),0.2458 (± 0.1246),0.7114 (± 0.1371),NaN,relu,0.20,0.25,4,360,114,46,0.003472,AdamW,None,0.000937
46,0.5013 (± 0.0065),0.5646 (± 0.0318),0.5569 (± 0.0325),0.5015 (± 0.0061),0.0161 (± 0.0363),0.0087 (± 0.0213),0.2321 (± 0.3493),NaN,relu,0.20,0.30,2,300,84,54,0.000031,AdamW,None,0.000643
47,0.5462 (± 0.036),0.6116 (± 0.0473),0.6013 (± 0.0458),0.5463 (± 0.036),0.2483 (± 0.1585),0.1673 (± 0.1177),0.5782 (± 0.28),39.0,relu,0.30,0.10,3,915,83,71,0.002033,Adam,Cosine,0.002576
51,0.5335 (± 0.0221),0.5991 (± 0.0357),0.5982 (± 0.0351),0.5337 (± 0.0223),0.2158 (± 0.1038),0.1359 (± 0.0773),0.665 (± 0.1295),NaN,relu,0.25,0.20,4,440,135,86,0.000053,Adam,None,0.000008
62,0.5432 (± 0.0344),0.6187 (± 0.0421),0.6138 (± 0.0415),0.5433 (± 0.0343),0.2531 (± 0.1734),0.1813 (± 0.1494),0.6206 (± 0.251),NaN,gelu,0.30,0.50,2,628,347,36,0.000302,Adam,None,0.004301

In [3]:
parsed_df.sort_values("ACC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
35,0.5751 (± 0.0432),0.6508 (± 0.0536),0.6385 (± 0.0509),0.5752 (± 0.0433),0.3486 (± 0.1462),0.2458 (± 0.1246),0.7114 (± 0.1371),NaN,relu,0.2,0.25,4,360,114,46,0.003472,AdamW,None,0.000937
14,0.5709 (± 0.0342),0.6376 (± 0.0399),0.6283 (± 0.0386),0.571 (± 0.0342),0.3897 (± 0.1477),0.3021 (± 0.1499),0.666 (± 0.1224),NaN,relu,0.4,0.45,2,499,235,143,0.000176,AdamW,None,0.000057
15,0.5603 (± 0.0386),0.6329 (± 0.0426),0.6283 (± 0.0433),0.5604 (± 0.0385),0.3167 (± 0.1629),0.2288 (± 0.1437),0.6717 (± 0.1722),NaN,relu,0.1,0.25,6,370,163,72,0.000613,AdamW,None,0.000935

In [4]:
parsed_df.sort_values("AUPR", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
35,0.5751 (± 0.0432),0.6508 (± 0.0536),0.6385 (± 0.0509),0.5752 (± 0.0433),0.3486 (± 0.1462),0.2458 (± 0.1246),0.7114 (± 0.1371),NaN,relu,0.2,0.25,4,360,114,46,0.003472,AdamW,None,0.000937
14,0.5709 (± 0.0342),0.6376 (± 0.0399),0.6283 (± 0.0386),0.571 (± 0.0342),0.3897 (± 0.1477),0.3021 (± 0.1499),0.666 (± 0.1224),NaN,relu,0.4,0.45,2,499,235,143,0.000176,AdamW,None,0.000057
15,0.5603 (± 0.0386),0.6329 (± 0.0426),0.6283 (± 0.0433),0.5604 (± 0.0385),0.3167 (± 0.1629),0.2288 (± 0.1437),0.6717 (± 0.1722),NaN,relu,0.1,0.25,6,370,163,72,0.000613,AdamW,None,0.000935

In [5]:
parsed_df.sort_values("AUROC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
35,0.5751 (± 0.0432),0.6508 (± 0.0536),0.6385 (± 0.0509),0.5752 (± 0.0433),0.3486 (± 0.1462),0.2458 (± 0.1246),0.7114 (± 0.1371),NaN,relu,0.2,0.25,4,360,114,46,0.003472,AdamW,None,0.000937
15,0.5603 (± 0.0386),0.6329 (± 0.0426),0.6283 (± 0.0433),0.5604 (± 0.0385),0.3167 (± 0.1629),0.2288 (± 0.1437),0.6717 (± 0.1722),NaN,relu,0.1,0.25,6,370,163,72,0.000613,AdamW,None,0.000935
14,0.5709 (± 0.0342),0.6376 (± 0.0399),0.6283 (± 0.0386),0.571 (± 0.0342),0.3897 (± 0.1477),0.3021 (± 0.1499),0.666 (± 0.1224),NaN,relu,0.4,0.45,2,499,235,143,0.000176,AdamW,None,0.000057

In [6]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

[I 2025-04-17 10:43:56,269] Using an existing study with name 'Transformer' instead of creating a new one.

(13, 22)

In [7]:
parsed_df.sort_values("ACC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
28,0.6063 (± 0.0392),0.6895 (± 0.0474),0.6949 (± 0.0446),0.6064 (± 0.0392),0.4516 (± 0.1121),0.3406 (± 0.1197),0.7377 (± 0.0697),NaN,relu,0.35,0.45,7,994,105,95,0.000313,AdamW,None,0.000141
13,0.5717 (± 0.0295),0.6462 (± 0.0398),0.6471 (± 0.0382),0.5718 (± 0.0294),0.3588 (± 0.1044),0.2512 (± 0.0985),0.7131 (± 0.0735),NaN,gelu,0.25,0.10,2,550,79,55,0.000133,AdamW,None,0.000069
42,0.5616 (± 0.0391),0.6405 (± 0.0463),0.6405 (± 0.0465),0.5617 (± 0.0391),0.3113 (± 0.1444),0.2161 (± 0.1234),0.7076 (± 0.1002),NaN,relu,0.10,0.25,2,845,127,89,0.001268,Adam,None,0.000005

In [8]:
parsed_df.sort_values("AUPR", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
28,0.6063 (± 0.0392),0.6895 (± 0.0474),0.6949 (± 0.0446),0.6064 (± 0.0392),0.4516 (± 0.1121),0.3406 (± 0.1197),0.7377 (± 0.0697),NaN,relu,0.35,0.45,7,994,105,95,0.000313,AdamW,None,0.000141
43,0.5562 (± 0.0295),0.6488 (± 0.04),0.6473 (± 0.0387),0.5564 (± 0.0294),0.2773 (± 0.1074),0.1787 (± 0.0849),0.7371 (± 0.0926),NaN,gelu,0.25,0.25,6,893,89,62,0.000019,Adam,None,0.000009
13,0.5717 (± 0.0295),0.6462 (± 0.0398),0.6471 (± 0.0382),0.5718 (± 0.0294),0.3588 (± 0.1044),0.2512 (± 0.0985),0.7131 (± 0.0735),NaN,gelu,0.25,0.10,2,550,79,55,0.000133,AdamW,None,0.000069

In [9]:
parsed_df.sort_values("AUROC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
28,0.6063 (± 0.0392),0.6895 (± 0.0474),0.6949 (± 0.0446),0.6064 (± 0.0392),0.4516 (± 0.1121),0.3406 (± 0.1197),0.7377 (± 0.0697),NaN,relu,0.35,0.45,7,994,105,95,0.000313,AdamW,None,0.000141
43,0.5562 (± 0.0295),0.6488 (± 0.04),0.6473 (± 0.0387),0.5564 (± 0.0294),0.2773 (± 0.1074),0.1787 (± 0.0849),0.7371 (± 0.0926),NaN,gelu,0.25,0.25,6,893,89,62,0.000019,Adam,None,0.000009
13,0.5717 (± 0.0295),0.6462 (± 0.0398),0.6471 (± 0.0382),0.5718 (± 0.0294),0.3588 (± 0.1044),0.2512 (± 0.0985),0.7131 (± 0.0735),NaN,gelu,0.25,0.10,2,550,79,55,0.000133,AdamW,None,0.000069

In [10]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df.head() if n > 0 else None

[I 2025-04-17 10:44:16,396] Using an existing study with name 'GAT' instead of creating a new one.

(4, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
2,0.5093 (± 0.0184),0.5524 (± 0.0415),0.5408 (± 0.0409),0.5094 (± 0.0183),0.076 (± 0.125),0.0523 (± 0.109),0.3783 (± 0.3731),27.0,relu,0.35,0.20,2,403,215,187,0.009411,AdamW,Cosine,0.000008
4,0.5109 (± 0.0184),0.5837 (± 0.0366),0.5841 (± 0.0403),0.511 (± 0.0183),0.0798 (± 0.1003),0.0479 (± 0.0685),0.5479 (± 0.3271),NaN,gelu,0.15,0.25,6,285,143,33,0.000076,Adam,None,0.000017
5,0.5067 (± 0.0174),0.5809 (± 0.036),0.5764 (± 0.0361),0.5069 (± 0.0173),0.0443 (± 0.0946),0.0281 (± 0.0705),0.4876 (± 0.4304),NaN,gelu,0.45,0.40,4,390,313,102,0.000178,Adam,None,0.000305
6,0.5097 (± 0.0211),0.5801 (± 0.0378),0.575 (± 0.038),0.5098 (± 0.0213),0.067 (± 0.1107),0.0424 (± 0.0823),0.458 (± 0.3796),46.0,relu,0.35,0.15,3,604,404,141,0.000208,Adam,Cosine,0.000410

In [11]:
parsed_df.sort_values("ACC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
4,0.5109 (± 0.0184),0.5837 (± 0.0366),0.5841 (± 0.0403),0.511 (± 0.0183),0.0798 (± 0.1003),0.0479 (± 0.0685),0.5479 (± 0.3271),NaN,gelu,0.15,0.25,6,285,143,33,0.000076,Adam,None,0.000017
6,0.5097 (± 0.0211),0.5801 (± 0.0378),0.575 (± 0.038),0.5098 (± 0.0213),0.067 (± 0.1107),0.0424 (± 0.0823),0.458 (± 0.3796),46.0,relu,0.35,0.15,3,604,404,141,0.000208,Adam,Cosine,0.000410
2,0.5093 (± 0.0184),0.5524 (± 0.0415),0.5408 (± 0.0409),0.5094 (± 0.0183),0.076 (± 0.125),0.0523 (± 0.109),0.3783 (± 0.3731),27.0,relu,0.35,0.20,2,403,215,187,0.009411,AdamW,Cosine,0.000008

In [12]:
parsed_df.sort_values("AUPR", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
4,0.5109 (± 0.0184),0.5837 (± 0.0366),0.5841 (± 0.0403),0.511 (± 0.0183),0.0798 (± 0.1003),0.0479 (± 0.0685),0.5479 (± 0.3271),NaN,gelu,0.15,0.25,6,285,143,33,0.000076,Adam,None,0.000017
5,0.5067 (± 0.0174),0.5809 (± 0.036),0.5764 (± 0.0361),0.5069 (± 0.0173),0.0443 (± 0.0946),0.0281 (± 0.0705),0.4876 (± 0.4304),NaN,gelu,0.45,0.40,4,390,313,102,0.000178,Adam,None,0.000305
6,0.5097 (± 0.0211),0.5801 (± 0.0378),0.575 (± 0.038),0.5098 (± 0.0213),0.067 (± 0.1107),0.0424 (± 0.0823),0.458 (± 0.3796),46.0,relu,0.35,0.15,3,604,404,141,0.000208,Adam,Cosine,0.000410

In [36]:
parsed_df.sort_values("AUROC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
4,0.5109 (± 0.0184),0.5837 (± 0.0366),0.5841 (± 0.0403),0.511 (± 0.0183),0.0798 (± 0.1003),0.0479 (± 0.0685),0.5479 (± 0.3271),NaN,gelu,0.15,0.25,6,285,143,33,0.000076,Adam,None,0.000017
5,0.5067 (± 0.0174),0.5809 (± 0.036),0.5764 (± 0.0361),0.5069 (± 0.0173),0.0443 (± 0.0946),0.0281 (± 0.0705),0.4876 (± 0.4304),NaN,gelu,0.45,0.40,4,390,313,102,0.000178,Adam,None,0.000305
2,0.5093 (± 0.0184),0.5524 (± 0.0415),0.5408 (± 0.0409),0.5094 (± 0.0183),0.076 (± 0.125),0.0523 (± 0.109),0.3783 (± 0.3731),27.0,relu,0.35,0.20,2,403,215,187,0.009411,AdamW,Cosine,0.000008

In [13]:
method = "MPNN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 19:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-17 10:44:28,725] Using an existing study with name 'MPNN' instead of creating a new one.

(2, 23)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4998 (± 0.0022),0.5495 (± 0.0296),0.5387 (± 0.0285),0.5 (± 0.0006),0.0002 (± 0.0031),0.0001 (± 0.0016),0.0022 (± 0.0367),30.0,gelu,0.15,0.35,6,722,104,48,0.000013,Adam,Cosine,0.000058
1,0.4998 (± 0.0021),0.5611 (± 0.0298),0.5493 (± 0.0295),0.5 (± 0.0002),0.0001 (± 0.0016),0.0 (± 0.0008),0.0026 (± 0.0454),39.0,gelu,0.40,0.15,6,472,352,163,0.000104,AdamW,Cosine,0.000122

In [14]:
parsed_df.sort_values("ACC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4998 (± 0.0022),0.5495 (± 0.0296),0.5387 (± 0.0285),0.5 (± 0.0006),0.0002 (± 0.0031),0.0001 (± 0.0016),0.0022 (± 0.0367),30.0,gelu,0.15,0.35,6,722,104,48,0.000013,Adam,Cosine,0.000058
1,0.4998 (± 0.0021),0.5611 (± 0.0298),0.5493 (± 0.0295),0.5 (± 0.0002),0.0001 (± 0.0016),0.0 (± 0.0008),0.0026 (± 0.0454),39.0,gelu,0.40,0.15,6,472,352,163,0.000104,AdamW,Cosine,0.000122

In [15]:
parsed_df.sort_values("AUPR", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1,0.4998 (± 0.0021),0.5611 (± 0.0298),0.5493 (± 0.0295),0.5 (± 0.0002),0.0001 (± 0.0016),0.0 (± 0.0008),0.0026 (± 0.0454),39.0,gelu,0.40,0.15,6,472,352,163,0.000104,AdamW,Cosine,0.000122
0,0.4998 (± 0.0022),0.5495 (± 0.0296),0.5387 (± 0.0285),0.5 (± 0.0006),0.0002 (± 0.0031),0.0001 (± 0.0016),0.0022 (± 0.0367),30.0,gelu,0.15,0.35,6,722,104,48,0.000013,Adam,Cosine,0.000058

In [16]:
parsed_df.sort_values("AUROC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1,0.4998 (± 0.0021),0.5611 (± 0.0298),0.5493 (± 0.0295),0.5 (± 0.0002),0.0001 (± 0.0016),0.0 (± 0.0008),0.0026 (± 0.0454),39.0,gelu,0.40,0.15,6,472,352,163,0.000104,AdamW,Cosine,0.000122
0,0.4998 (± 0.0022),0.5495 (± 0.0296),0.5387 (± 0.0285),0.5 (± 0.0006),0.0002 (± 0.0031),0.0001 (± 0.0016),0.0022 (± 0.0367),30.0,gelu,0.15,0.35,6,722,104,48,0.000013,Adam,Cosine,0.000058

In [17]:
for i in parsed_df["ACC"]:
    if "0.5" in i:
        print(i)

In [18]:
method = "GCN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-17 10:44:30,560] Using an existing study with name 'GCN' instead of creating a new one.

(6, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4998 (± 0.0021),0.5546 (± 0.0301),0.545 (± 0.0298),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),33.0,gelu,0.45,0.30,8,580,70,50,0.000907,AdamW,Cosine,0.000045
1,0.4998 (± 0.0021),0.5542 (± 0.0299),0.5449 (± 0.0297),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),35.0,relu,0.15,0.30,8,319,213,107,0.001292,Adam,Cosine,0.000001
2,0.4998 (± 0.0021),0.5531 (± 0.0299),0.5446 (± 0.0298),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.30,0.30,8,976,390,208,0.001390,AdamW,None,0.000558
3,0.4999 (± 0.0023),0.5556 (± 0.03),0.5477 (± 0.0296),0.5 (± 0.0008),0.0002 (± 0.0043),0.0001 (± 0.0023),0.0021 (± 0.0436),NaN,gelu,0.10,0.50,6,684,167,83,0.000202,Adam,None,0.000498
4,0.4998 (± 0.0021),0.5513 (± 0.0298),0.543 (± 0.0295),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.50,0.25,2,791,64,48,0.006178,AdamW,None,0.000948
5,0.4998 (± 0.0021),0.5514 (± 0.0295),0.5422 (± 0.0294),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),43.0,relu,0.40,0.20,3,643,245,98,0.002911,Adam,Cosine,0.000090

In [19]:
for i in parsed_df["ACC"]:
    if "0.5" in i:
        print(i)

In [20]:
parsed_df.sort_values("ACC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3,0.4999 (± 0.0023),0.5556 (± 0.03),0.5477 (± 0.0296),0.5 (± 0.0008),0.0002 (± 0.0043),0.0001 (± 0.0023),0.0021 (± 0.0436),NaN,gelu,0.10,0.5,6,684,167,83,0.000202,Adam,None,0.000498
0,0.4998 (± 0.0021),0.5546 (± 0.0301),0.545 (± 0.0298),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),33.0,gelu,0.45,0.3,8,580,70,50,0.000907,AdamW,Cosine,0.000045
1,0.4998 (± 0.0021),0.5542 (± 0.0299),0.5449 (± 0.0297),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),35.0,relu,0.15,0.3,8,319,213,107,0.001292,Adam,Cosine,0.000001

In [21]:
parsed_df.sort_values("AUPR", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3,0.4999 (± 0.0023),0.5556 (± 0.03),0.5477 (± 0.0296),0.5 (± 0.0008),0.0002 (± 0.0043),0.0001 (± 0.0023),0.0021 (± 0.0436),NaN,gelu,0.10,0.5,6,684,167,83,0.000202,Adam,None,0.000498
0,0.4998 (± 0.0021),0.5546 (± 0.0301),0.545 (± 0.0298),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),33.0,gelu,0.45,0.3,8,580,70,50,0.000907,AdamW,Cosine,0.000045
1,0.4998 (± 0.0021),0.5542 (± 0.0299),0.5449 (± 0.0297),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),35.0,relu,0.15,0.3,8,319,213,107,0.001292,Adam,Cosine,0.000001

In [22]:
parsed_df.sort_values("AUROC", ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
3,0.4999 (± 0.0023),0.5556 (± 0.03),0.5477 (± 0.0296),0.5 (± 0.0008),0.0002 (± 0.0043),0.0001 (± 0.0023),0.0021 (± 0.0436),NaN,gelu,0.10,0.5,6,684,167,83,0.000202,Adam,None,0.000498
0,0.4998 (± 0.0021),0.5546 (± 0.0301),0.545 (± 0.0298),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),33.0,gelu,0.45,0.3,8,580,70,50,0.000907,AdamW,Cosine,0.000045
1,0.4998 (± 0.0021),0.5542 (± 0.0299),0.5449 (± 0.0297),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),35.0,relu,0.15,0.3,8,319,213,107,0.001292,Adam,Cosine,0.000001