In [36]:
import optuna
import pandas as pd
from metrics import get_parsed_df

In [45]:
name = 'NCI'
method = "GATv2"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)

tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
print(df.shape)
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 15:35:25,141] Using an existing study with name 'GATv2' instead of creating a new one.

(26, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
10,0.667 (± 0.0071),0.7254 (± 0.0083),0.7331 (± 0.007),0.667 (± 0.0071),0.6347 (± 0.0187),0.5798 (± 0.0362),0.7028 (± 0.0103),NaN,gelu,0.25,0.35,5400,2,471,132,103,0.000069,Adam,None,0.000935
262,0.6594 (± 0.0136),0.7248 (± 0.0037),0.7297 (± 0.0028),0.6594 (± 0.0136),0.6056 (± 0.044),0.5285 (± 0.0741),0.7184 (± 0.0189),NaN,relu,0.10,0.30,3800,2,393,146,32,0.000343,AdamW,None,0.000005
123,0.6648 (± 0.0072),0.7237 (± 0.0071),0.7315 (± 0.0062),0.6648 (± 0.0072),0.6269 (± 0.0184),0.5644 (± 0.0347),0.7068 (± 0.0129),2099.0,gelu,0.20,0.25,5500,2,639,122,64,0.000012,Adam,Cosine,0.000247
39,0.6609 (± 0.009),0.7225 (± 0.0095),0.7292 (± 0.0079),0.6609 (± 0.009),0.6228 (± 0.0187),0.5611 (± 0.0357),0.7018 (± 0.0168),1396.0,gelu,0.50,0.25,6600,4,600,94,51,0.000480,AdamW,Cosine,0.000017
312,0.6644 (± 0.006),0.7215 (± 0.0066),0.7301 (± 0.0068),0.6644 (± 0.006),0.6264 (± 0.0164),0.5636 (± 0.0298),0.7063 (± 0.0063),750.0,gelu,0.45,0.40,3700,2,794,72,71,0.000110,Adam,Cosine,0.000230

In [46]:
name = 'NCI'
method = "Transformer"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 15:35:28,334] Using an existing study with name 'Transformer' instead of creating a new one.

(26, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
79,0.6656 (± 0.0049),0.7233 (± 0.0075),0.7314 (± 0.0062),0.6656 (± 0.0049),0.6375 (± 0.0122),0.5888 (± 0.0246),0.6959 (± 0.0097),NaN,relu,0.15,0.35,800,5,694,68,51,0.000246,Adam,None,0.000004
308,0.667 (± 0.0033),0.7227 (± 0.008),0.7298 (± 0.0052),0.667 (± 0.0033),0.6451 (± 0.0056),0.6054 (± 0.0134),0.6906 (± 0.0075),1254.0,gelu,0.30,0.10,5500,4,980,64,37,0.000011,Adam,Cosine,0.000743
124,0.6688 (± 0.0047),0.7224 (± 0.0042),0.7306 (± 0.0045),0.6688 (± 0.0047),0.6534 (± 0.0118),0.6248 (± 0.0243),0.6853 (± 0.0041),NaN,relu,0.35,0.40,1200,2,631,155,116,0.000012,AdamW,None,0.005146
200,0.6661 (± 0.0037),0.7223 (± 0.0058),0.7298 (± 0.0059),0.6661 (± 0.0037),0.6375 (± 0.008),0.5874 (± 0.0176),0.6973 (± 0.0093),920.0,gelu,0.10,0.20,1900,4,563,84,69,0.000074,AdamW,Cosine,0.000094
467,0.669 (± 0.0056),0.7217 (± 0.0064),0.7297 (± 0.0064),0.669 (± 0.0056),0.6618 (± 0.0065),0.6478 (± 0.0131),0.6766 (± 0.0082),NaN,relu,0.50,0.20,1300,4,743,86,58,0.000011,Adam,None,0.000405

In [52]:
name = 'NCI'
method = "GATv2"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}_rbf.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=f"{method}_wo_rbf",
    load_if_exists=True,
)

tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
print(df.shape)
# df.columns = [i.replace('user_attrs_', '') for i in df.columns]
# parsed_df = get_parsed_df(df)
# parsed_df = pd.concat([parsed_df, tmp], axis=1)
# parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 15:38:06,671] Using an existing study with name 'GATv2_wo_rbf' instead of creating a new one.

(0, 0)

In [59]:
name = 'NCI'
method = "Transformer"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}_rbf.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=f"{method}_wo_rbf",
    load_if_exists=True,
)

tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
print(df.shape)
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 15:38:53,896] Using an existing study with name 'Transformer_wo_rbf' instead of creating a new one.

(1, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
63,0.6234 (± 0.011),0.6604 (± 0.0101),0.6723 (± 0.009),0.6234 (± 0.011),0.5896 (± 0.0234),0.5423 (± 0.0393),0.6476 (± 0.0126),30.0,relu,0.5,0.1,100,2,840,79,76,0.000016,Adam,Cosine,0.001838

In [58]:
df

,ACC_mean,ACC_std,AUPR_mean,AUPR_std,AUROC_mean,AUROC_std,Balanced_ACC_mean,Balanced_ACC_std,Brier_mean,Brier_std,...,LogLoss_mean,LogLoss_std,MCC_mean,MCC_std,Precision_mean,Precision_std,Recall_mean,Recall_std,Specificity_mean,Specificity_std
63,0.623418,0.011025,0.660442,0.01015,0.67234,0.009036,0.623418,0.011025,0.230373,0.003368,...,0.653514,0.00743,0.250525,0.021086,0.647639,0.012605,0.542265,0.039347,0.704571,0.028302

In [39]:
name = 'GDSC1'
method = "GATv2"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 14:20:17,284] Using an existing study with name 'GATv2' instead of creating a new one.

(30, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
67,0.8447 (± 0.0041),0.9617 (± 0.0022),0.962 (± 0.0017),0.8447 (± 0.0041),0.8226 (± 0.0054),0.7204 (± 0.0076),0.9587 (± 0.0025),NaN,gelu,0.30,0.30,7900,4,877,88,34,0.000042,Adam,None,0.000086
38,0.8394 (± 0.0113),0.9613 (± 0.001),0.9615 (± 0.0007),0.8394 (± 0.0113),0.8149 (± 0.0165),0.7081 (± 0.0275),0.9604 (± 0.0049),4564.0,gelu,0.40,0.10,9600,5,328,217,43,0.000372,Adam,Cosine,0.000001
55,0.8474 (± 0.0025),0.961 (± 0.001),0.9613 (± 0.0009),0.8474 (± 0.0025),0.8266 (± 0.0034),0.7275 (± 0.0058),0.9569 (± 0.0028),1759.0,relu,0.25,0.30,4300,2,677,367,174,0.000092,AdamW,Cosine,0.000212
112,0.8396 (± 0.0032),0.9608 (± 0.0007),0.9612 (± 0.0006),0.8396 (± 0.0032),0.8153 (± 0.005),0.7085 (± 0.0095),0.9602 (± 0.0036),NaN,relu,0.15,0.25,3300,3,743,85,73,0.000104,AdamW,None,0.000013
45,0.8301 (± 0.0105),0.9606 (± 0.002),0.9611 (± 0.0014),0.8301 (± 0.0105),0.8013 (± 0.0152),0.6859 (± 0.0229),0.9638 (± 0.0025),NaN,relu,0.30,0.15,3000,5,277,89,48,0.001271,Adam,None,0.000020

In [40]:
name = 'GDSC1'
method = "Transformer"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False).head()

[I 2025-04-04 14:20:17,583] Using an existing study with name 'Transformer' instead of creating a new one.

(37, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
32,0.8459 (± 0.0025),0.9615 (± 0.0016),0.9616 (± 0.0013),0.8459 (± 0.0025),0.8244 (± 0.0033),0.7235 (± 0.0049),0.958 (± 0.0026),3562.0,relu,0.25,0.40,9300,4,587,76,34,0.000217,Adam,Cosine,0.000201
119,0.8342 (± 0.0024),0.9615 (± 0.0014),0.9616 (± 0.0011),0.8342 (± 0.0024),0.8072 (± 0.0033),0.6944 (± 0.0048),0.9639 (± 0.0016),1585.0,relu,0.30,0.35,4400,2,409,330,175,0.000013,Adam,Cosine,0.000003
55,0.8442 (± 0.0043),0.9613 (± 0.0019),0.9615 (± 0.0016),0.8442 (± 0.0043),0.8221 (± 0.0055),0.72 (± 0.0073),0.958 (± 0.0022),NaN,relu,0.40,0.40,3800,6,348,67,52,0.000064,Adam,None,0.000004
94,0.8412 (± 0.0039),0.9609 (± 0.0011),0.9609 (± 0.0009),0.8412 (± 0.0039),0.8176 (± 0.0055),0.7121 (± 0.0089),0.9599 (± 0.0024),3470.0,gelu,0.10,0.40,8600,3,723,146,74,0.000115,Adam,Cosine,0.000121
103,0.8317 (± 0.0027),0.9609 (± 0.0007),0.9611 (± 0.0006),0.8317 (± 0.0027),0.8036 (± 0.0039),0.6889 (± 0.0059),0.9643 (± 0.0011),1505.0,relu,0.35,0.45,7200,5,786,81,77,0.000020,Adam,Cosine,0.000807

In [41]:
name = 'GDSC2'
method = "GATv2"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False)

[I 2025-04-04 14:20:18,266] Using an existing study with name 'GATv2' instead of creating a new one.

(22, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
39,0.8537 (± 0.0044),0.9725 (± 0.0009),0.9724 (± 0.0011),0.8537 (± 0.0044),0.8323 (± 0.006),0.7263 (± 0.0096),0.9747 (± 0.0021),NaN,relu,0.30,0.45,7900,8,267,125,47,0.000032,AdamW,None,0.000009
27,0.847 (± 0.0115),0.9718 (± 0.0019),0.972 (± 0.0016),0.847 (± 0.0115),0.8229 (± 0.0161),0.7121 (± 0.0248),0.9751 (± 0.0021),NaN,gelu,0.30,0.15,7700,8,917,95,67,0.000293,Adam,None,0.000002
50,0.8645 (± 0.0073),0.9717 (± 0.0016),0.9717 (± 0.0016),0.8645 (± 0.0073),0.8472 (± 0.0096),0.7521 (± 0.016),0.9701 (± 0.0032),NaN,gelu,0.30,0.10,5500,3,649,178,114,0.000034,AdamW,None,0.000153
23,0.8515 (± 0.0121),0.9717 (± 0.0013),0.9719 (± 0.001),0.8515 (± 0.0121),0.8295 (± 0.0169),0.7234 (± 0.0278),0.9727 (± 0.004),2112.0,relu,0.40,0.40,7500,7,957,67,61,0.003694,Adam,Cosine,0.000011
71,0.8549 (± 0.0019),0.9716 (± 0.0015),0.9715 (± 0.0015),0.8549 (± 0.0019),0.8344 (± 0.0031),0.7311 (± 0.0068),0.9718 (± 0.0039),NaN,gelu,0.30,0.10,1600,4,330,170,54,0.000302,Adam,None,0.000020
53,0.8535 (± 0.0053),0.9715 (± 0.0017),0.9716 (± 0.0015),0.8535 (± 0.0053),0.8323 (± 0.0072),0.7272 (± 0.0114),0.9728 (± 0.0022),NaN,gelu,0.35,0.45,2500,6,920,140,50,0.000072,AdamW,None,0.000005
41,0.8438 (± 0.0115),0.9715 (± 0.0011),0.9718 (± 0.0009),0.8438 (± 0.0115),0.8185 (± 0.0165),0.7055 (± 0.0274),0.9755 (± 0.005),823.0,relu,0.20,0.40,1700,3,508,218,94,0.000044,AdamW,Cosine,0.007795
58,0.8418 (± 0.0162),0.9714 (± 0.0027),0.9714 (± 0.0023),0.8418 (± 0.0162),0.8153 (± 0.0234),0.7002 (± 0.0347),0.9769 (± 0.0027),NaN,relu,0.10,0.50,8400,5,638,81,69,0.001154,Adam,None,0.000011
22,0.8478 (± 0.002),0.9714 (± 0.0019),0.9717 (± 0.0016),0.8478 (± 0.002),0.8243 (± 0.0028),0.714 (± 0.0048),0.9747 (± 0.0025),1821.0,gelu,0.50,0.10,5300,4,557,70,63,0.001543,AdamW,Cosine,0.000456
18,0.8575 (± 0.0077),0.9714 (± 0.0015),0.9715 (± 0.0013),0.8575 (± 0.0077),0.8378 (± 0.0108),0.737 (± 0.0187),0.971 (± 0.0045),NaN,relu,0.10,0.30,5400,3,998,136,71,0.000342,Adam,None,0.000014
40,0.8537 (± 0.0038),0.9714 (± 0.0015),0.9708 (± 0.0014),0.8537 (± 0.0038),0.8327 (± 0.0048),0.7281 (± 0.0064),0.9724 (± 0.0028),NaN,relu,0.20,0.50,8700,3,866,367,255,0.000118,Adam,None,0.000004
70,0.8355 (± 0.0065),0.9714 (± 0.0014),0.9714 (± 0.0012),0.8355 (± 0.0065),0.8067 (± 0.0093),0.6867 (± 0.0143),0.9776 (± 0.002),960.0,gelu,0.25,0.20,3300,4,628,69,39,0.000082,Adam,Cosine,0.000002
46,0.8514 (± 0.0059),0.9713 (± 0.0022),0.9712 (± 0.0022),0.8514 (± 0.0059),0.8295 (± 0.0081),0.7234 (± 0.0127),0.9724 (± 0.0043),NaN,relu,0.15,0.10,6600,2,751,406,42,0.000407,AdamW,None,0.000008
38,0.8481 (± 0.0062),0.9712 (± 0.0007),0.9715 (± 0.0007),0.8481 (± 0.0062),0.8251 (± 0.0087),0.7168 (± 0.0141),0.9721 (± 0.0019),383.0,relu,0.10,0.20,1800,5,371,142,80,0.000046,AdamW,Cosine,0.000081
68,0.8493 (± 0.0067),0.9707 (± 0.0008),0.9706 (± 0.001),0.8493 (± 0.0067),0.8265 (± 0.0098),0.7183 (± 0.0171),0.9735 (± 0.0047),2148.0,gelu,0.45,0.20,8300,3,935,106,47,0.002044,AdamW,Cosine,0.000790
66,0.8492 (± 0.0097),0.9705 (± 0.0016),0.971 (± 0.0016),0.8492 (± 0.0097),0.8268 (± 0.0141),0.7206 (± 0.0242),0.9703 (± 0.0067),NaN,gelu,0.25,0.40,1400,3,994,149,55,0.000025,Adam,None,0.000445
31,0.8549 (± 0.0026),0.9703 (± 0.0017),0.9709 (± 0.0014),0.8549 (± 0.0026),0.8348 (± 0.0038),0.7334 (± 0.0075),0.9688 (± 0.0039),616.0,relu,0.35,0.50,1800,3,897,407,106,0.000011,Adam,Cosine,0.000039
29,0.833 (± 0.0087),0.9698 (± 0.0023),0.9707 (± 0.0018),0.833 (± 0.0087),0.8034 (± 0.0126),0.6832 (± 0.0191),0.9755 (± 0.0035),NaN,gelu,0.40,0.15,1400,2,263,98,42,0.000057,Adam,None,0.000013
83,0.8349 (± 0.0125),0.9698 (± 0.0015),0.9702 (± 0.0015),0.8349 (± 0.0125),0.8062 (± 0.0184),0.6878 (± 0.0303),0.9748 (± 0.0066),491.0,relu,0.35,0.35,1600,5,972,101,68,0.005240,Adam,Cosine,0.000597
30,0.8524 (± 0.0146),0.969 (± 0.0015),0.9697 (± 0.0018),0.8524 (± 0.0146),0.8318 (± 0.0209),0.7324 (± 0.0394),0.9643 (± 0.0115),NaN,gelu,0.10,0.15,4200,6,517,228,82,0.000672,Adam,None,0.001917
24,0.8245 (± 0.021),0.9688 (± 0.001),0.9697 (± 0.0009),0.8245 (± 0.021),0.7904 (± 0.0321),0.6652 (± 0.0486),0.9769 (± 0.0081),259.0,gelu,0.35,0.20,1200,6,708,69,49,0.008266,Adam,Cosine,0.000893
35,0.8349 (± 0.0218),0.9672 (± 0.0037),0.9684 (± 0.0033),0.8349 (± 0.0218),0.8061 (± 0.0326),0.69 (± 0.0503),0.972 (± 0.0078),125.0,gelu,0.45,0.30,300,6,321,182,100,0.001046,Adam,Cosine,0.000616
37,0.82 (± 0.0264),0.9671 (± 0.0043),0.9679 (± 0.0042),0.82 (± 0.0264),0.7837 (± 0.0397),0.657 (± 0.0596),0.9755 (± 0.0083),1178.0,gelu,0.10,0.40,5200,3,330,110,49,0.009722,Adam,Cosine,0.000581
65,0.8103 (± 0.039),0.9648 (± 0.0014),0.9654 (± 0.0017),0.8103 (± 0.039),0.7674 (± 0.0625),0.6357 (± 0.0856),0.9779 (± 0.0101),NaN,relu,0.10,0.20,2200,4,325,195,94,0.008391,Adam,None,0.004359
47,0.535 (± 0.0782),0.9623 (± 0.0018),0.9626 (± 0.0018),0.535 (± 0.0782),0.1039 (± 0.2323),0.0703 (± 0.1572),0.199 (± 0.445),NaN,gelu,0.40,0.40,7900,2,973,365,151,0.004436,Adam,None,0.004553
16,0.8126 (± 0.0807),0.9573 (± 0.0299),0.9607 (± 0.0222),0.8126 (± 0.0807),0.7655 (± 0.1349),0.6474 (± 0.158),0.9632 (± 0.0197),1996.0,relu,0.20,0.40,5600,2,437,275,131,0.007113,AdamW,Cosine,0.000002
34,0.68 (± 0.1508),0.9114 (± 0.0546),0.9246 (± 0.0501),0.68 (± 0.1508),0.4766 (± 0.3491),0.3804 (± 0.3193),0.7635 (± 0.4275),NaN,relu,0.45,0.25,9200,5,816,173,161,0.006825,AdamW,None,0.000029
57,0.6163 (± 0.1342),0.8646 (± 0.2039),0.8655 (± 0.2044),0.6163 (± 0.1342),0.3195 (± 0.348),0.2381 (± 0.2768),0.5902 (± 0.5389),NaN,relu,0.45,0.30,7000,2,844,219,219,0.006704,Adam,None,0.002793

In [42]:
name = 'GDSC2'
method = "Transformer"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df.sort_values('AUPR', ascending=False)

[I 2025-04-04 14:20:18,512] Using an existing study with name 'Transformer' instead of creating a new one.

(28, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
90,0.8539 (± 0.0049),0.9727 (± 0.0008),0.9721 (± 0.0007),0.8539 (± 0.0049),0.8324 (± 0.0067),0.7262 (± 0.0105),0.9752 (± 0.0023),NaN,relu,0.30,0.20,2600,3,1021,104,60,0.000093,AdamW,None,0.000044
54,0.8516 (± 0.0043),0.9722 (± 0.0011),0.9722 (± 0.001),0.8516 (± 0.0043),0.8294 (± 0.0061),0.7217 (± 0.01),0.9751 (± 0.0035),242.0,gelu,0.30,0.40,1100,6,861,142,136,0.000210,AdamW,Cosine,0.000818
84,0.8492 (± 0.0023),0.972 (± 0.001),0.9718 (± 0.0009),0.8492 (± 0.0023),0.826 (± 0.0031),0.716 (± 0.0049),0.9759 (± 0.0009),NaN,relu,0.20,0.45,5800,2,347,89,80,0.000024,AdamW,None,0.000007
28,0.8506 (± 0.0067),0.9719 (± 0.0018),0.972 (± 0.0018),0.8506 (± 0.0067),0.8282 (± 0.0094),0.7207 (± 0.0153),0.9737 (± 0.0031),1308.0,gelu,0.35,0.50,2700,3,372,302,115,0.000038,Adam,Cosine,0.000022
38,0.8485 (± 0.0031),0.9719 (± 0.0016),0.9719 (± 0.0016),0.8485 (± 0.0031),0.8255 (± 0.0045),0.7165 (± 0.0081),0.9737 (± 0.0032),1794.0,gelu,0.50,0.40,4300,4,584,118,92,0.000939,Adam,Cosine,0.000181
17,0.856 (± 0.0069),0.9719 (± 0.0016),0.9718 (± 0.0015),0.856 (± 0.0069),0.8355 (± 0.0092),0.7319 (± 0.0142),0.9736 (± 0.0023),1375.0,gelu,0.30,0.35,6100,3,417,238,87,0.000174,Adam,Cosine,0.000996
18,0.8561 (± 0.0039),0.9719 (± 0.0014),0.9721 (± 0.001),0.8561 (± 0.0039),0.8358 (± 0.0053),0.7327 (± 0.009),0.9727 (± 0.0026),1392.0,relu,0.30,0.45,5700,2,850,457,52,0.000101,Adam,Cosine,0.001175
13,0.8566 (± 0.0025),0.9718 (± 0.0014),0.9718 (± 0.0011),0.8566 (± 0.0025),0.8365 (± 0.0035),0.7338 (± 0.006),0.9727 (± 0.0022),333.0,gelu,0.40,0.25,1000,2,691,308,225,0.000252,AdamW,Cosine,0.003546
35,0.8492 (± 0.0036),0.9717 (± 0.0016),0.9719 (± 0.0014),0.8492 (± 0.0036),0.8262 (± 0.0049),0.7174 (± 0.0077),0.9741 (± 0.0032),2223.0,gelu,0.50,0.40,9000,3,316,95,82,0.000011,Adam,Cosine,0.000067
15,0.8542 (± 0.0094),0.9717 (± 0.0008),0.9719 (± 0.0008),0.8542 (± 0.0094),0.8333 (± 0.0133),0.7297 (± 0.0223),0.9717 (± 0.004),NaN,relu,0.25,0.15,3300,2,782,95,49,0.001270,Adam,None,0.000002
62,0.8508 (± 0.0032),0.9716 (± 0.0017),0.9716 (± 0.0016),0.8508 (± 0.0032),0.8284 (± 0.0044),0.7206 (± 0.007),0.9743 (± 0.0021),1001.0,gelu,0.30,0.35,4800,2,653,432,83,0.000011,AdamW,Cosine,0.000203
83,0.846 (± 0.0058),0.9716 (± 0.0014),0.9715 (± 0.0013),0.846 (± 0.0058),0.8218 (± 0.0083),0.7104 (± 0.0137),0.9749 (± 0.003),NaN,relu,0.15,0.45,1200,5,556,164,61,0.000073,Adam,None,0.000001
36,0.8503 (± 0.0028),0.9715 (± 0.0017),0.9714 (± 0.0018),0.8503 (± 0.0028),0.8277 (± 0.0041),0.7196 (± 0.0073),0.9742 (± 0.0024),1949.0,gelu,0.15,0.25,4900,2,678,240,177,0.000029,Adam,Cosine,0.000007
4,0.8511 (± 0.0032),0.9715 (± 0.0013),0.9713 (± 0.0011),0.8511 (± 0.0032),0.8287 (± 0.004),0.7206 (± 0.0054),0.9751 (± 0.0021),NaN,relu,0.35,0.35,4800,7,823,108,61,0.000012,AdamW,None,0.003078
11,0.8541 (± 0.0032),0.9714 (± 0.0012),0.9712 (± 0.001),0.8541 (± 0.0032),0.8331 (± 0.0041),0.728 (± 0.0056),0.9736 (± 0.0014),1677.0,relu,0.10,0.10,6700,2,418,363,225,0.000252,AdamW,Cosine,0.000060
82,0.8534 (± 0.0036),0.9712 (± 0.0017),0.971 (± 0.0015),0.8534 (± 0.0036),0.8322 (± 0.0047),0.7272 (± 0.0068),0.9727 (± 0.0028),2569.0,relu,0.30,0.20,5800,2,347,180,45,0.000051,Adam,Cosine,0.000006
3,0.8541 (± 0.0037),0.9712 (± 0.0017),0.9718 (± 0.0012),0.8541 (± 0.0037),0.8335 (± 0.005),0.7305 (± 0.0078),0.9703 (± 0.0012),2024.0,relu,0.50,0.50,4500,2,314,92,66,0.000250,Adam,Cosine,0.000763
39,0.8462 (± 0.0064),0.9711 (± 0.0014),0.9715 (± 0.0015),0.8462 (± 0.0064),0.8223 (± 0.009),0.7122 (± 0.0146),0.9729 (± 0.0029),NaN,gelu,0.35,0.20,1600,3,564,228,105,0.002061,Adam,None,0.000120
61,0.8552 (± 0.002),0.9711 (± 0.0009),0.9708 (± 0.0008),0.8552 (± 0.002),0.835 (± 0.0027),0.7327 (± 0.0047),0.9704 (± 0.0021),NaN,gelu,0.20,0.35,5100,2,534,381,232,0.000194,Adam,None,0.000019
16,0.8645 (± 0.0078),0.971 (± 0.0015),0.9713 (± 0.001),0.8645 (± 0.0078),0.8477 (± 0.011),0.755 (± 0.0206),0.9668 (± 0.0056),NaN,relu,0.40,0.15,600,4,680,194,191,0.000969,AdamW,None,0.000001
46,0.8417 (± 0.006),0.9709 (± 0.0017),0.9714 (± 0.0014),0.8417 (± 0.006),0.8159 (± 0.0085),0.7016 (± 0.0133),0.9748 (± 0.0031),244.0,gelu,0.45,0.50,600,2,898,131,71,0.000203,Adam,Cosine,0.000344
87,0.8496 (± 0.0163),0.9709 (± 0.0007),0.9709 (± 0.001),0.8496 (± 0.0163),0.827 (± 0.0239),0.7214 (± 0.0389),0.9706 (± 0.0071),2336.0,gelu,0.45,0.30,7700,2,349,99,39,0.004217,Adam,Cosine,0.000870
27,0.8521 (± 0.0109),0.9707 (± 0.0021),0.9711 (± 0.0022),0.8521 (± 0.0109),0.8308 (± 0.0153),0.7275 (± 0.0254),0.969 (± 0.0054),335.0,relu,0.15,0.10,1400,3,528,111,76,0.001607,Adam,Cosine,0.000737
10,0.8553 (± 0.0237),0.9688 (± 0.0052),0.969 (± 0.0052),0.8553 (± 0.0237),0.8348 (± 0.0326),0.736 (± 0.053),0.967 (± 0.0071),NaN,gelu,0.20,0.45,8900,2,804,414,186,0.000798,Adam,None,0.000588
64,0.8482 (± 0.0066),0.9667 (± 0.0053),0.9676 (± 0.0041),0.8482 (± 0.0066),0.8263 (± 0.0088),0.7224 (± 0.0145),0.9655 (± 0.0094),2188.0,gelu,0.20,0.40,8400,2,615,356,194,0.000624,Adam,Cosine,0.000003

In [43]:
name = 'CTRP'
method = "GATv2"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df

[I 2025-04-04 14:20:18,854] Using an existing study with name 'GATv2' instead of creating a new one.

(25, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.8189 (± 0.0062),0.9024 (± 0.0054),0.9042 (± 0.0047),0.8189 (± 0.0062),0.8082 (± 0.0082),0.7634 (± 0.018),0.8589 (± 0.0109),1687.0,gelu,0.30,0.35,8300,3,942,93,65,0.005514,AdamW,Cosine,0.000003
3,0.8169 (± 0.004),0.9059 (± 0.002),0.9072 (± 0.0009),0.8169 (± 0.004),0.8019 (± 0.0068),0.7416 (± 0.0166),0.8733 (± 0.0071),NaN,gelu,0.30,0.20,5800,4,706,70,44,0.000076,AdamW,None,0.000001
6,0.8118 (± 0.0125),0.9025 (± 0.0047),0.9044 (± 0.0034),0.8118 (± 0.0125),0.7963 (± 0.0194),0.7373 (± 0.0377),0.8669 (± 0.0107),3518.0,gelu,0.40,0.10,9100,3,373,283,176,0.002626,AdamW,Cosine,0.001886
14,0.8169 (± 0.0023),0.8998 (± 0.0017),0.904 (± 0.0014),0.8169 (± 0.0023),0.8044 (± 0.0034),0.7529 (± 0.0078),0.8636 (± 0.0046),778.0,gelu,0.10,0.50,1800,3,740,88,66,0.000105,AdamW,Cosine,0.000122
19,0.8185 (± 0.0012),0.8974 (± 0.0009),0.8997 (± 0.0005),0.8185 (± 0.0012),0.8092 (± 0.0013),0.7697 (± 0.002),0.8529 (± 0.0017),1591.0,gelu,0.30,0.20,4600,4,283,66,41,0.000885,Adam,Cosine,0.009381
29,0.8134 (± 0.0034),0.9007 (± 0.0017),0.9039 (± 0.0014),0.8134 (± 0.0034),0.7989 (± 0.0049),0.7416 (± 0.0094),0.8659 (± 0.0018),970.0,gelu,0.40,0.15,4300,6,549,92,33,0.000047,Adam,Cosine,0.000006
30,0.8198 (± 0.0021),0.8977 (± 0.0006),0.902 (± 0.0008),0.8198 (± 0.0021),0.8122 (± 0.0054),0.7797 (± 0.0189),0.848 (± 0.0104),2352.0,gelu,0.30,0.20,7500,2,1018,322,54,0.000012,Adam,Cosine,0.003032
31,0.7962 (± 0.0061),0.8944 (± 0.0022),0.9008 (± 0.0012),0.7962 (± 0.0061),0.7722 (± 0.0107),0.6918 (± 0.0219),0.8746 (± 0.0082),141.0,relu,0.50,0.45,400,8,1013,128,58,0.000509,Adam,Cosine,0.000006
34,0.8057 (± 0.0112),0.896 (± 0.0026),0.8999 (± 0.0012),0.8057 (± 0.0112),0.7888 (± 0.0186),0.7281 (± 0.0415),0.8625 (± 0.0125),44.0,gelu,0.50,0.40,100,3,962,270,142,0.001312,Adam,Cosine,0.000018
35,0.8193 (± 0.002),0.9062 (± 0.0016),0.907 (± 0.0007),0.8193 (± 0.002),0.8059 (± 0.0031),0.7502 (± 0.0063),0.8706 (± 0.0015),2577.0,gelu,0.50,0.40,5700,4,866,121,83,0.000100,AdamW,Cosine,0.000029
38,0.8187 (± 0.0027),0.9014 (± 0.0016),0.9047 (± 0.0015),0.8187 (± 0.0027),0.808 (± 0.0042),0.7631 (± 0.0111),0.8588 (± 0.0064),2389.0,gelu,0.20,0.10,6600,4,888,73,59,0.000016,Adam,Cosine,0.000037
44,0.8183 (± 0.0041),0.9 (± 0.0012),0.9037 (± 0.0008),0.8183 (± 0.0041),0.8075 (± 0.0074),0.7628 (± 0.0193),0.8584 (± 0.0079),NaN,gelu,0.25,0.20,3700,2,319,184,80,0.000017,AdamW,None,0.000131
47,0.8141 (± 0.0111),0.9018 (± 0.0027),0.9031 (± 0.0026),0.8141 (± 0.0111),0.8006 (± 0.0166),0.7478 (± 0.0317),0.8623 (± 0.0056),NaN,gelu,0.45,0.45,8900,2,999,84,35,0.003299,Adam,None,0.000032
68,0.8181 (± 0.0059),0.9037 (± 0.0037),0.9049 (± 0.0035),0.8181 (± 0.0059),0.8056 (± 0.0089),0.7546 (± 0.0193),0.8644 (± 0.0082),NaN,gelu,0.40,0.45,2400,4,326,70,53,0.002120,Adam,None,0.000010
69,0.8193 (± 0.0011),0.9028 (± 0.0019),0.9052 (± 0.0014),0.8193 (± 0.0011),0.8082 (± 0.0013),0.7618 (± 0.0043),0.8608 (± 0.0041),1787.0,gelu,0.10,0.50,4700,2,711,247,150,0.000025,Adam,Cosine,0.000004
78,0.821 (± 0.0013),0.906 (± 0.0023),0.9072 (± 0.002),0.821 (± 0.0013),0.8087 (± 0.0029),0.7569 (± 0.0108),0.8684 (± 0.008),1378.0,gelu,0.15,0.25,6500,3,382,151,106,0.000252,AdamW,Cosine,0.000002
85,0.8159 (± 0.0066),0.9001 (± 0.0035),0.9021 (± 0.0034),0.8159 (± 0.0066),0.8041 (± 0.0114),0.757 (± 0.0293),0.8586 (± 0.0135),NaN,relu,0.35,0.40,8500,2,916,209,39,0.001128,Adam,None,0.000168
89,0.8154 (± 0.0014),0.8973 (± 0.0014),0.8996 (± 0.0008),0.8154 (± 0.0014),0.8049 (± 0.0023),0.7618 (± 0.0061),0.8532 (± 0.0031),2802.0,relu,0.10,0.35,5900,4,986,70,52,0.004568,Adam,Cosine,0.000218
99,0.817 (± 0.0023),0.901 (± 0.0055),0.903 (± 0.0045),0.817 (± 0.0023),0.8052 (± 0.0018),0.7567 (± 0.0075),0.8605 (± 0.0094),1249.0,relu,0.15,0.35,3400,4,670,149,39,0.000849,Adam,Cosine,0.000019
104,0.8213 (± 0.0036),0.9048 (± 0.0032),0.907 (± 0.0015),0.8213 (± 0.0036),0.8095 (± 0.0064),0.7596 (± 0.0164),0.8667 (± 0.0069),2105.0,gelu,0.50,0.40,5300,2,971,242,73,0.000221,AdamW,Cosine,0.000002
108,0.8202 (± 0.0022),0.8985 (± 0.0009),0.9026 (± 0.001),0.8202 (± 0.0022),0.812 (± 0.004),0.777 (± 0.011),0.8505 (± 0.0049),NaN,gelu,0.25,0.15,1800,2,362,224,162,0.000030,Adam,None,0.000010
111,0.8166 (± 0.002),0.8996 (± 0.001),0.9033 (± 0.0007),0.8166 (± 0.002),0.8048 (± 0.0029),0.7562 (± 0.0065),0.8602 (± 0.0033),NaN,relu,0.10,0.35,1900,2,494,417,44,0.000043,Adam,None,0.000010

In [44]:
name = 'CTRP'
method = "Transformer"  # 任意のstudy名
storage_path = f"./Tuning_{name}/{method}.sqlite3"  # "./subdir"は1階層下のディレクトリ
study = optuna.create_study(
    storage=f"sqlite:///{storage_path}",
    study_name=method,
    load_if_exists=True,
)
print(df.shape)
tmp = study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3'])
tmp = tmp[[i for i in tmp.columns if 'params' in i]]
df = (study.trials_dataframe().dropna(subset=['values_0', 'values_1', 'values_2', 'values_3']).iloc[:, 21:-2])
df.columns = [i.replace('user_attrs_', '') for i in df.columns]
parsed_df = get_parsed_df(df)
parsed_df = pd.concat([parsed_df, tmp], axis=1)
parsed_df

[I 2025-04-04 14:20:19,380] Using an existing study with name 'Transformer' instead of creating a new one.

(22, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_epochs,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
8,0.8158 (± 0.0084),0.9035 (± 0.0029),0.906 (± 0.0013),0.8158 (± 0.0084),0.8011 (± 0.0144),0.7431 (± 0.032),0.8701 (± 0.0122),NaN,gelu,0.10,0.40,1300,2,685,111,75,0.000187,AdamW,None,0.000007
9,0.8212 (± 0.0013),0.9065 (± 0.0012),0.9075 (± 0.0007),0.8212 (± 0.0013),0.8096 (± 0.002),0.7606 (± 0.0047),0.8654 (± 0.0022),3575.0,relu,0.40,0.15,8100,2,459,118,60,0.000151,Adam,Cosine,0.000072
10,0.8187 (± 0.0031),0.903 (± 0.0028),0.905 (± 0.0014),0.8187 (± 0.0031),0.8072 (± 0.0054),0.7593 (± 0.0143),0.8619 (± 0.0077),NaN,gelu,0.45,0.45,1400,6,1010,64,36,0.000458,AdamW,None,0.000189
15,0.8156 (± 0.0038),0.8993 (± 0.001),0.901 (± 0.0011),0.8156 (± 0.0038),0.8047 (± 0.005),0.7598 (± 0.0089),0.8552 (± 0.0008),4359.0,relu,0.30,0.20,9300,2,446,69,41,0.000551,Adam,Cosine,0.008225
25,0.8194 (± 0.0028),0.9074 (± 0.0013),0.9081 (± 0.001),0.8194 (± 0.0028),0.8054 (± 0.004),0.7476 (± 0.0076),0.8729 (± 0.0016),NaN,gelu,0.45,0.20,7600,2,488,126,95,0.000023,Adam,None,0.000365
29,0.8213 (± 0.0033),0.9034 (± 0.0012),0.906 (± 0.0005),0.8213 (± 0.0033),0.8107 (± 0.0052),0.7656 (± 0.0122),0.8616 (± 0.0045),1114.0,gelu,0.15,0.20,2500,3,793,75,66,0.000021,AdamW,Cosine,0.000509
34,0.8232 (± 0.0025),0.9093 (± 0.0009),0.9093 (± 0.001),0.8232 (± 0.0025),0.8116 (± 0.0035),0.7616 (± 0.0071),0.8687 (± 0.0015),NaN,gelu,0.35,0.40,8900,2,413,281,60,0.000013,AdamW,None,0.000360
41,0.8213 (± 0.0004),0.908 (± 0.0009),0.908 (± 0.0009),0.8213 (± 0.0004),0.8084 (± 0.0008),0.7544 (± 0.0034),0.8709 (± 0.003),NaN,relu,0.25,0.15,9000,7,981,100,46,0.000036,AdamW,None,0.000276
46,0.8166 (± 0.0036),0.8989 (± 0.0017),0.9013 (± 0.0012),0.8166 (± 0.0036),0.8062 (± 0.0052),0.7633 (± 0.0108),0.8544 (± 0.0032),NaN,gelu,0.20,0.45,800,2,805,83,32,0.000018,Adam,None,0.000003
53,0.8209 (± 0.0031),0.907 (± 0.0015),0.9083 (± 0.0012),0.8209 (± 0.0031),0.8085 (± 0.0042),0.7564 (± 0.0089),0.8684 (± 0.005),NaN,relu,0.40,0.10,4300,2,875,146,92,0.000128,Adam,None,0.000573
75,0.8191 (± 0.0023),0.907 (± 0.0009),0.9078 (± 0.0012),0.8191 (± 0.0023),0.8054 (± 0.003),0.7488 (± 0.0052),0.8714 (± 0.0022),3486.0,relu,0.15,0.35,9400,2,499,79,64,0.000011,Adam,Cosine,0.000032
76,0.8136 (± 0.0147),0.8918 (± 0.0138),0.8979 (± 0.0053),0.8136 (± 0.0147),0.805 (± 0.0248),0.7733 (± 0.0569),0.8427 (± 0.0213),212.0,gelu,0.35,0.45,800,4,441,97,97,0.005503,Adam,Cosine,0.001207
77,0.8169 (± 0.0027),0.8978 (± 0.001),0.9013 (± 0.0016),0.8169 (± 0.0027),0.8059 (± 0.0047),0.7602 (± 0.0123),0.8575 (± 0.0059),2285.0,gelu,0.25,0.15,4600,3,475,216,36,0.001449,Adam,Cosine,0.000614
86,0.8178 (± 0.0026),0.904 (± 0.005),0.9054 (± 0.0029),0.8178 (± 0.0026),0.8046 (± 0.0049),0.7504 (± 0.0135),0.8675 (± 0.0082),NaN,gelu,0.20,0.15,9400,4,647,129,46,0.000375,AdamW,None,0.000006
98,0.8177 (± 0.0045),0.9052 (± 0.0036),0.9062 (± 0.0027),0.8177 (± 0.0045),0.8043 (± 0.0063),0.7496 (± 0.0121),0.8677 (± 0.0034),NaN,gelu,0.10,0.10,8600,3,571,80,60,0.000865,AdamW,None,0.000130
112,0.8202 (± 0.0008),0.9079 (± 0.0005),0.9082 (± 0.0007),0.8202 (± 0.0008),0.8072 (± 0.0014),0.7529 (± 0.0038),0.8699 (± 0.0024),2159.0,gelu,0.50,0.45,7400,3,427,152,125,0.000036,AdamW,Cosine,0.000424
127,0.8171 (± 0.0042),0.9051 (± 0.0029),0.9068 (± 0.0017),0.8171 (± 0.0042),0.8025 (± 0.0067),0.7437 (± 0.0145),0.8717 (± 0.0054),NaN,gelu,0.35,0.50,3100,4,595,107,45,0.000257,AdamW,None,0.001722
132,0.8161 (± 0.0029),0.8987 (± 0.0016),0.9029 (± 0.0012),0.8161 (± 0.0029),0.8041 (± 0.0045),0.7551 (± 0.011),0.8601 (± 0.0052),457.0,relu,0.20,0.15,1200,2,287,165,78,0.000025,Adam,Cosine,0.000674
150,0.8158 (± 0.0018),0.8988 (± 0.0008),0.9018 (± 0.0011),0.8158 (± 0.0018),0.8038 (± 0.0031),0.7547 (± 0.0081),0.8598 (± 0.0036),725.0,gelu,0.40,0.40,2100,2,427,131,104,0.000013,AdamW,Cosine,0.000408
167,0.8157 (± 0.0029),0.8997 (± 0.0011),0.9022 (± 0.0008),0.8157 (± 0.0029),0.8034 (± 0.0047),0.7532 (± 0.0111),0.8609 (± 0.004),531.0,relu,0.20,0.15,1200,2,407,157,38,0.000012,Adam,Cosine,0.000006
168,0.8154 (± 0.0021),0.9006 (± 0.001),0.9039 (± 0.0007),0.8154 (± 0.0021),0.8022 (± 0.0032),0.7486 (± 0.0067),0.8642 (± 0.0027),395.0,relu,0.10,0.30,900,2,960,232,181,0.000032,AdamW,Cosine,0.000094