In [1]:
import os
import sys

import optuna
import pandas as pd

current_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(parent_dir)

from metrics import get_parsed_df

In [2]:
task = 'drug'
method = "GATv2"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

# parsed_df if n > 0 else None

[I 2025-04-12 17:24:56,680] Using an existing study with name 'GATv2' instead of creating a new one.

(1, 22)

In [3]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [4]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [5]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [5]:
method = "Transformer"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 17:25:03,380] Using an existing study with name 'Transformer' instead of creating a new one.

(0, 0)

In [7]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [8]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [9]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.4055 (± 0.1893),0.6378 (± 0.1755),0.5035 (± 0.0648),0.5004 (± 0.0049),0.073 (± 0.2209),0.0879 (± 0.2718),0.0879 (± 0.2437),38,relu,0.45,0.15,6,769,91,35,0.000659,Adam,Cosine,0.002098

In [6]:
method = "GAT"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 17:25:05,381] Using an existing study with name 'GAT' instead of creating a new one.

(1, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.379 (± 0.1775),0.6363 (± 0.1739),0.5049 (± 0.0569),0.5001 (± 0.0035),0.009 (± 0.0702),0.0102 (± 0.0874),0.0262 (± 0.143),29.0,gelu,0.45,0.4,8,465,116,105,0.000336,Adam,Cosine,0.000016

In [11]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.379 (± 0.1775),0.6363 (± 0.1739),0.5049 (± 0.0569),0.5001 (± 0.0035),0.009 (± 0.0702),0.0102 (± 0.0874),0.0262 (± 0.143),29.0,gelu,0.45,0.4,8,465,116,105,0.000336,Adam,Cosine,0.000016

In [12]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.379 (± 0.1775),0.6363 (± 0.1739),0.5049 (± 0.0569),0.5001 (± 0.0035),0.009 (± 0.0702),0.0102 (± 0.0874),0.0262 (± 0.143),29.0,gelu,0.45,0.4,8,465,116,105,0.000336,Adam,Cosine,0.000016

In [13]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.379 (± 0.1775),0.6363 (± 0.1739),0.5049 (± 0.0569),0.5001 (± 0.0035),0.009 (± 0.0702),0.0102 (± 0.0874),0.0262 (± 0.143),29.0,gelu,0.45,0.4,8,465,116,105,0.000336,Adam,Cosine,0.000016

In [7]:
method = "MPNN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 19:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df.head() if n > 0 else None

[I 2025-04-12 17:25:19,541] Using an existing study with name 'MPNN' instead of creating a new one.

(4, 23)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.3781 (± 0.1777),0.6343 (± 0.1775),0.5041 (± 0.0656),0.5 (± 0.0),0.0001 (± 0.0013),0.0 (± 0.0007),0.0012 (± 0.0245),32.0,gelu,0.2,0.15,3,494,156,88,0.001613,AdamW,Cosine,0.000047
1,0.3781 (± 0.1777),0.6345 (± 0.1764),0.5042 (± 0.0638),0.5 (± 0.0002),0.0 (± 0.0008),0.0 (± 0.0004),0.0024 (± 0.049),NaN,gelu,0.2,0.20,8,454,391,154,0.000099,AdamW,None,0.000258
2,0.3781 (± 0.1777),0.6334 (± 0.1772),0.5015 (± 0.0646),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.4,0.30,2,897,220,44,0.000530,AdamW,None,0.000427
3,0.3781 (± 0.1777),0.6322 (± 0.1771),0.5 (± 0.067),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.4,0.40,4,405,211,46,0.000387,AdamW,None,0.001331

In [15]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.3781 (± 0.1777),0.6343 (± 0.1775),0.5041 (± 0.0656),0.5 (± 0.0),0.0001 (± 0.0013),0.0 (± 0.0007),0.0012 (± 0.0245),32.0,gelu,0.2,0.15,3,494,156,88,0.001613,AdamW,Cosine,0.000047
1,0.3781 (± 0.1777),0.6345 (± 0.1764),0.5042 (± 0.0638),0.5 (± 0.0002),0.0 (± 0.0008),0.0 (± 0.0004),0.0024 (± 0.049),NaN,gelu,0.2,0.20,8,454,391,154,0.000099,AdamW,None,0.000258
2,0.3781 (± 0.1777),0.6334 (± 0.1772),0.5015 (± 0.0646),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.4,0.30,2,897,220,44,0.000530,AdamW,None,0.000427

In [16]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1,0.3781 (± 0.1777),0.6345 (± 0.1764),0.5042 (± 0.0638),0.5 (± 0.0002),0.0 (± 0.0008),0.0 (± 0.0004),0.0024 (± 0.049),NaN,gelu,0.2,0.20,8,454,391,154,0.000099,AdamW,None,0.000258
0,0.3781 (± 0.1777),0.6343 (± 0.1775),0.5041 (± 0.0656),0.5 (± 0.0),0.0001 (± 0.0013),0.0 (± 0.0007),0.0012 (± 0.0245),32.0,gelu,0.2,0.15,3,494,156,88,0.001613,AdamW,Cosine,0.000047
2,0.3781 (± 0.1777),0.6334 (± 0.1772),0.5015 (± 0.0646),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.4,0.30,2,897,220,44,0.000530,AdamW,None,0.000427

In [17]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
1,0.3781 (± 0.1777),0.6345 (± 0.1764),0.5042 (± 0.0638),0.5 (± 0.0002),0.0 (± 0.0008),0.0 (± 0.0004),0.0024 (± 0.049),NaN,gelu,0.2,0.20,8,454,391,154,0.000099,AdamW,None,0.000258
0,0.3781 (± 0.1777),0.6343 (± 0.1775),0.5041 (± 0.0656),0.5 (± 0.0),0.0001 (± 0.0013),0.0 (± 0.0007),0.0012 (± 0.0245),32.0,gelu,0.2,0.15,3,494,156,88,0.001613,AdamW,Cosine,0.000047
2,0.3781 (± 0.1777),0.6334 (± 0.1772),0.5015 (± 0.0646),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.4,0.30,2,897,220,44,0.000530,AdamW,None,0.000427

In [8]:
method = "GCN"
study = optuna.create_study(
    storage=f"sqlite:///{method}_{task}_small.sqlite3",
    study_name=method,
    load_if_exists=True,
)
tmp = study.trials_dataframe().dropna(
    subset=["values_0", "values_1", "values_2", "values_3"]
)
tmp = tmp[[i for i in tmp.columns if "params" in i]]
df = (
    study.trials_dataframe()
    .dropna(subset=["values_0", "values_1", "values_2", "values_3"])
    .iloc[:, 20:-2]
)
df.columns = [i.replace("user_attrs_", "") for i in df.columns]

print(df.shape)
n = df.shape[0]
if n > 0:
    parsed_df = get_parsed_df(df)
    parsed_df = pd.concat([parsed_df, tmp], axis=1)
    parsed_df.sort_values("AUPR", ascending=False).head()

parsed_df if n > 0 else None

[I 2025-04-12 17:25:24,060] Using an existing study with name 'GCN' instead of creating a new one.

(12, 22)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
0,0.3781 (± 0.1777),0.6343 (± 0.1758),0.4979 (± 0.0648),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.35,0.40,7,706,176,114,0.000153,Adam,None,0.009340
1,0.3781 (± 0.1777),0.6387 (± 0.1742),0.5047 (± 0.0662),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.50,0.35,6,692,304,37,0.000385,Adam,None,0.000010
2,0.3781 (± 0.1777),0.6383 (± 0.1753),0.5045 (± 0.0641),0.5 (± 0.0004),0.0001 (± 0.0017),0.0001 (± 0.0009),0.0089 (± 0.0914),NaN,relu,0.10,0.25,4,450,154,79,0.000019,AdamW,None,0.001760
3,0.3781 (± 0.1777),0.6361 (± 0.1759),0.5052 (± 0.0683),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.35,0.45,2,496,237,92,0.002618,Adam,None,0.000048
4,0.3781 (± 0.1777),0.6369 (± 0.176),0.508 (± 0.0677),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.50,0.35,4,281,190,50,0.001437,AdamW,None,0.001508
5,0.3781 (± 0.1777),0.6364 (± 0.1739),0.4999 (± 0.0597),0.5 (± 0.0008),0.0002 (± 0.0019),0.0001 (± 0.001),0.0084 (± 0.0809),24.0,gelu,0.30,0.50,6,656,160,75,0.000032,Adam,Cosine,0.002935
6,0.3781 (± 0.1777),0.6383 (± 0.1748),0.5047 (± 0.0631),0.5 (± 0.001),0.0004 (± 0.0046),0.0002 (± 0.0024),0.0096 (± 0.0856),NaN,gelu,0.40,0.20,5,466,299,51,0.000025,AdamW,None,0.000005
7,0.3781 (± 0.1777),0.6351 (± 0.1765),0.5021 (± 0.067),0.5 (± 0.0),0.0 (± 0.0002),0.0 (± 0.0001),0.0024 (± 0.049),24.0,gelu,0.35,0.20,6,616,360,40,0.000718,Adam,Cosine,0.005065
8,0.3781 (± 0.1777),0.6353 (± 0.1777),0.5045 (± 0.071),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.35,0.35,7,561,351,39,0.004151,Adam,None,0.000065
9,0.378 (± 0.1777),0.6378 (± 0.1735),0.5026 (± 0.0616),0.5 (± 0.001),0.0001 (± 0.0013),0.0 (± 0.0007),0.0024 (± 0.049),26.0,gelu,0.30,0.30,4,469,145,59,0.000518,AdamW,Cosine,0.000167
10,0.3784 (± 0.178),0.6373 (± 0.1742),0.5046 (± 0.0629),0.5003 (± 0.0067),0.0013 (± 0.0245),0.0009 (± 0.0178),0.0101 (± 0.095),38.0,relu,0.30,0.30,3,358,254,50,0.000025,Adam,Cosine,0.000226
11,0.3781 (± 0.1777),0.6399 (± 0.1738),0.5073 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),20.0,gelu,0.50,0.25,2,617,403,114,0.002535,Adam,Cosine,0.000780

In [19]:
parsed_df.sort_values('ACC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
10,0.3784 (± 0.178),0.6373 (± 0.1742),0.5046 (± 0.0629),0.5003 (± 0.0067),0.0013 (± 0.0245),0.0009 (± 0.0178),0.0101 (± 0.095),38.0,relu,0.30,0.30,3,358,254,50,0.000025,Adam,Cosine,0.000226
0,0.3781 (± 0.1777),0.6343 (± 0.1758),0.4979 (± 0.0648),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.35,0.40,7,706,176,114,0.000153,Adam,None,0.009340
1,0.3781 (± 0.1777),0.6387 (± 0.1742),0.5047 (± 0.0662),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.50,0.35,6,692,304,37,0.000385,Adam,None,0.000010

In [20]:
parsed_df.sort_values('AUPR', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
11,0.3781 (± 0.1777),0.6399 (± 0.1738),0.5073 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),20.0,gelu,0.5,0.25,2,617,403,114,0.002535,Adam,Cosine,0.00078
1,0.3781 (± 0.1777),0.6387 (± 0.1742),0.5047 (± 0.0662),0.5 (± 0.0001),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.5,0.35,6,692,304,37,0.000385,Adam,None,0.00001
2,0.3781 (± 0.1777),0.6383 (± 0.1753),0.5045 (± 0.0641),0.5 (± 0.0004),0.0001 (± 0.0017),0.0001 (± 0.0009),0.0089 (± 0.0914),NaN,relu,0.1,0.25,4,450,154,79,0.000019,AdamW,None,0.00176

In [21]:
parsed_df.sort_values('AUROC', ascending=False).head(3)

,ACC,AUPR,AUROC,Balanced_ACC,F1,Recall,Precision,params_T_max,params_activation,params_dropout1,params_dropout2,params_heads,params_hidden1,params_hidden2,params_hidden3,params_lr,params_optimizer,params_scheduler,params_weight_decay
4,0.3781 (± 0.1777),0.6369 (± 0.176),0.508 (± 0.0677),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,gelu,0.50,0.35,4,281,190,50,0.001437,AdamW,None,0.001508
11,0.3781 (± 0.1777),0.6399 (± 0.1738),0.5073 (± 0.0655),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),20.0,gelu,0.50,0.25,2,617,403,114,0.002535,Adam,Cosine,0.000780
3,0.3781 (± 0.1777),0.6361 (± 0.1759),0.5052 (± 0.0683),0.5 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),0.0 (± 0.0),NaN,relu,0.35,0.45,2,496,237,92,0.002618,Adam,None,0.000048