In [1]:
import time
import xml.etree.ElementTree as ET

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import seaborn as sns
from IPython.display import HTML, display
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.patches import Patch
from tqdm import tqdm

display(HTML("<style>.container { width:100% !important; }</style>"))

# Preprocess for figure 2.
- Get the paper list
- eseach on PubMed
- make a table.

In [2]:
def search_pubmed(query, max_results=None):
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {"db": "pubmed", "term": query, "retmax": max_results}

    if max_results:
        params["retmax"] = max_results

    response = requests.get(base_url, params=params)

    if response.status_code == 200:
        root = ET.fromstring(response.content)
        pmids = [id_elem.text for id_elem in root.findall("IdList/Id")]
        return pmids
    elif response.status_code == 429:
        time.sleep(2)
        return search_pubmed(query, 300)
    else:
        print("Error: Unable to fetch data from PubMed")
        return []

In [3]:
def fetch_details(pmids):
    ids = ",".join(pmids)
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    params = {"db": "pubmed", "retmode": "xml", "id": ids}

    response = requests.get(base_url, params=params)
    if response.status_code != 200:
        print("Error: Unable to fetch details from PubMed")
        return None

    return response.content

In [4]:
def parse_pubmed_efetch(xml_data):
    root = ET.fromstring(xml_data)

    articles = []
    for article in root.findall(".//PubmedArticle"):
        title = article.find(".//ArticleTitle").text

        journal_title = article.find(".//Journal/Title").text

        authors = []
        for author in article.findall(".//Author"):
            lastname = author.find("LastName")
            firstname = author.find("ForeName")
            if lastname is not None and firstname is not None:
                authors.append(f"{firstname.text} {lastname.text}")

        pmcid = None
        for article_id in article.findall(".//ArticleId"):
            if article_id.get("IdType") == "pmc":
                pmcid = article_id.text
                break

        articles.append(
            {
                "title": title,
                "journal": journal_title,
                "authors": authors,
                "pmcid": pmcid,
            }
        )

    return articles

In [5]:
attention = pd.read_csv("val_attention.csv.gz", index_col=0)
attention

/tmp/ipykernel_3534472/1117812176.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  attention = pd.read_csv("val_attention.csv.gz", index_col=0)

,740,752,755,757,762,1390,1895,3053,3061,3088,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001185,0.001214,0.001265,0.001232,0.001272,0.001272,0.001120,0.001256,0.001263,0.001158
752,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001667,0.001711,0.001720,0.001663,0.001670,0.001596,0.001767,0.001658,0.001707,0.001732
755,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001897,0.001952,0.001939,0.001866,0.001854,0.001740,0.002123,0.001846,0.001921,0.002026
757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001321,0.001349,0.001393,0.001355,0.001384,0.001361,0.001299,0.001367,0.001389,0.001316
762,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002030,0.002095,0.002065,0.001984,0.001962,0.001831,0.002312,0.001959,0.002042,0.002188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.000543,0.000516,0.000517,0.000516,0.000560,0.000520,0.000578,0.000602,0.000550,0.000596,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNRD1,0.000369,0.000362,0.000363,0.000362,0.000381,0.000363,0.000388,0.000399,0.000376,0.000394,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZP3,0.000459,0.000439,0.000440,0.000441,0.000471,0.000442,0.000483,0.000507,0.000465,0.000497,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZSCAN18,0.000464,0.000439,0.000441,0.000442,0.000474,0.000442,0.000489,0.000520,0.000468,0.000505,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZYX,0.000354,0.000342,0.000341,0.000345,0.000357,0.000341,0.000365,0.000383,0.000357,0.000372,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [6]:
att_dg = attention.iloc[:1005, 1005+60:]
conv = dict(pd.read_csv("nsc_dti.csv", index_col=0)[["NSC", "Drug Name"]].values)

In [8]:
len(np.unique(attention.values))

5049645

In [10]:
results = []
pmid_list = []
for drug in tqdm(att_dg.index):
    genes = list(att_dg.loc[drug].sort_values(ascending=False).head(5).index)
    if drug == 759263:
        print(genes)

    for gene in genes:

        d = conv[int(drug)]
        if d == "benzaldehyde (BEN)":
            d = "benzaldehyde"
        elif "Derivative" in d:
            d = d[:-11]

        if "ADA" == gene:
            gene = "adenosine deaminase"

        pmids = search_pubmed("{} AND {}".format(d, gene), max_results=300)
        pmid_list.append([drug, gene, pmids])
        if pmids != None:
            details = fetch_details(pmids)
            if details != None:
                details = details.decode("utf-8")
                res = pd.DataFrame(parse_pubmed_efetch(details))
                if len(res) > 0:
                    results.append(
                        [
                            drug,
                            conv[int(drug)],
                            gene,
                            len(pmids),
                            # len(
                            #     (
                            #         res[
                            #             res.journal.str.lower().isin(
                            #                 set(j_list["Title"].str.lower())
                            #             )
                            #         ]
                            #     )
                            # ),
                        ]
                    )
                else:
                    results.append([drug, conv[int(drug)], gene, len(pmids), 0])
            else:
                results.append([drug, conv[int(drug)], gene, len(pmids), 0])
        else:
            results.append([drug, conv[int(drug)], gene, 0, 0])

  0%|          | 0/1005 [00:00<?, ?it/s]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 1/1005 [00:04<1:18:42,  4.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 2/1005 [00:09<1:17:24,  4.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 3/1005 [00:16<1:33:22,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 4/1005 [00:20<1:26:33,  5.19s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 5/1005 [00:27<1:34:57,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 6/1005 [00:31<1:28:17,  5.30s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 7/1005 [00:38<1:34:58,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 8/1005 [00:42<1:28:35,  5.33s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 9/1005 [00:49<1:37:02,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 10/1005 [00:54<1:30:09,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 11/1005 [01:00<1:35:39,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 12/1005 [01:05<1:31:17,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 13/1005 [01:12<1:36:53,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 14/1005 [01:17<1:32:05,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 15/1005 [01:23<1:37:15,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 16/1005 [01:28<1:30:47,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 17/1005 [01:35<1:35:55,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 18/1005 [01:39<1:29:17,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 19/1005 [01:46<1:35:06,  5.79s/it]

Error: Unable to fetch details from PubMed

  2%|▏         | 20/1005 [01:51<1:34:08,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 21/1005 [01:56<1:28:28,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 22/1005 [02:03<1:34:00,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 23/1005 [02:08<1:30:29,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 24/1005 [02:14<1:36:34,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 25/1005 [02:20<1:33:53,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 26/1005 [02:26<1:38:11,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 27/1005 [02:31<1:31:06,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 28/1005 [02:38<1:36:16,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 29/1005 [02:42<1:29:18,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 30/1005 [02:49<1:34:35,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 31/1005 [02:54<1:29:46,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 32/1005 [03:00<1:34:46,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 33/1005 [03:05<1:28:17,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 34/1005 [03:11<1:33:36,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 35/1005 [03:16<1:27:39,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▎         | 36/1005 [03:23<1:33:45,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▎         | 37/1005 [03:27<1:27:27,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 38/1005 [03:34<1:32:52,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 39/1005 [03:38<1:27:43,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 40/1005 [03:45<1:33:04,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 41/1005 [03:49<1:26:56,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 42/1005 [03:56<1:32:11,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 43/1005 [04:01<1:26:24,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 44/1005 [04:07<1:31:28,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 45/1005 [04:12<1:25:45,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 46/1005 [04:18<1:31:30,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 47/1005 [04:23<1:26:03,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 48/1005 [04:29<1:32:11,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 49/1005 [04:34<1:26:10,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 50/1005 [04:41<1:32:13,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 51/1005 [04:45<1:26:38,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 52/1005 [04:52<1:31:52,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 53/1005 [04:57<1:28:57,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 54/1005 [05:04<1:37:30,  6.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 55/1005 [05:09<1:29:39,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 56/1005 [05:16<1:33:49,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 57/1005 [05:21<1:31:41,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 58/1005 [05:28<1:35:22,  6.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 59/1005 [05:32<1:28:04,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 60/1005 [05:39<1:32:36,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 61/1005 [05:44<1:31:03,  5.79s/it]

Error: Unable to fetch details from PubMed

  6%|▌         | 62/1005 [05:51<1:35:43,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 63/1005 [05:58<1:37:42,  6.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 64/1005 [06:02<1:29:42,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 65/1005 [06:09<1:33:22,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 66/1005 [06:13<1:27:29,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 67/1005 [06:20<1:31:50,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 68/1005 [06:24<1:25:23,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 69/1005 [06:31<1:30:29,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 70/1005 [06:36<1:24:38,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 71/1005 [06:42<1:30:18,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 72/1005 [06:47<1:24:18,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 73/1005 [06:54<1:31:55,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 74/1005 [06:58<1:25:28,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 75/1005 [07:05<1:30:44,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 76/1005 [07:10<1:24:56,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 77/1005 [07:17<1:30:54,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 78/1005 [07:22<1:30:30,  5.86s/it]

Error: Unable to fetch details from PubMed

  8%|▊         | 79/1005 [07:27<1:24:39,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 80/1005 [07:34<1:29:56,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 81/1005 [07:38<1:24:03,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 82/1005 [07:45<1:30:14,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 83/1005 [07:50<1:25:07,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 84/1005 [07:56<1:29:39,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 85/1005 [08:01<1:23:32,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▊         | 86/1005 [08:07<1:28:33,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▊         | 87/1005 [08:12<1:22:49,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 88/1005 [08:19<1:28:10,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 89/1005 [08:23<1:22:22,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 90/1005 [08:30<1:27:58,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 91/1005 [08:34<1:22:36,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 92/1005 [08:41<1:27:48,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 93/1005 [08:45<1:22:02,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 94/1005 [08:52<1:27:06,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 95/1005 [08:57<1:21:27,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 96/1005 [09:03<1:26:47,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 97/1005 [09:08<1:21:39,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 98/1005 [09:14<1:27:02,  5.76s/it]

Error: Unable to fetch details from PubMed

 10%|▉         | 99/1005 [09:20<1:26:06,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 100/1005 [09:24<1:20:40,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 101/1005 [09:31<1:25:55,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 102/1005 [09:35<1:20:34,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 103/1005 [09:42<1:26:48,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 104/1005 [09:47<1:21:54,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 105/1005 [09:54<1:27:17,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 106/1005 [09:58<1:21:20,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 107/1005 [10:05<1:26:14,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 108/1005 [10:09<1:21:08,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 109/1005 [10:16<1:26:12,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 110/1005 [10:21<1:20:57,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 111/1005 [10:27<1:25:57,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 112/1005 [10:32<1:20:13,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 113/1005 [10:38<1:25:33,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█▏        | 114/1005 [10:43<1:20:39,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█▏        | 115/1005 [10:50<1:26:19,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 116/1005 [10:54<1:20:34,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 117/1005 [11:01<1:25:33,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 118/1005 [11:05<1:19:52,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 119/1005 [11:12<1:24:54,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 120/1005 [11:17<1:20:09,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 121/1005 [11:23<1:24:59,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 122/1005 [11:28<1:19:23,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 123/1005 [11:34<1:24:35,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 124/1005 [11:39<1:19:52,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 125/1005 [11:45<1:24:40,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 126/1005 [11:52<1:28:38,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 127/1005 [11:59<1:30:47,  6.20s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 128/1005 [12:03<1:23:43,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 129/1005 [12:10<1:27:37,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 130/1005 [12:15<1:21:29,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 131/1005 [12:21<1:25:37,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 132/1005 [12:26<1:20:22,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 133/1005 [12:32<1:25:17,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 134/1005 [12:37<1:19:28,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 135/1005 [12:44<1:24:04,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 136/1005 [12:48<1:18:27,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 137/1005 [12:55<1:23:28,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 138/1005 [12:59<1:18:05,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 139/1005 [13:06<1:23:03,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 140/1005 [13:10<1:17:38,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 141/1005 [13:17<1:22:35,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 142/1005 [13:21<1:17:21,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 143/1005 [13:28<1:22:49,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 144/1005 [13:33<1:17:20,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 145/1005 [13:39<1:22:16,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 146/1005 [13:44<1:17:07,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 147/1005 [13:50<1:21:58,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 148/1005 [13:55<1:16:35,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 149/1005 [14:01<1:21:28,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 150/1005 [14:06<1:16:29,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 151/1005 [14:12<1:21:39,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 152/1005 [14:17<1:17:18,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 153/1005 [14:24<1:22:05,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 154/1005 [14:28<1:16:42,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 155/1005 [14:35<1:21:51,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 156/1005 [14:40<1:16:37,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 157/1005 [14:46<1:22:27,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 158/1005 [14:51<1:17:03,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 159/1005 [14:58<1:23:02,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 160/1005 [15:01<1:12:49,  5.17s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 161/1005 [15:08<1:19:12,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 162/1005 [15:13<1:14:30,  5.30s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 163/1005 [15:19<1:19:38,  5.68s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▋        | 164/1005 [15:24<1:15:01,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▋        | 165/1005 [15:30<1:20:37,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 166/1005 [15:35<1:15:18,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 167/1005 [15:42<1:20:11,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 168/1005 [15:46<1:15:43,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 169/1005 [15:54<1:25:48,  6.16s/it]

Error: Unable to fetch details from PubMed

 17%|█▋        | 170/1005 [15:59<1:20:07,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 171/1005 [16:06<1:25:11,  6.13s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 172/1005 [16:11<1:19:01,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 173/1005 [16:17<1:22:37,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 174/1005 [16:22<1:16:40,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 175/1005 [16:28<1:21:04,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 176/1005 [16:33<1:16:26,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 177/1005 [16:40<1:20:27,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 178/1005 [16:44<1:15:39,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 179/1005 [16:51<1:20:02,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 180/1005 [16:55<1:14:43,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 181/1005 [17:02<1:19:16,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 182/1005 [17:08<1:18:48,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 183/1005 [17:14<1:22:01,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 184/1005 [17:19<1:15:57,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 185/1005 [17:25<1:20:16,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 186/1005 [17:30<1:14:54,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 187/1005 [17:36<1:19:02,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 188/1005 [17:41<1:13:32,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 189/1005 [17:48<1:18:19,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 190/1005 [17:52<1:13:12,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 191/1005 [17:59<1:18:20,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 192/1005 [18:03<1:13:50,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 193/1005 [18:10<1:18:11,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 194/1005 [18:15<1:12:57,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 195/1005 [18:21<1:17:59,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 196/1005 [18:26<1:13:08,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 197/1005 [18:32<1:18:05,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 198/1005 [18:37<1:13:10,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 199/1005 [18:44<1:18:28,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 200/1005 [18:48<1:13:23,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 201/1005 [18:55<1:17:59,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 202/1005 [19:00<1:13:01,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 203/1005 [19:06<1:17:42,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 204/1005 [19:11<1:12:33,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 205/1005 [19:18<1:17:19,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 206/1005 [19:22<1:12:53,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 207/1005 [19:29<1:17:36,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 208/1005 [19:33<1:12:30,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 209/1005 [19:40<1:16:37,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 210/1005 [19:45<1:11:42,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 211/1005 [19:51<1:16:39,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 212/1005 [19:56<1:11:44,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 213/1005 [20:02<1:16:27,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 214/1005 [20:07<1:11:23,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 215/1005 [20:14<1:16:00,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 216/1005 [20:18<1:11:03,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 217/1005 [20:25<1:15:44,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 218/1005 [20:29<1:10:43,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 219/1005 [20:36<1:15:44,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 220/1005 [20:41<1:10:45,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 221/1005 [20:47<1:15:46,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 222/1005 [20:52<1:10:51,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 223/1005 [20:58<1:15:37,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 224/1005 [21:03<1:10:53,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 225/1005 [21:10<1:15:18,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 226/1005 [21:14<1:10:11,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 227/1005 [21:21<1:14:31,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 228/1005 [21:25<1:09:38,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 229/1005 [21:32<1:14:11,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 230/1005 [21:37<1:11:17,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 231/1005 [21:42<1:11:37,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 232/1005 [21:49<1:15:34,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 233/1005 [21:54<1:10:20,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 234/1005 [22:00<1:14:28,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 235/1005 [22:05<1:09:30,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 236/1005 [22:11<1:13:46,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▎       | 237/1005 [22:16<1:08:54,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▎       | 238/1005 [22:22<1:13:34,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 239/1005 [22:27<1:08:43,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 240/1005 [22:33<1:13:12,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 241/1005 [22:38<1:08:26,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 242/1005 [22:45<1:12:58,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 243/1005 [22:49<1:08:13,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 244/1005 [22:57<1:17:39,  6.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 245/1005 [23:02<1:11:33,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 246/1005 [23:06<1:08:20,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 247/1005 [23:13<1:13:39,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 248/1005 [23:18<1:08:42,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 249/1005 [23:25<1:14:18,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 250/1005 [23:30<1:10:44,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 251/1005 [23:37<1:15:52,  6.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 252/1005 [23:41<1:10:00,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 253/1005 [23:48<1:13:45,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 254/1005 [23:53<1:10:33,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 255/1005 [24:00<1:16:23,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 256/1005 [24:05<1:13:05,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 257/1005 [24:12<1:15:51,  6.08s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 258/1005 [24:16<1:10:01,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 259/1005 [24:23<1:13:27,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 260/1005 [24:28<1:08:08,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 261/1005 [24:34<1:11:54,  5.80s/it]

Error: Unable to fetch details from PubMed

 26%|██▌       | 262/1005 [24:40<1:12:43,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 263/1005 [24:47<1:15:29,  6.10s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 264/1005 [24:51<1:10:13,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 265/1005 [24:58<1:13:56,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 266/1005 [25:03<1:08:33,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 267/1005 [25:09<1:12:30,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 268/1005 [25:14<1:07:26,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 269/1005 [25:21<1:12:54,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 270/1005 [25:26<1:07:55,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 271/1005 [25:32<1:12:16,  5.91s/it]

Error: Unable to fetch details from PubMed

 27%|██▋       | 272/1005 [25:38<1:12:03,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 273/1005 [25:43<1:07:02,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 274/1005 [25:49<1:11:10,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 275/1005 [25:54<1:07:08,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 276/1005 [26:03<1:18:06,  6.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 277/1005 [26:07<1:11:38,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 278/1005 [26:14<1:14:22,  6.14s/it]

Error: Unable to fetch details from PubMed

 28%|██▊       | 279/1005 [26:21<1:16:32,  6.33s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 280/1005 [26:29<1:22:35,  6.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 281/1005 [26:34<1:15:25,  6.25s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 282/1005 [26:39<1:12:29,  6.02s/it]

Error: Unable to fetch details from PubMed

 28%|██▊       | 283/1005 [26:45<1:12:47,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 284/1005 [26:53<1:17:38,  6.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 285/1005 [26:58<1:11:54,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 286/1005 [27:04<1:13:44,  6.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▊       | 287/1005 [27:10<1:12:00,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▊       | 288/1005 [27:17<1:14:32,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 289/1005 [27:22<1:09:48,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 290/1005 [27:29<1:14:59,  6.29s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 291/1005 [27:34<1:10:09,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 292/1005 [27:42<1:16:55,  6.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 293/1005 [27:47<1:11:50,  6.05s/it]

Error: Unable to fetch details from PubMed

 29%|██▉       | 294/1005 [27:53<1:10:37,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 295/1005 [27:59<1:12:36,  6.14s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 296/1005 [28:04<1:08:38,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 297/1005 [28:10<1:07:05,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 298/1005 [28:16<1:10:01,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 299/1005 [28:21<1:05:02,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 300/1005 [28:28<1:09:51,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 301/1005 [28:33<1:08:59,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 302/1005 [28:40<1:11:23,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 303/1005 [28:45<1:06:12,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 304/1005 [28:51<1:10:28,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 305/1005 [28:56<1:05:25,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 306/1005 [29:03<1:09:33,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 307/1005 [29:07<1:04:27,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 308/1005 [29:14<1:08:12,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 309/1005 [29:19<1:04:28,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 310/1005 [29:24<1:04:29,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 311/1005 [29:31<1:07:51,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 312/1005 [29:36<1:03:51,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 313/1005 [29:42<1:07:01,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 314/1005 [29:49<1:10:51,  6.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███▏      | 315/1005 [29:55<1:11:05,  6.18s/it]

Error: Unable to fetch details from PubMed

 31%|███▏      | 316/1005 [30:00<1:06:49,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 317/1005 [30:09<1:15:46,  6.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 318/1005 [30:14<1:10:54,  6.19s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 319/1005 [30:20<1:08:29,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 320/1005 [30:27<1:14:08,  6.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 321/1005 [30:33<1:13:09,  6.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 322/1005 [30:38<1:07:42,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 323/1005 [30:46<1:12:58,  6.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 324/1005 [30:51<1:06:45,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 325/1005 [30:58<1:12:46,  6.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 326/1005 [31:03<1:08:06,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 327/1005 [31:10<1:10:31,  6.24s/it]

Error: Unable to fetch details from PubMed

 33%|███▎      | 328/1005 [31:17<1:11:58,  6.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 329/1005 [31:24<1:14:03,  6.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 330/1005 [31:30<1:12:56,  6.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 331/1005 [31:36<1:10:02,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 332/1005 [31:43<1:14:14,  6.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 333/1005 [31:49<1:11:57,  6.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 334/1005 [31:56<1:14:03,  6.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 335/1005 [32:02<1:09:46,  6.25s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 336/1005 [32:09<1:12:06,  6.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 337/1005 [32:13<1:06:20,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 338/1005 [32:20<1:09:24,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 339/1005 [32:25<1:04:29,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 340/1005 [32:32<1:07:32,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 341/1005 [32:37<1:03:42,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 342/1005 [32:44<1:07:17,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 343/1005 [32:48<1:02:15,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 344/1005 [32:55<1:06:13,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 345/1005 [33:01<1:04:59,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 346/1005 [33:08<1:10:25,  6.41s/it]

Error: Unable to fetch details from PubMed

 35%|███▍      | 347/1005 [33:13<1:04:20,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 348/1005 [33:20<1:06:33,  6.08s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 349/1005 [33:24<1:01:28,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 350/1005 [33:31<1:04:38,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 351/1005 [33:35<1:00:13,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 352/1005 [33:42<1:03:30,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 353/1005 [33:47<59:30,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 354/1005 [33:53<1:03:14,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 355/1005 [33:58<59:00,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 356/1005 [34:04<1:02:43,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 357/1005 [34:09<58:31,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 358/1005 [34:15<1:02:03,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 359/1005 [34:20<57:54,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 360/1005 [34:27<1:01:51,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 361/1005 [34:31<58:23,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 362/1005 [34:38<1:02:04,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 363/1005 [34:42<57:54,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 364/1005 [34:49<1:01:34,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▋      | 365/1005 [34:54<57:32,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▋      | 366/1005 [35:00<1:01:10,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 367/1005 [35:05<57:32,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 368/1005 [35:11<1:01:22,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 369/1005 [35:16<57:28,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 370/1005 [35:23<1:01:08,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 371/1005 [35:27<57:02,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 372/1005 [35:34<1:00:33,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 373/1005 [35:38<56:44,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 374/1005 [35:45<1:00:34,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 375/1005 [35:49<56:45,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 376/1005 [35:56<1:00:44,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 377/1005 [36:01<57:28,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 378/1005 [36:07<1:00:43,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 379/1005 [36:12<56:43,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 380/1005 [36:19<1:00:49,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 381/1005 [36:23<56:39,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 382/1005 [36:30<59:53,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 383/1005 [36:34<55:54,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 384/1005 [36:41<59:21,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 385/1005 [36:45<55:37,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 386/1005 [36:52<59:33,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 387/1005 [36:57<55:33,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 388/1005 [37:03<59:10,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 389/1005 [37:08<55:20,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 390/1005 [37:14<58:56,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 391/1005 [37:20<58:15,  5.69s/it]

Error: Unable to fetch details from PubMed

 39%|███▉      | 392/1005 [37:24<54:43,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 393/1005 [37:31<58:13,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 394/1005 [37:36<54:55,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 395/1005 [37:43<59:22,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 396/1005 [37:47<55:18,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 397/1005 [37:54<58:30,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 398/1005 [37:58<54:37,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 399/1005 [38:05<58:05,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 400/1005 [38:09<54:26,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 401/1005 [38:16<58:17,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 402/1005 [38:21<54:21,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 403/1005 [38:27<57:47,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 404/1005 [38:32<54:00,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 405/1005 [38:38<57:24,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 406/1005 [38:43<53:53,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 407/1005 [38:50<58:03,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 408/1005 [38:54<54:12,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 409/1005 [39:01<57:40,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 410/1005 [39:05<53:56,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 411/1005 [39:12<57:06,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 412/1005 [39:22<1:09:06,  6.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 413/1005 [39:26<1:01:40,  6.25s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 414/1005 [39:31<56:30,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 415/1005 [39:37<58:45,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 416/1005 [39:42<54:20,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 417/1005 [39:49<57:29,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 418/1005 [39:53<53:36,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 419/1005 [40:00<56:36,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 420/1005 [40:04<53:02,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 421/1005 [40:11<56:15,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 422/1005 [40:15<52:54,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 423/1005 [40:22<56:39,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 424/1005 [40:27<52:47,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 425/1005 [40:33<56:00,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 426/1005 [40:38<52:17,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 427/1005 [40:44<55:30,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 428/1005 [40:49<51:50,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 429/1005 [40:56<55:04,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 430/1005 [41:00<51:36,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 431/1005 [41:07<54:55,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 432/1005 [41:11<51:42,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 433/1005 [41:18<54:46,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 434/1005 [41:22<51:18,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 435/1005 [41:29<54:23,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 436/1005 [41:34<51:27,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 437/1005 [41:40<54:55,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▎     | 438/1005 [41:45<51:12,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▎     | 439/1005 [41:52<55:05,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 440/1005 [41:56<51:12,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 441/1005 [42:03<54:28,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 442/1005 [42:08<51:21,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 443/1005 [42:14<54:26,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 444/1005 [42:19<50:54,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 445/1005 [42:25<53:52,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 446/1005 [42:30<50:19,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 447/1005 [42:36<53:21,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 448/1005 [42:41<50:00,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 449/1005 [42:47<53:03,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 450/1005 [42:52<49:34,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 451/1005 [42:59<52:55,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 452/1005 [43:03<49:36,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 453/1005 [43:10<52:43,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 454/1005 [43:14<49:13,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 455/1005 [43:21<52:20,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 456/1005 [43:25<48:55,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 457/1005 [43:32<52:07,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 458/1005 [43:36<48:47,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 459/1005 [43:43<52:04,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 460/1005 [43:47<48:40,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 461/1005 [43:54<51:56,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 462/1005 [43:59<49:06,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 463/1005 [44:05<52:09,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 464/1005 [44:10<48:49,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 465/1005 [44:16<51:45,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 466/1005 [44:21<48:23,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 467/1005 [44:27<51:24,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 468/1005 [44:32<48:07,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 469/1005 [44:39<51:16,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 470/1005 [44:43<47:58,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 471/1005 [44:50<51:09,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 472/1005 [44:54<48:00,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 473/1005 [45:01<51:02,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 474/1005 [45:05<47:50,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 475/1005 [45:12<50:57,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 476/1005 [45:17<49:31,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 477/1005 [45:24<51:51,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 478/1005 [45:28<48:06,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 479/1005 [45:35<50:58,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 480/1005 [45:40<47:39,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 481/1005 [45:46<50:23,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 482/1005 [45:51<47:03,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 483/1005 [45:57<49:53,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 484/1005 [46:02<46:33,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 485/1005 [46:08<49:37,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 486/1005 [46:13<46:34,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 487/1005 [46:19<49:33,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▊     | 488/1005 [46:24<46:25,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▊     | 489/1005 [46:30<49:19,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 490/1005 [46:35<46:13,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 491/1005 [46:42<49:04,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 492/1005 [46:46<46:00,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 493/1005 [46:53<48:54,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 494/1005 [46:57<45:54,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 495/1005 [47:04<48:43,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 496/1005 [47:08<45:47,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 497/1005 [47:15<48:37,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 498/1005 [47:20<45:26,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 499/1005 [47:26<48:20,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 500/1005 [47:31<45:16,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 501/1005 [47:37<48:01,  5.72s/it]

Error: Unable to fetch details from PubMed

 50%|████▉     | 502/1005 [47:43<47:57,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 503/1005 [47:50<50:26,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 504/1005 [47:54<46:38,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 505/1005 [48:01<49:09,  5.90s/it]

['LINC01287', 'PVALB', 'IGLL5', 'JCHAIN', 'TLR7']
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 506/1005 [48:06<46:12,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 507/1005 [48:12<48:57,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 508/1005 [48:17<46:42,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 509/1005 [48:24<49:52,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 510/1005 [48:29<46:27,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 511/1005 [48:36<49:19,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 512/1005 [48:40<45:52,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 513/1005 [48:47<48:05,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 514/1005 [48:52<45:29,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 515/1005 [48:58<48:07,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████▏    | 516/1005 [49:03<44:59,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████▏    | 517/1005 [49:10<47:42,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 518/1005 [49:14<44:16,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 519/1005 [49:20<44:24,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 520/1005 [49:27<47:27,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 521/1005 [49:31<44:22,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 522/1005 [49:38<47:01,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 523/1005 [49:42<43:45,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 524/1005 [49:49<46:53,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 525/1005 [49:54<43:59,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 526/1005 [50:00<46:32,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 527/1005 [50:05<43:28,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 528/1005 [50:12<46:10,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 529/1005 [50:16<43:30,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 530/1005 [50:23<46:05,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 531/1005 [50:28<42:59,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 532/1005 [50:34<45:55,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 533/1005 [50:39<43:17,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 534/1005 [50:46<45:44,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 535/1005 [50:50<42:41,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 536/1005 [50:57<45:35,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 537/1005 [51:02<42:43,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 538/1005 [51:08<45:35,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 539/1005 [51:13<42:50,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 540/1005 [51:20<45:15,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 541/1005 [51:24<42:24,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 542/1005 [51:31<44:45,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 543/1005 [51:35<41:46,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 544/1005 [51:42<44:20,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 545/1005 [51:46<41:23,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 546/1005 [51:53<43:59,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 547/1005 [51:58<41:07,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 548/1005 [52:04<43:50,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 549/1005 [52:09<41:05,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 550/1005 [52:15<43:37,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 551/1005 [52:20<40:43,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 552/1005 [52:26<43:13,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 553/1005 [52:31<40:25,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 554/1005 [52:38<43:13,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 555/1005 [52:42<40:26,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 556/1005 [52:49<42:59,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 557/1005 [52:53<40:19,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 558/1005 [53:00<42:52,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 559/1005 [53:04<40:01,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 560/1005 [53:11<43:07,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 561/1005 [53:16<40:15,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 562/1005 [53:22<42:37,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 563/1005 [53:27<39:58,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 564/1005 [53:33<42:20,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 565/1005 [53:38<39:37,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▋    | 566/1005 [53:45<41:59,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▋    | 567/1005 [53:49<39:17,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 568/1005 [53:56<41:41,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 569/1005 [54:00<38:57,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 570/1005 [54:07<41:31,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 571/1005 [54:11<38:48,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 572/1005 [54:18<41:13,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 573/1005 [54:22<38:32,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 574/1005 [54:29<41:09,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 575/1005 [54:33<38:28,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 576/1005 [54:40<40:56,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 577/1005 [54:45<38:15,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 578/1005 [54:51<40:41,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 579/1005 [54:56<38:01,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 580/1005 [55:02<40:31,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 581/1005 [55:07<37:56,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 582/1005 [55:13<40:21,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 583/1005 [55:18<37:48,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 584/1005 [55:24<40:23,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 585/1005 [55:29<37:42,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 586/1005 [55:36<40:05,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 587/1005 [55:40<37:29,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▊    | 588/1005 [55:47<39:54,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch data from PubMed

 59%|█████▊    | 589/1005 [56:11<1:18:50, 11.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▊    | 590/1005 [56:18<1:08:43,  9.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 591/1005 [56:22<57:22,  8.32s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 592/1005 [56:29<53:35,  7.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 593/1005 [56:33<46:43,  6.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 594/1005 [56:40<46:07,  6.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 595/1005 [56:44<41:29,  6.07s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 596/1005 [56:51<42:25,  6.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 597/1005 [56:56<39:45,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 598/1005 [57:03<42:00,  6.19s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 599/1005 [57:08<38:36,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 600/1005 [57:14<40:11,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 601/1005 [57:19<37:10,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 602/1005 [57:25<39:08,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 603/1005 [57:30<36:22,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 604/1005 [57:36<38:34,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 605/1005 [57:41<35:56,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 606/1005 [57:47<38:11,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 607/1005 [57:52<35:53,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 608/1005 [57:58<38:02,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 609/1005 [58:03<35:30,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 610/1005 [58:10<37:44,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 611/1005 [58:15<37:09,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 612/1005 [58:22<39:42,  6.06s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 613/1005 [58:27<36:32,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 614/1005 [58:33<38:17,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 615/1005 [58:38<35:31,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 616/1005 [58:44<37:35,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 617/1005 [58:49<35:14,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 618/1005 [58:55<37:17,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 619/1005 [59:00<34:47,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 620/1005 [59:07<37:06,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 621/1005 [59:11<34:34,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 622/1005 [59:18<36:44,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 623/1005 [59:22<34:20,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 624/1005 [59:29<36:25,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 625/1005 [59:33<34:09,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 626/1005 [59:40<36:18,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 627/1005 [59:44<33:53,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 628/1005 [59:51<36:06,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 629/1005 [59:56<34:35,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 630/1005 [1:00:03<36:53,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 631/1005 [1:00:07<34:30,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 632/1005 [1:00:14<36:17,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 633/1005 [1:00:19<34:00,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 634/1005 [1:00:25<35:55,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 635/1005 [1:00:30<34:41,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 636/1005 [1:00:37<36:19,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 637/1005 [1:00:46<42:20,  6.90s/it]

Error: Unable to fetch details from PubMed

 63%|██████▎   | 638/1005 [1:00:55<46:07,  7.54s/it]

Error: Unable to fetch details from PubMed

 64%|██████▎   | 640/1005 [1:01:14<50:39,  8.33s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 642/1005 [1:01:40<1:04:26, 10.65s/it]

Error: Unable to fetch details from PubMed

 64%|██████▍   | 643/1005 [1:01:50<1:03:11, 10.47s/it]

Error: Unable to fetch details from PubMed

 64%|██████▍   | 646/1005 [1:02:21<1:01:24, 10.26s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▍   | 649/1005 [1:02:51<59:59, 10.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▍   | 650/1005 [1:03:01<1:00:07, 10.16s/it]

Error: Unable to fetch details from PubMed

 65%|██████▍   | 651/1005 [1:03:11<58:57,  9.99s/it]

Error: Unable to fetch details from PubMed

 65%|██████▍   | 653/1005 [1:03:30<57:42,  9.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▌   | 654/1005 [1:03:41<59:46, 10.22s/it]

Error: Unable to fetch details from PubMed

 65%|██████▌   | 655/1005 [1:03:50<56:41,  9.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▌   | 657/1005 [1:04:18<1:11:19, 12.30s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 659/1005 [1:04:41<1:09:51, 12.11s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 660/1005 [1:04:51<1:05:36, 11.41s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 661/1005 [1:05:05<1:09:11, 12.07s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 662/1005 [1:05:17<1:10:01, 12.25s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▌   | 663/1005 [1:05:27<1:05:14, 11.45s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 664/1005 [1:05:33<55:13,  9.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▋   | 666/1005 [1:05:52<53:25,  9.46s/it]

Error: Unable to fetch details from PubMed

 66%|██████▋   | 667/1005 [1:06:06<1:00:05, 10.67s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 670/1005 [1:06:36<59:18, 10.62s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 672/1005 [1:06:58<59:39, 10.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 673/1005 [1:07:06<54:53,  9.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 674/1005 [1:07:17<56:35, 10.26s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 676/1005 [1:07:34<51:25,  9.38s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 677/1005 [1:07:46<55:28, 10.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 678/1005 [1:07:52<49:24,  9.07s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 680/1005 [1:08:13<53:13,  9.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 682/1005 [1:08:28<45:07,  8.38s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 683/1005 [1:08:34<41:53,  7.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 684/1005 [1:08:39<37:08,  6.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 685/1005 [1:08:45<36:09,  6.78s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 686/1005 [1:09:00<47:52,  9.00s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 687/1005 [1:09:11<51:47,  9.77s/it]

Error: Unable to fetch details from PubMed

 69%|██████▊   | 689/1005 [1:09:32<54:28, 10.34s/it]

Error: Unable to fetch details from PubMed

 69%|██████▊   | 690/1005 [1:09:37<45:39,  8.70s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 691/1005 [1:09:50<52:59, 10.13s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 692/1005 [1:09:55<44:44,  8.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▉   | 693/1005 [1:10:03<43:57,  8.45s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 694/1005 [1:10:09<40:19,  7.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▉   | 696/1005 [1:10:31<48:13,  9.37s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 697/1005 [1:10:40<47:15,  9.21s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 698/1005 [1:10:46<42:11,  8.25s/it]

Error: Unable to fetch details from PubMed

 70%|██████▉   | 699/1005 [1:10:53<40:39,  7.97s/it]

Error: Unable to fetch details from PubMed

 70%|██████▉   | 700/1005 [1:11:04<45:25,  8.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 701/1005 [1:11:15<47:39,  9.41s/it]

Error: Unable to fetch details from PubMed

 70%|██████▉   | 702/1005 [1:11:20<40:43,  8.06s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 703/1005 [1:11:27<38:45,  7.70s/it]

Error: Unable to fetch details from PubMed

 70%|███████   | 704/1005 [1:11:37<43:14,  8.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|███████   | 706/1005 [1:11:51<37:19,  7.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|███████   | 707/1005 [1:11:58<36:26,  7.34s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|███████   | 708/1005 [1:12:08<39:41,  8.02s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 709/1005 [1:12:17<40:45,  8.26s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 710/1005 [1:12:26<41:54,  8.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 711/1005 [1:12:33<40:01,  8.17s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 712/1005 [1:12:40<37:58,  7.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 713/1005 [1:12:49<39:50,  8.19s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 714/1005 [1:12:57<38:49,  8.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 716/1005 [1:13:17<45:03,  9.36s/it]

Error: Unable to fetch details from PubMed

 71%|███████▏  | 718/1005 [1:13:37<45:26,  9.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 72%|███████▏  | 721/1005 [1:14:08<47:58, 10.14s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 72%|███████▏  | 722/1005 [1:14:13<40:22,  8.56s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 723/1005 [1:14:23<42:54,  9.13s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 725/1005 [1:14:41<40:49,  8.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 72%|███████▏  | 726/1005 [1:14:52<44:26,  9.56s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 727/1005 [1:15:00<42:37,  9.20s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 728/1005 [1:15:06<37:04,  8.03s/it]

Error: Unable to fetch details from PubMed

 73%|███████▎  | 729/1005 [1:15:13<35:32,  7.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 730/1005 [1:15:25<41:39,  9.09s/it]

Error: Unable to fetch details from PubMed

 73%|███████▎  | 732/1005 [1:15:47<45:42, 10.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 733/1005 [1:15:52<39:33,  8.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 734/1005 [1:15:59<36:32,  8.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 735/1005 [1:16:06<34:31,  7.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 736/1005 [1:16:15<37:05,  8.27s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 737/1005 [1:16:20<32:50,  7.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 738/1005 [1:16:27<32:02,  7.20s/it]

Error: Unable to fetch details from PubMed

 74%|███████▎  | 739/1005 [1:16:33<30:08,  6.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▎  | 740/1005 [1:16:42<32:54,  7.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▎  | 741/1005 [1:16:47<29:32,  6.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▍  | 742/1005 [1:16:55<30:16,  6.91s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 744/1005 [1:17:11<32:36,  7.50s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 745/1005 [1:17:19<32:34,  7.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▍  | 746/1005 [1:17:26<31:59,  7.41s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 747/1005 [1:17:34<33:15,  7.73s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 748/1005 [1:17:39<29:27,  6.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▍  | 749/1005 [1:17:48<31:49,  7.46s/it]

Error: Unable to fetch details from PubMed

 75%|███████▍  | 750/1005 [1:17:58<34:27,  8.11s/it]

Error: Unable to fetch details from PubMed

 75%|███████▍  | 751/1005 [1:18:02<29:46,  7.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▍  | 753/1005 [1:18:25<38:18,  9.12s/it]

Error: Unable to fetch details from PubMed

 75%|███████▌  | 754/1005 [1:18:36<40:23,  9.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▌  | 755/1005 [1:18:42<35:51,  8.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▌  | 756/1005 [1:18:54<39:22,  9.49s/it]

Error: Unable to fetch details from PubMed

 75%|███████▌  | 757/1005 [1:19:03<39:23,  9.53s/it]

Error: Unable to fetch details from PubMed

 75%|███████▌  | 758/1005 [1:19:09<34:17,  8.33s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 759/1005 [1:19:15<32:04,  7.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 760/1005 [1:19:20<28:01,  6.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 761/1005 [1:19:26<27:29,  6.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 762/1005 [1:19:31<24:39,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 763/1005 [1:19:38<25:06,  6.23s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 764/1005 [1:19:42<23:04,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 765/1005 [1:19:49<23:55,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 766/1005 [1:19:53<22:04,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▋  | 767/1005 [1:20:00<23:09,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▋  | 768/1005 [1:20:04<21:29,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 769/1005 [1:20:11<22:42,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 770/1005 [1:20:15<21:08,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 771/1005 [1:20:22<22:24,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 772/1005 [1:20:26<20:57,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 773/1005 [1:20:33<22:14,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 774/1005 [1:20:38<20:42,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 775/1005 [1:20:44<21:56,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 776/1005 [1:20:49<20:29,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 777/1005 [1:20:55<21:44,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 778/1005 [1:21:00<20:22,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 779/1005 [1:21:06<21:35,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 780/1005 [1:21:11<20:09,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 781/1005 [1:21:17<21:20,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 782/1005 [1:21:22<19:57,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 783/1005 [1:21:28<21:10,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 784/1005 [1:21:33<19:45,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 785/1005 [1:21:40<20:57,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 786/1005 [1:21:44<19:32,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 787/1005 [1:21:51<20:47,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 788/1005 [1:21:55<19:22,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 789/1005 [1:22:02<20:35,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 790/1005 [1:22:06<19:11,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 791/1005 [1:22:13<20:35,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 792/1005 [1:22:18<19:12,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 793/1005 [1:22:23<19:15,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 794/1005 [1:22:30<20:19,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 795/1005 [1:22:35<20:00,  5.71s/it]

Error: Unable to fetch details from PubMed

 79%|███████▉  | 796/1005 [1:22:40<18:53,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 797/1005 [1:22:46<19:57,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 798/1005 [1:22:51<18:35,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 799/1005 [1:22:58<19:40,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 800/1005 [1:23:02<18:20,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 801/1005 [1:23:09<19:30,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 802/1005 [1:23:13<18:09,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 803/1005 [1:23:20<19:20,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 804/1005 [1:23:24<18:13,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 805/1005 [1:23:31<19:14,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 806/1005 [1:23:36<17:52,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 807/1005 [1:23:41<17:58,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 808/1005 [1:23:46<16:58,  5.17s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 809/1005 [1:23:52<18:15,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 810/1005 [1:23:57<17:07,  5.27s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 811/1005 [1:24:03<18:29,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 812/1005 [1:24:08<17:24,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 813/1005 [1:24:15<18:22,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 814/1005 [1:24:19<17:18,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 815/1005 [1:24:26<18:15,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 816/1005 [1:24:30<16:58,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 817/1005 [1:24:37<17:57,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 818/1005 [1:24:42<16:54,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 819/1005 [1:24:48<17:54,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 820/1005 [1:24:54<17:43,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 821/1005 [1:25:01<18:24,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 822/1005 [1:25:05<17:04,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 823/1005 [1:25:12<17:55,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 824/1005 [1:25:16<16:35,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 825/1005 [1:25:23<17:26,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 826/1005 [1:25:29<17:22,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 827/1005 [1:25:36<18:06,  6.10s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 828/1005 [1:25:40<16:40,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 829/1005 [1:25:47<17:21,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 830/1005 [1:25:51<16:04,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 831/1005 [1:25:58<16:53,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 832/1005 [1:26:02<15:38,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 833/1005 [1:26:09<16:31,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 834/1005 [1:26:13<15:21,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 835/1005 [1:26:21<17:09,  6.06s/it]

Error: Unable to fetch details from PubMed

 83%|████████▎ | 836/1005 [1:26:26<15:53,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 837/1005 [1:26:32<16:31,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 838/1005 [1:26:37<15:23,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 839/1005 [1:26:43<16:11,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▎ | 840/1005 [1:26:48<15:00,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▎ | 841/1005 [1:26:55<15:53,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 842/1005 [1:26:59<14:45,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 843/1005 [1:27:06<15:44,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 844/1005 [1:27:10<14:34,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 845/1005 [1:27:17<15:20,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 846/1005 [1:27:22<14:25,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 847/1005 [1:27:28<15:11,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 848/1005 [1:27:33<14:17,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 849/1005 [1:27:39<15:01,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 850/1005 [1:27:44<13:57,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 851/1005 [1:27:51<14:47,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 852/1005 [1:27:55<13:46,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 853/1005 [1:28:02<14:35,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 854/1005 [1:28:06<13:34,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 855/1005 [1:28:13<14:24,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 856/1005 [1:28:17<13:25,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 857/1005 [1:28:24<14:12,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 858/1005 [1:28:29<13:14,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 859/1005 [1:28:35<13:59,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 860/1005 [1:28:40<13:02,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 861/1005 [1:28:46<13:46,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 862/1005 [1:28:51<12:49,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 863/1005 [1:28:57<13:34,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 864/1005 [1:29:02<12:46,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 865/1005 [1:29:09<13:26,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 866/1005 [1:29:13<12:30,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 867/1005 [1:29:20<13:14,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 868/1005 [1:29:24<12:18,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 869/1005 [1:29:31<13:08,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 870/1005 [1:29:36<12:15,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 871/1005 [1:29:42<12:56,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 872/1005 [1:29:47<12:00,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 873/1005 [1:29:53<12:42,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 874/1005 [1:29:58<11:46,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 875/1005 [1:30:05<12:25,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 876/1005 [1:30:10<11:56,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 877/1005 [1:30:17<12:46,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 878/1005 [1:30:22<12:04,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 879/1005 [1:30:28<12:29,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 880/1005 [1:30:33<11:30,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 881/1005 [1:30:39<12:02,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 882/1005 [1:30:44<11:11,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 883/1005 [1:30:50<11:44,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 884/1005 [1:30:55<10:53,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 885/1005 [1:31:02<11:34,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 886/1005 [1:31:06<10:49,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 887/1005 [1:31:13<11:20,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 888/1005 [1:31:17<10:30,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 889/1005 [1:31:24<11:04,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▊ | 890/1005 [1:31:29<10:28,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▊ | 891/1005 [1:31:35<11:02,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 892/1005 [1:31:40<10:14,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 893/1005 [1:31:47<10:51,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 894/1005 [1:31:51<10:07,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 895/1005 [1:31:58<10:56,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 896/1005 [1:32:03<10:03,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 897/1005 [1:32:10<10:50,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 898/1005 [1:32:15<09:56,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 899/1005 [1:32:21<10:25,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 900/1005 [1:32:26<09:42,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 901/1005 [1:32:33<10:08,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 902/1005 [1:32:37<09:21,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 903/1005 [1:32:44<09:48,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 904/1005 [1:32:48<09:05,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 905/1005 [1:32:55<09:33,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 906/1005 [1:32:59<08:52,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 907/1005 [1:33:06<09:21,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 908/1005 [1:33:10<08:42,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 909/1005 [1:33:17<09:10,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 910/1005 [1:33:23<09:27,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 911/1005 [1:33:28<08:45,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 912/1005 [1:33:35<09:09,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 913/1005 [1:33:39<08:30,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 914/1005 [1:33:46<08:53,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 915/1005 [1:33:51<08:11,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 916/1005 [1:33:57<08:34,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 917/1005 [1:34:02<08:00,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████▏| 918/1005 [1:34:09<08:28,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████▏| 919/1005 [1:34:13<07:48,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 920/1005 [1:34:20<08:10,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 921/1005 [1:34:24<07:32,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 922/1005 [1:34:31<08:07,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 923/1005 [1:34:36<07:27,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 924/1005 [1:34:42<07:48,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 925/1005 [1:34:47<07:12,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 926/1005 [1:34:53<07:36,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 927/1005 [1:34:59<07:25,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 928/1005 [1:35:06<07:43,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 929/1005 [1:35:10<07:02,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 930/1005 [1:35:17<07:19,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 931/1005 [1:35:21<06:44,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 932/1005 [1:35:28<07:03,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 933/1005 [1:35:32<06:31,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 934/1005 [1:35:39<06:49,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 935/1005 [1:35:43<06:17,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 936/1005 [1:35:50<06:37,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 937/1005 [1:35:55<06:08,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 938/1005 [1:36:01<06:25,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 939/1005 [1:36:06<05:57,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 940/1005 [1:36:12<06:14,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 941/1005 [1:36:17<05:44,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 942/1005 [1:36:23<06:00,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 943/1005 [1:36:28<05:32,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 944/1005 [1:36:34<05:48,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 945/1005 [1:36:39<05:20,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 946/1005 [1:36:46<05:37,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 947/1005 [1:36:50<05:10,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 948/1005 [1:36:57<05:25,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 949/1005 [1:37:01<04:59,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 950/1005 [1:37:08<05:14,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 951/1005 [1:37:12<04:49,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 952/1005 [1:37:19<05:03,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 953/1005 [1:37:23<04:39,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 954/1005 [1:37:30<04:52,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 955/1005 [1:37:35<04:37,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 956/1005 [1:37:42<04:46,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 957/1005 [1:37:46<04:21,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 958/1005 [1:37:53<04:30,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 959/1005 [1:37:57<04:07,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 960/1005 [1:38:04<04:17,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 961/1005 [1:38:08<03:56,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 962/1005 [1:38:15<04:06,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 963/1005 [1:38:19<03:45,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 964/1005 [1:38:26<03:54,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 965/1005 [1:38:30<03:35,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 966/1005 [1:38:37<03:43,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 967/1005 [1:38:41<03:24,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▋| 968/1005 [1:38:48<03:31,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▋| 969/1005 [1:38:52<03:12,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 970/1005 [1:38:59<03:19,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 971/1005 [1:39:04<03:02,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 972/1005 [1:39:10<03:08,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 973/1005 [1:39:15<02:52,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 974/1005 [1:39:21<02:57,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 975/1005 [1:39:26<02:41,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 976/1005 [1:39:32<02:46,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 977/1005 [1:39:37<02:30,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 978/1005 [1:39:43<02:34,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 979/1005 [1:39:48<02:19,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 980/1005 [1:39:54<02:22,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 981/1005 [1:39:59<02:09,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 982/1005 [1:40:06<02:11,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 983/1005 [1:40:10<01:59,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 984/1005 [1:40:17<02:02,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 985/1005 [1:40:22<01:51,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 986/1005 [1:40:29<01:51,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 987/1005 [1:40:33<01:38,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 988/1005 [1:40:40<01:39,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 989/1005 [1:40:44<01:27,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 990/1005 [1:40:51<01:28,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 991/1005 [1:40:56<01:16,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 992/1005 [1:41:03<01:18,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 993/1005 [1:41:08<01:06,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 994/1005 [1:41:14<01:04,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 995/1005 [1:41:19<00:54,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 996/1005 [1:41:25<00:52,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 997/1005 [1:41:31<00:45,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 998/1005 [1:41:35<00:37,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 999/1005 [1:41:42<00:34,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1000/1005 [1:41:46<00:26,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1001/1005 [1:41:53<00:22,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1002/1005 [1:41:58<00:16,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1003/1005 [1:42:04<00:11,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1004/1005 [1:42:09<00:05,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|██████████| 1005/1005 [1:42:15<00:00,  6.11s/it]

In [13]:
results

           0             1          2  3    4
0        740  METHOTREXATE  LINC01287  0  0.0
1        740  METHOTREXATE      PVALB  0  0.0
2        740  METHOTREXATE      IGLL5  0  0.0
3        740  METHOTREXATE     JCHAIN  0  0.0
4        740  METHOTREXATE       TLR7  5  NaN
...      ...           ...        ... ..  ...
5020  820919    NVP-BHG712  LINC01287  0  0.0
5021  820919    NVP-BHG712      PVALB  0  0.0
5022  820919    NVP-BHG712     JCHAIN  0  0.0
5023  820919    NVP-BHG712      IGLL5  0  0.0
5024  820919    NVP-BHG712       TLR7  0  0.0

[5025 rows x 5 columns]

In [16]:
results = pd.DataFrame(results)[[0, 1, 2, 3]]
results.columns = ["NSC", "drug", "gene", "num"]
results

         NSC          drug       gene  num
0        740  METHOTREXATE  LINC01287    0
1        740  METHOTREXATE      PVALB    0
2        740  METHOTREXATE      IGLL5    0
3        740  METHOTREXATE     JCHAIN    0
4        740  METHOTREXATE       TLR7    5
...      ...           ...        ...  ...
5020  820919    NVP-BHG712  LINC01287    0
5021  820919    NVP-BHG712      PVALB    0
5022  820919    NVP-BHG712     JCHAIN    0
5023  820919    NVP-BHG712      IGLL5    0
5024  820919    NVP-BHG712       TLR7    0

[5025 rows x 4 columns]

In [17]:
results.to_csv("result_all_vall.csv", index=False)

In [18]:
attention = pd.read_csv("train_attention.csv.gz", index_col=0)
attention

/tmp/ipykernel_3534472/1825614993.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  attention = pd.read_csv("train_attention.csv.gz", index_col=0)

,740,752,755,757,762,1390,1895,3053,3061,3088,...,ZNF358,ZNF462,ZNF542P,ZNF655,ZNF667-AS1,ZNF703,ZNRD1,ZP3,ZSCAN18,ZYX
740,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001020,0.000985,0.001102,0.001062,0.001133,0.001139,0.000912,0.001096,0.001129,0.000951
752,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001736,0.001722,0.001797,0.001727,0.001756,0.001677,0.001829,0.001766,0.001792,0.001780
755,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001925,0.001897,0.001986,0.001875,0.001882,0.001760,0.002189,0.001905,0.001975,0.002033
757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001221,0.001207,0.001328,0.001256,0.001290,0.001267,0.001175,0.001300,0.001310,0.001208
762,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001963,0.002026,0.002052,0.001943,0.001956,0.001803,0.002234,0.001931,0.002021,0.002095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF703,0.000464,0.000490,0.000438,0.000451,0.000465,0.000452,0.000484,0.000528,0.000439,0.000540,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZNRD1,0.000323,0.000345,0.000319,0.000332,0.000328,0.000321,0.000335,0.000340,0.000311,0.000363,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZP3,0.000406,0.000439,0.000393,0.000404,0.000416,0.000398,0.000423,0.000455,0.000384,0.000478,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZSCAN18,0.000395,0.000425,0.000377,0.000404,0.000401,0.000385,0.000417,0.000448,0.000374,0.000458,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ZYX,0.000337,0.000375,0.000336,0.000340,0.000348,0.000332,0.000357,0.000363,0.000324,0.000387,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [19]:
att_dg = attention.iloc[:1005, 1005+60:]
conv = dict(pd.read_csv("nsc_dti.csv", index_col=0)[["NSC", "Drug Name"]].values)

In [20]:
len(np.unique(attention.values))

5080913

In [21]:
results = []
pmid_list = []
for drug in tqdm(att_dg.index):
    genes = list(att_dg.loc[drug].sort_values(ascending=False).head(5).index)
    if drug == 759263:
        print(genes)

    for gene in genes:

        d = conv[int(drug)]
        if d == "benzaldehyde (BEN)":
            d = "benzaldehyde"
        elif "Derivative" in d:
            d = d[:-11]

        if "ADA" == gene:
            gene = "adenosine deaminase"

        pmids = search_pubmed("{} AND {}".format(d, gene), max_results=300)
        pmid_list.append([drug, gene, pmids])
        if pmids != None:
            details = fetch_details(pmids)
            if details != None:
                details = details.decode("utf-8")
                res = pd.DataFrame(parse_pubmed_efetch(details))
                if len(res) > 0:
                    results.append(
                        [
                            drug,
                            conv[int(drug)],
                            gene,
                            len(pmids),
                            # len(
                            #     (
                            #         res[
                            #             res.journal.str.lower().isin(
                            #                 set(j_list["Title"].str.lower())
                            #             )
                            #         ]
                            #     )
                            # ),
                        ]
                    )
                else:
                    results.append([drug, conv[int(drug)], gene, len(pmids), 0])
            else:
                results.append([drug, conv[int(drug)], gene, len(pmids), 0])
        else:
            results.append([drug, conv[int(drug)], gene, 0, 0])

  0%|          | 0/1005 [00:00<?, ?it/s]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 1/1005 [00:04<1:17:26,  4.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 2/1005 [00:09<1:16:37,  4.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 3/1005 [00:15<1:33:00,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 4/1005 [00:20<1:26:49,  5.20s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  0%|          | 5/1005 [00:27<1:37:00,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 6/1005 [00:32<1:30:05,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 7/1005 [00:38<1:37:42,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 8/1005 [00:43<1:30:48,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 9/1005 [00:50<1:36:23,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 10/1005 [00:54<1:30:18,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|          | 11/1005 [01:01<1:36:21,  5.82s/it]

Error: Unable to fetch details from PubMed

  1%|          | 12/1005 [01:10<1:51:18,  6.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 13/1005 [01:14<1:40:06,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 14/1005 [01:21<1:42:17,  6.19s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  1%|▏         | 15/1005 [01:25<1:34:02,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 16/1005 [01:31<1:35:45,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 17/1005 [01:38<1:40:16,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 18/1005 [01:43<1:32:28,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 19/1005 [01:49<1:37:21,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 20/1005 [01:54<1:30:33,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 21/1005 [02:01<1:36:35,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 22/1005 [02:05<1:30:24,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 23/1005 [02:12<1:35:43,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 24/1005 [02:16<1:29:46,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  2%|▏         | 25/1005 [02:23<1:36:12,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 26/1005 [02:28<1:29:48,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 27/1005 [02:34<1:34:48,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 28/1005 [02:39<1:29:09,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 29/1005 [02:46<1:34:20,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 30/1005 [02:51<1:29:56,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 32/1005 [03:03<1:32:53,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 33/1005 [03:09<1:37:09,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 34/1005 [03:14<1:30:12,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  3%|▎         | 35/1005 [03:21<1:35:00,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▎         | 36/1005 [03:25<1:28:30,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▎         | 37/1005 [03:32<1:33:48,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 38/1005 [03:36<1:27:30,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 39/1005 [03:43<1:33:32,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 40/1005 [03:48<1:27:11,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 41/1005 [03:54<1:32:32,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 42/1005 [03:59<1:26:46,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 43/1005 [04:05<1:32:32,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 44/1005 [04:10<1:26:49,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  4%|▍         | 45/1005 [04:16<1:32:06,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 46/1005 [04:21<1:26:20,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 47/1005 [04:28<1:32:19,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 48/1005 [04:32<1:26:22,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 49/1005 [04:39<1:32:28,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▍         | 50/1005 [04:44<1:26:50,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 51/1005 [04:50<1:32:26,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 52/1005 [04:55<1:26:31,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 53/1005 [05:00<1:26:57,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 54/1005 [05:07<1:31:54,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  5%|▌         | 55/1005 [05:11<1:25:51,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 56/1005 [05:18<1:31:06,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 57/1005 [05:23<1:25:32,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 58/1005 [05:29<1:30:50,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 59/1005 [05:34<1:26:27,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 60/1005 [05:41<1:33:13,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 61/1005 [05:46<1:26:55,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▌         | 62/1005 [05:52<1:32:18,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 63/1005 [05:57<1:25:52,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 64/1005 [06:03<1:30:51,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  6%|▋         | 65/1005 [06:08<1:25:00,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 66/1005 [06:15<1:34:50,  6.06s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 67/1005 [06:20<1:28:16,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 68/1005 [06:27<1:32:44,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 69/1005 [06:31<1:25:59,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 70/1005 [06:39<1:35:59,  6.16s/it]

Error: Unable to fetch details from PubMed

  7%|▋         | 71/1005 [06:43<1:28:10,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 72/1005 [06:51<1:37:01,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 73/1005 [06:56<1:29:12,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 74/1005 [07:02<1:33:01,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  7%|▋         | 75/1005 [07:07<1:26:33,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 76/1005 [07:14<1:31:47,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 77/1005 [07:18<1:25:29,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 78/1005 [07:25<1:30:21,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 79/1005 [07:30<1:29:06,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 80/1005 [07:37<1:33:14,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 81/1005 [07:42<1:26:04,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 82/1005 [07:48<1:31:11,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 83/1005 [07:53<1:24:42,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 84/1005 [07:59<1:29:30,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  8%|▊         | 85/1005 [08:04<1:23:34,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▊         | 86/1005 [08:10<1:28:27,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▊         | 87/1005 [08:15<1:22:40,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 88/1005 [08:22<1:28:10,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 89/1005 [08:26<1:22:30,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 90/1005 [08:33<1:27:41,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 91/1005 [08:37<1:22:11,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 92/1005 [08:44<1:27:19,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 93/1005 [08:48<1:21:48,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 94/1005 [08:55<1:26:59,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

  9%|▉         | 95/1005 [08:59<1:21:37,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 96/1005 [09:06<1:26:44,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 97/1005 [09:11<1:21:29,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 98/1005 [09:17<1:26:47,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 99/1005 [09:23<1:25:55,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|▉         | 100/1005 [09:29<1:29:52,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 101/1005 [09:34<1:23:29,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 102/1005 [09:40<1:27:58,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 103/1005 [09:45<1:22:09,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 104/1005 [09:52<1:26:50,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 10%|█         | 105/1005 [09:56<1:21:05,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 106/1005 [10:03<1:26:16,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 107/1005 [10:07<1:21:11,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 108/1005 [10:14<1:26:50,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 109/1005 [10:19<1:21:01,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 110/1005 [10:25<1:26:50,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 111/1005 [10:30<1:20:54,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 112/1005 [10:36<1:26:18,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█         | 113/1005 [10:41<1:21:22,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█▏        | 114/1005 [10:48<1:26:07,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 11%|█▏        | 115/1005 [10:52<1:20:51,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 116/1005 [10:59<1:26:25,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 117/1005 [11:04<1:20:29,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 118/1005 [11:10<1:25:34,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 119/1005 [11:15<1:21:00,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 120/1005 [11:22<1:26:14,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 121/1005 [11:26<1:20:09,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 122/1005 [11:33<1:25:49,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 123/1005 [11:37<1:19:56,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 124/1005 [11:44<1:25:01,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 12%|█▏        | 125/1005 [11:49<1:19:24,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 126/1005 [11:55<1:24:06,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 127/1005 [12:00<1:18:33,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 128/1005 [12:06<1:23:39,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 129/1005 [12:11<1:19:03,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 130/1005 [12:17<1:24:06,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 131/1005 [12:22<1:18:52,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 132/1005 [12:29<1:25:46,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 133/1005 [12:34<1:19:37,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 134/1005 [12:41<1:26:24,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 13%|█▎        | 135/1005 [12:45<1:20:31,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 136/1005 [12:52<1:25:21,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 137/1005 [12:56<1:19:15,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▎        | 138/1005 [13:03<1:24:23,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 139/1005 [13:08<1:19:16,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 140/1005 [13:14<1:23:33,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 141/1005 [13:19<1:17:54,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 142/1005 [13:25<1:23:04,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 143/1005 [13:30<1:17:41,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 144/1005 [13:37<1:22:57,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 14%|█▍        | 145/1005 [13:41<1:17:18,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 146/1005 [13:48<1:22:50,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 147/1005 [13:53<1:18:20,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 148/1005 [13:59<1:24:07,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 149/1005 [14:04<1:18:57,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▍        | 150/1005 [14:11<1:23:47,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 151/1005 [14:15<1:17:46,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 152/1005 [14:22<1:22:10,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 153/1005 [14:27<1:18:02,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 154/1005 [14:33<1:23:03,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 15%|█▌        | 155/1005 [14:38<1:18:36,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 156/1005 [14:45<1:23:13,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 157/1005 [14:49<1:17:42,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 158/1005 [14:57<1:24:28,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 159/1005 [15:02<1:20:35,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 160/1005 [15:08<1:23:52,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 161/1005 [15:13<1:18:43,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 162/1005 [15:20<1:25:46,  6.10s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▌        | 163/1005 [15:25<1:20:55,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▋        | 164/1005 [15:32<1:24:33,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 16%|█▋        | 165/1005 [15:37<1:19:23,  5.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 166/1005 [15:43<1:22:56,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 167/1005 [15:48<1:16:52,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 168/1005 [15:53<1:17:37,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 169/1005 [16:00<1:21:46,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 170/1005 [16:05<1:16:07,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 171/1005 [16:11<1:20:38,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 172/1005 [16:16<1:15:13,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 173/1005 [16:22<1:19:47,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 174/1005 [16:27<1:14:54,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 17%|█▋        | 175/1005 [16:35<1:24:19,  6.10s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 176/1005 [16:39<1:17:44,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 177/1005 [16:46<1:21:19,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 178/1005 [16:50<1:16:01,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 179/1005 [16:57<1:20:22,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 180/1005 [17:01<1:14:42,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 181/1005 [17:08<1:19:11,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 182/1005 [17:12<1:13:51,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 183/1005 [17:19<1:18:29,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 184/1005 [17:23<1:13:19,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 18%|█▊        | 185/1005 [17:30<1:19:47,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 186/1005 [17:35<1:14:38,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 187/1005 [17:42<1:19:17,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▊        | 188/1005 [17:46<1:13:47,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 189/1005 [17:53<1:18:53,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 190/1005 [17:57<1:14:05,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 191/1005 [18:04<1:18:17,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 192/1005 [18:08<1:12:59,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 193/1005 [18:15<1:17:53,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 194/1005 [18:19<1:12:39,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 19%|█▉        | 195/1005 [18:26<1:17:19,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 196/1005 [18:31<1:12:13,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 197/1005 [18:37<1:16:55,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 198/1005 [18:42<1:11:53,  5.34s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 199/1005 [18:48<1:16:39,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|█▉        | 200/1005 [18:53<1:11:49,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 201/1005 [18:59<1:17:42,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 202/1005 [19:04<1:12:26,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 203/1005 [19:11<1:16:49,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 204/1005 [19:15<1:11:56,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 205/1005 [19:22<1:17:02,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 20%|██        | 206/1005 [19:26<1:11:55,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 207/1005 [19:33<1:16:46,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 208/1005 [19:37<1:11:41,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 209/1005 [19:44<1:16:31,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 210/1005 [19:49<1:12:19,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 211/1005 [19:55<1:16:46,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 212/1005 [20:00<1:11:47,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██        | 213/1005 [20:07<1:16:20,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 214/1005 [20:11<1:11:09,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 215/1005 [20:18<1:15:35,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 21%|██▏       | 216/1005 [20:22<1:10:41,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 217/1005 [20:29<1:15:16,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 218/1005 [20:33<1:10:23,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 219/1005 [20:40<1:15:09,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 220/1005 [20:44<1:10:18,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 221/1005 [20:51<1:14:50,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 222/1005 [20:55<1:10:04,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 223/1005 [21:02<1:14:53,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 224/1005 [21:07<1:10:03,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 225/1005 [21:13<1:15:01,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 22%|██▏       | 226/1005 [21:18<1:10:11,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 227/1005 [21:24<1:14:32,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 228/1005 [21:29<1:09:46,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 229/1005 [21:35<1:14:04,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 230/1005 [21:40<1:09:26,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 231/1005 [21:47<1:13:52,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 232/1005 [21:51<1:09:03,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 233/1005 [21:58<1:13:31,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 234/1005 [22:02<1:08:48,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 235/1005 [22:09<1:13:13,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 23%|██▎       | 236/1005 [22:13<1:09:15,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▎       | 237/1005 [22:20<1:13:26,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▎       | 238/1005 [22:24<1:08:54,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 239/1005 [22:31<1:13:22,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 240/1005 [22:35<1:08:29,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 241/1005 [22:42<1:13:09,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 242/1005 [22:47<1:08:37,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 243/1005 [22:53<1:12:46,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 244/1005 [22:58<1:08:21,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 245/1005 [23:04<1:12:34,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 24%|██▍       | 246/1005 [23:09<1:08:00,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 247/1005 [23:16<1:13:31,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 248/1005 [23:20<1:08:41,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 249/1005 [23:27<1:13:58,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 250/1005 [23:32<1:09:49,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▍       | 251/1005 [23:39<1:15:02,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 252/1005 [23:43<1:09:28,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 253/1005 [23:50<1:13:19,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 254/1005 [23:55<1:09:27,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 255/1005 [24:02<1:14:08,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 25%|██▌       | 256/1005 [24:07<1:10:10,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 257/1005 [24:13<1:13:53,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 258/1005 [24:18<1:08:36,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 259/1005 [24:25<1:13:22,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 260/1005 [24:29<1:08:24,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 261/1005 [24:36<1:12:11,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 262/1005 [24:40<1:07:45,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▌       | 263/1005 [24:47<1:11:32,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 264/1005 [24:51<1:06:49,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 265/1005 [24:58<1:11:00,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 26%|██▋       | 266/1005 [25:03<1:07:09,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 267/1005 [25:08<1:07:31,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 268/1005 [25:15<1:11:23,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 269/1005 [25:19<1:06:30,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 270/1005 [25:26<1:10:29,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 271/1005 [25:31<1:06:36,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 272/1005 [25:37<1:10:53,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 273/1005 [25:42<1:06:05,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 274/1005 [25:48<1:10:05,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 275/1005 [25:53<1:05:31,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 27%|██▋       | 276/1005 [26:00<1:09:59,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 277/1005 [26:04<1:05:35,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 278/1005 [26:11<1:09:44,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 279/1005 [26:15<1:05:13,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 280/1005 [26:22<1:09:17,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 281/1005 [26:26<1:04:49,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 282/1005 [26:33<1:08:53,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 283/1005 [26:37<1:04:34,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 284/1005 [26:44<1:08:43,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 285/1005 [26:48<1:04:21,  5.36s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 28%|██▊       | 286/1005 [26:55<1:08:44,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▊       | 287/1005 [27:00<1:04:29,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▊       | 288/1005 [27:06<1:08:41,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 289/1005 [27:11<1:04:17,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 290/1005 [27:17<1:08:20,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 291/1005 [27:22<1:03:56,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 292/1005 [27:28<1:08:05,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 293/1005 [27:33<1:04:05,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 294/1005 [27:39<1:07:55,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 295/1005 [27:44<1:03:37,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 29%|██▉       | 296/1005 [27:51<1:07:52,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 297/1005 [27:55<1:03:32,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 298/1005 [28:02<1:07:26,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 299/1005 [28:06<1:03:10,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 300/1005 [28:13<1:07:34,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|██▉       | 301/1005 [28:17<1:03:06,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 302/1005 [28:24<1:07:09,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 303/1005 [28:28<1:02:48,  5.37s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 304/1005 [28:35<1:07:38,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 305/1005 [28:40<1:03:16,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 30%|███       | 306/1005 [28:46<1:07:07,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 307/1005 [28:51<1:03:15,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 308/1005 [28:58<1:06:58,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 309/1005 [29:02<1:03:06,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 310/1005 [29:09<1:06:47,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 311/1005 [29:13<1:02:26,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 312/1005 [29:20<1:06:16,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 313/1005 [29:25<1:03:08,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███       | 314/1005 [29:31<1:06:44,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███▏      | 315/1005 [29:36<1:02:33,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 31%|███▏      | 316/1005 [29:42<1:06:09,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 317/1005 [29:47<1:02:01,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 318/1005 [29:54<1:06:04,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 319/1005 [29:58<1:02:09,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 320/1005 [30:05<1:05:58,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 321/1005 [30:09<1:01:59,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 322/1005 [30:17<1:09:30,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 323/1005 [30:22<1:04:31,  5.68s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 324/1005 [30:29<1:09:13,  6.10s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 325/1005 [30:33<1:03:52,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 32%|███▏      | 326/1005 [30:40<1:06:55,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 327/1005 [30:45<1:03:29,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 328/1005 [30:52<1:06:42,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 329/1005 [30:56<1:03:02,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 330/1005 [31:03<1:06:33,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 331/1005 [31:08<1:02:01,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 332/1005 [31:14<1:05:21,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 333/1005 [31:19<1:01:13,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 334/1005 [31:26<1:05:39,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 335/1005 [31:30<1:01:33,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 33%|███▎      | 336/1005 [31:37<1:05:41,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 337/1005 [31:42<1:01:44,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 338/1005 [31:48<1:05:18,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▎      | 339/1005 [31:53<1:01:01,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 340/1005 [32:00<1:05:29,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 341/1005 [32:05<1:01:15,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 342/1005 [32:11<1:04:44,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 343/1005 [32:16<1:00:49,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 344/1005 [32:23<1:05:41,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 345/1005 [32:28<1:03:22,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 34%|███▍      | 346/1005 [32:35<1:06:40,  6.07s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 347/1005 [32:40<1:01:40,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 348/1005 [32:47<1:08:26,  6.25s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 349/1005 [32:52<1:02:45,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 350/1005 [32:59<1:05:35,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▍      | 351/1005 [33:03<1:00:51,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 352/1005 [33:10<1:04:06,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 353/1005 [33:14<59:34,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 354/1005 [33:21<1:03:04,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 355/1005 [33:25<58:58,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 35%|███▌      | 356/1005 [33:32<1:02:49,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 357/1005 [33:37<58:54,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 358/1005 [33:43<1:02:26,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 359/1005 [33:48<58:20,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 360/1005 [33:54<1:02:10,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 361/1005 [33:59<58:08,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 362/1005 [34:06<1:01:54,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 363/1005 [34:10<57:49,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▌      | 364/1005 [34:17<1:01:45,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▋      | 365/1005 [34:21<57:37,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 36%|███▋      | 366/1005 [34:28<1:02:33,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 367/1005 [34:33<58:08,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 368/1005 [34:40<1:02:48,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 369/1005 [34:44<58:21,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 370/1005 [34:51<1:01:36,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 371/1005 [34:56<57:40,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 372/1005 [35:02<1:01:15,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 373/1005 [35:07<57:09,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 374/1005 [35:13<1:01:17,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 375/1005 [35:18<57:14,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 37%|███▋      | 376/1005 [35:25<1:00:52,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 377/1005 [35:29<56:56,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 378/1005 [35:36<1:00:18,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 379/1005 [35:40<56:39,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 380/1005 [35:47<1:01:09,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 381/1005 [35:52<58:16,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 382/1005 [35:59<1:01:17,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 383/1005 [36:03<57:02,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 384/1005 [36:10<1:00:23,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 385/1005 [36:15<56:26,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 38%|███▊      | 386/1005 [36:21<59:50,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 387/1005 [36:26<55:48,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 388/1005 [36:32<59:14,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▊      | 389/1005 [36:37<56:01,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 390/1005 [36:44<59:24,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 391/1005 [36:48<55:34,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 392/1005 [36:55<58:58,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 393/1005 [36:59<55:07,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 394/1005 [37:06<59:08,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 395/1005 [37:11<55:23,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 39%|███▉      | 396/1005 [37:17<58:46,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 397/1005 [37:22<54:46,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 398/1005 [37:29<59:06,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 399/1005 [37:33<55:03,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 400/1005 [37:40<58:30,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|███▉      | 401/1005 [37:44<54:35,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 402/1005 [37:51<58:05,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 403/1005 [37:56<54:31,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 404/1005 [38:02<57:54,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 405/1005 [38:07<54:08,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 406/1005 [38:13<57:36,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 40%|████      | 407/1005 [38:18<53:46,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 408/1005 [38:24<57:12,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 409/1005 [38:29<53:29,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 410/1005 [38:36<58:25,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 411/1005 [38:41<54:35,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 412/1005 [38:53<1:15:12,  7.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 413/1005 [38:58<1:06:03,  6.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████      | 414/1005 [39:02<59:36,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 415/1005 [39:09<1:01:10,  6.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 416/1005 [39:14<56:24,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 41%|████▏     | 417/1005 [39:20<58:48,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 418/1005 [39:25<54:32,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 419/1005 [39:32<1:00:44,  6.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 420/1005 [39:37<55:57,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 421/1005 [39:44<58:55,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 422/1005 [39:49<55:01,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 423/1005 [39:55<57:51,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 424/1005 [40:00<53:39,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 425/1005 [40:06<56:33,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 426/1005 [40:11<52:49,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 42%|████▏     | 427/1005 [40:18<56:04,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 428/1005 [40:22<52:59,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 429/1005 [40:29<56:03,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 430/1005 [40:34<52:20,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 431/1005 [40:40<55:47,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 432/1005 [40:45<52:18,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 433/1005 [40:52<55:28,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 434/1005 [40:58<55:36,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 435/1005 [41:02<51:47,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 436/1005 [41:09<55:49,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 43%|████▎     | 437/1005 [41:14<52:13,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▎     | 438/1005 [41:20<55:41,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▎     | 439/1005 [41:25<52:01,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 440/1005 [41:32<54:59,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 441/1005 [41:36<51:18,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 442/1005 [41:42<52:27,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 443/1005 [41:49<55:23,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 444/1005 [41:53<51:38,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 445/1005 [42:00<55:49,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 446/1005 [42:05<51:56,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 44%|████▍     | 447/1005 [42:12<54:35,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 448/1005 [42:16<50:59,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 449/1005 [42:23<53:55,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 450/1005 [42:27<50:25,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 451/1005 [42:34<53:44,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▍     | 452/1005 [42:39<50:18,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 453/1005 [42:45<53:17,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 454/1005 [42:50<49:50,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 455/1005 [42:56<52:55,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 456/1005 [43:01<49:57,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 45%|████▌     | 457/1005 [43:08<52:53,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 458/1005 [43:13<50:16,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 459/1005 [43:19<53:12,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 460/1005 [43:25<52:54,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 461/1005 [43:32<55:13,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 462/1005 [43:36<50:58,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▌     | 463/1005 [43:43<53:59,  5.98s/it]

Error: Unable to fetch details from PubMed

 46%|████▌     | 464/1005 [43:49<53:27,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 465/1005 [43:53<49:41,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 466/1005 [44:00<52:45,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 46%|████▋     | 467/1005 [44:05<50:51,  5.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 468/1005 [44:12<53:48,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 469/1005 [44:17<49:50,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 470/1005 [44:24<53:20,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 471/1005 [44:28<49:40,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 472/1005 [44:35<52:40,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 473/1005 [44:40<48:56,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 474/1005 [44:46<51:55,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 475/1005 [44:51<48:33,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 476/1005 [44:58<52:05,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 47%|████▋     | 477/1005 [45:02<48:32,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 478/1005 [45:09<51:34,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 479/1005 [45:14<48:48,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 480/1005 [45:20<49:12,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 481/1005 [45:26<51:45,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 482/1005 [45:31<48:03,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 483/1005 [45:37<50:51,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 484/1005 [45:42<48:16,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 485/1005 [45:49<50:48,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 486/1005 [45:54<47:32,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 48%|████▊     | 487/1005 [46:00<50:25,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▊     | 488/1005 [46:05<47:28,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▊     | 489/1005 [46:12<50:52,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 490/1005 [46:17<49:14,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 491/1005 [46:24<51:30,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 492/1005 [46:28<47:40,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 493/1005 [46:35<50:27,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 494/1005 [46:40<47:52,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 495/1005 [46:47<50:10,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 496/1005 [46:51<46:33,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 49%|████▉     | 497/1005 [46:58<49:12,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 498/1005 [47:02<46:00,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 499/1005 [47:10<50:59,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 500/1005 [47:14<47:05,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 501/1005 [47:20<48:03,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|████▉     | 502/1005 [47:27<51:24,  6.13s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 503/1005 [47:32<48:53,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 504/1005 [47:39<51:06,  6.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 505/1005 [47:44<47:05,  5.65s/it]

Error: Unable to fetch details from PubMed
['LINC01287', 'TLR7', 'IGLL5', 'STMN4', 'NR1I2']
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 506/1005 [47:50<49:34,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 50%|█████     | 507/1005 [47:55<45:59,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 508/1005 [48:02<48:57,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 509/1005 [48:06<45:30,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 510/1005 [48:13<49:06,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 511/1005 [48:18<45:47,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 512/1005 [48:25<48:25,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 513/1005 [48:29<45:16,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 514/1005 [48:36<47:45,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████     | 515/1005 [48:40<44:31,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████▏    | 516/1005 [48:47<47:15,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 51%|█████▏    | 517/1005 [48:52<44:06,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 518/1005 [48:58<46:58,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 519/1005 [49:03<44:55,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 520/1005 [49:10<47:39,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 521/1005 [49:15<44:25,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 522/1005 [49:21<47:29,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 523/1005 [49:26<44:14,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 524/1005 [49:33<47:25,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 525/1005 [49:37<44:03,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 526/1005 [49:44<46:33,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 52%|█████▏    | 527/1005 [49:49<43:24,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 528/1005 [49:55<46:26,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 529/1005 [50:01<44:54,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 530/1005 [50:07<46:59,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 531/1005 [50:12<43:52,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 532/1005 [50:18<46:25,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 533/1005 [50:23<43:29,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 534/1005 [50:30<45:48,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 535/1005 [50:34<42:44,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 536/1005 [50:41<45:24,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 53%|█████▎    | 537/1005 [50:45<42:21,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 538/1005 [50:52<44:55,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 539/1005 [50:57<42:01,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▎    | 540/1005 [51:03<44:57,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 541/1005 [51:08<42:25,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 542/1005 [51:15<44:47,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 543/1005 [51:19<41:49,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 544/1005 [51:26<44:35,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 545/1005 [51:30<41:30,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 546/1005 [51:37<44:41,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 54%|█████▍    | 547/1005 [51:42<41:37,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 548/1005 [51:48<44:16,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 549/1005 [51:53<41:20,  5.44s/it]

Error: Unable to fetch details from PubMed

 55%|█████▍    | 550/1005 [51:59<41:36,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 551/1005 [52:05<44:40,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▍    | 552/1005 [52:10<41:37,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 553/1005 [52:17<44:03,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 554/1005 [52:21<41:09,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 555/1005 [52:28<43:52,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 556/1005 [52:32<40:46,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 55%|█████▌    | 557/1005 [52:39<43:21,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 558/1005 [52:44<40:32,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 559/1005 [52:50<43:01,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 560/1005 [52:55<41:17,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 561/1005 [53:02<43:24,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 562/1005 [53:06<40:29,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 563/1005 [53:13<42:46,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 564/1005 [53:18<39:53,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▌    | 565/1005 [53:24<42:21,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▋    | 566/1005 [53:29<39:56,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 56%|█████▋    | 567/1005 [53:36<43:09,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 568/1005 [53:41<40:17,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 569/1005 [53:47<42:28,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 570/1005 [53:52<39:47,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 571/1005 [53:58<42:06,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 572/1005 [54:03<39:55,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 573/1005 [54:10<42:01,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 574/1005 [54:14<39:19,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 575/1005 [54:21<41:35,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 576/1005 [54:26<38:52,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 57%|█████▋    | 577/1005 [54:32<41:30,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 578/1005 [54:37<38:39,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 579/1005 [54:44<41:33,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 580/1005 [54:48<38:55,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 581/1005 [54:55<41:08,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 582/1005 [54:59<38:20,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 583/1005 [55:06<41:14,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 584/1005 [55:11<38:20,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 585/1005 [55:17<40:33,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 586/1005 [55:22<37:48,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 58%|█████▊    | 587/1005 [55:28<40:11,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▊    | 588/1005 [55:33<37:45,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▊    | 589/1005 [55:40<40:14,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▊    | 590/1005 [55:44<37:31,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 591/1005 [55:50<37:39,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 592/1005 [55:57<40:36,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 593/1005 [56:02<38:50,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 594/1005 [56:09<41:38,  6.08s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 595/1005 [56:14<38:24,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 596/1005 [56:20<40:44,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 59%|█████▉    | 597/1005 [56:25<37:52,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 598/1005 [56:32<40:08,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 599/1005 [56:36<37:25,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 600/1005 [56:43<39:31,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 601/1005 [56:48<37:03,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|█████▉    | 602/1005 [56:54<39:10,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 603/1005 [56:59<36:37,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 604/1005 [57:05<38:58,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 605/1005 [57:10<36:16,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 606/1005 [57:17<38:41,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 607/1005 [57:21<36:04,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 60%|██████    | 608/1005 [57:28<38:14,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 609/1005 [57:33<36:51,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 610/1005 [57:40<38:45,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 611/1005 [57:44<36:07,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 612/1005 [57:51<38:08,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 613/1005 [57:55<35:31,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 614/1005 [58:02<38:38,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████    | 615/1005 [58:07<35:52,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 616/1005 [58:15<40:18,  6.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 617/1005 [58:19<37:06,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 61%|██████▏   | 618/1005 [58:26<38:44,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 619/1005 [58:31<36:00,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 620/1005 [58:37<37:45,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 621/1005 [58:42<35:07,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 622/1005 [58:48<37:17,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 623/1005 [58:53<34:42,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 624/1005 [59:00<36:43,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 625/1005 [59:04<34:17,  5.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 626/1005 [59:11<36:23,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 627/1005 [59:15<34:01,  5.40s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 62%|██████▏   | 628/1005 [59:22<36:11,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 629/1005 [59:26<33:55,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 630/1005 [59:33<36:08,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 631/1005 [59:38<34:05,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 632/1005 [59:44<36:12,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 633/1005 [59:49<33:50,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 634/1005 [59:56<35:52,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 635/1005 [1:00:00<33:29,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 636/1005 [1:00:07<35:39,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 63%|██████▎   | 637/1005 [1:00:15<40:03,  6.53s/it]

Error: Unable to fetch details from PubMed

 63%|██████▎   | 638/1005 [1:00:26<47:22,  7.75s/it]

Error: Unable to fetch details from PubMed

 64%|██████▎   | 639/1005 [1:00:34<47:33,  7.80s/it]

Error: Unable to fetch details from PubMed

 64%|██████▎   | 640/1005 [1:00:39<43:01,  7.07s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 641/1005 [1:00:49<48:04,  7.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 642/1005 [1:00:54<43:03,  7.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 643/1005 [1:01:05<50:13,  8.33s/it]

Error: Unable to fetch details from PubMed

 64%|██████▍   | 644/1005 [1:01:16<54:12,  9.01s/it]

Error: Unable to fetch details from PubMed

 64%|██████▍   | 646/1005 [1:01:33<51:37,  8.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 647/1005 [1:01:38<45:52,  7.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 64%|██████▍   | 648/1005 [1:01:48<49:52,  8.38s/it]

Error: Unable to fetch details from PubMed

 65%|██████▍   | 649/1005 [1:01:55<46:58,  7.92s/it]

Error: Unable to fetch details from PubMed

 65%|██████▍   | 650/1005 [1:02:04<48:08,  8.14s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▍   | 651/1005 [1:02:12<48:20,  8.19s/it]

Error: Unable to fetch details from PubMed

 65%|██████▍   | 652/1005 [1:02:18<44:53,  7.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▍   | 653/1005 [1:02:26<44:15,  7.54s/it]

Error: Unable to fetch details from PubMed

 65%|██████▌   | 654/1005 [1:02:33<44:34,  7.62s/it]

Error: Unable to fetch details from PubMed

 65%|██████▌   | 655/1005 [1:02:46<53:25,  9.16s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▌   | 656/1005 [1:02:52<48:01,  8.26s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 65%|██████▌   | 657/1005 [1:03:01<49:29,  8.53s/it]

Error: Unable to fetch details from PubMed

 65%|██████▌   | 658/1005 [1:03:07<44:24,  7.68s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▌   | 659/1005 [1:03:17<47:44,  8.28s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 660/1005 [1:03:26<49:57,  8.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▌   | 661/1005 [1:03:32<43:42,  7.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▌   | 662/1005 [1:03:41<46:06,  8.07s/it]

Error: Unable to fetch details from PubMed

 66%|██████▌   | 663/1005 [1:03:46<41:42,  7.32s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▌   | 664/1005 [1:03:53<41:24,  7.29s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▋   | 666/1005 [1:04:15<51:16,  9.08s/it]

Error: Unable to fetch details from PubMed

 66%|██████▋   | 667/1005 [1:04:23<48:58,  8.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 66%|██████▋   | 668/1005 [1:04:32<49:32,  8.82s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 669/1005 [1:04:39<46:46,  8.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 670/1005 [1:04:51<52:49,  9.46s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 671/1005 [1:04:57<46:51,  8.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 672/1005 [1:05:04<44:42,  8.06s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 673/1005 [1:05:12<44:33,  8.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 674/1005 [1:05:19<42:33,  7.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 675/1005 [1:05:27<42:10,  7.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 67%|██████▋   | 676/1005 [1:05:37<45:23,  8.28s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 677/1005 [1:05:47<49:19,  9.02s/it]

Error: Unable to fetch details from PubMed

 67%|██████▋   | 678/1005 [1:05:54<45:39,  8.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 679/1005 [1:06:00<40:41,  7.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 680/1005 [1:06:09<43:38,  8.06s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 681/1005 [1:06:14<38:43,  7.17s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 682/1005 [1:06:25<44:07,  8.20s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 683/1005 [1:06:34<45:41,  8.51s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 684/1005 [1:06:40<40:42,  7.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 685/1005 [1:06:46<39:10,  7.34s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 68%|██████▊   | 686/1005 [1:06:56<42:10,  7.93s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 687/1005 [1:07:05<44:38,  8.42s/it]

Error: Unable to fetch details from PubMed

 68%|██████▊   | 688/1005 [1:07:11<39:59,  7.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▊   | 689/1005 [1:07:20<43:19,  8.23s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▊   | 690/1005 [1:07:27<40:30,  7.71s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 691/1005 [1:07:36<42:05,  8.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▉   | 692/1005 [1:07:42<39:46,  7.62s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 693/1005 [1:07:49<38:04,  7.32s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 695/1005 [1:08:06<40:48,  7.90s/it]

Error: Unable to fetch details from PubMed

 69%|██████▉   | 696/1005 [1:08:11<36:55,  7.17s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▉   | 697/1005 [1:08:24<44:53,  8.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 69%|██████▉   | 698/1005 [1:08:28<38:38,  7.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 699/1005 [1:08:37<39:35,  7.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 700/1005 [1:08:46<41:45,  8.22s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 701/1005 [1:08:53<40:07,  7.92s/it]

Error: Unable to fetch details from PubMed

 70%|██████▉   | 702/1005 [1:09:01<39:20,  7.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|██████▉   | 703/1005 [1:09:08<38:18,  7.61s/it]

Error: Unable to fetch details from PubMed

 70%|███████   | 705/1005 [1:09:32<49:25,  9.88s/it]

Error: Unable to fetch details from PubMed

 70%|███████   | 706/1005 [1:09:41<48:10,  9.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 70%|███████   | 707/1005 [1:09:47<42:05,  8.47s/it]

Error: Unable to fetch details from PubMed

 70%|███████   | 708/1005 [1:09:55<41:15,  8.33s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 709/1005 [1:10:03<40:16,  8.16s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 710/1005 [1:10:11<40:10,  8.17s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 713/1005 [1:10:47<53:32, 11.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 714/1005 [1:10:52<44:49,  9.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████   | 715/1005 [1:11:02<44:35,  9.22s/it]

Error: Unable to fetch details from PubMed

 71%|███████   | 716/1005 [1:11:09<41:46,  8.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████▏  | 717/1005 [1:11:16<39:41,  8.27s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 71%|███████▏  | 718/1005 [1:11:22<35:07,  7.34s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 719/1005 [1:11:31<38:30,  8.08s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 720/1005 [1:11:45<45:53,  9.66s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 721/1005 [1:11:54<45:34,  9.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 72%|███████▏  | 722/1005 [1:12:00<39:18,  8.33s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 72%|███████▏  | 725/1005 [1:12:37<50:46, 10.88s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 726/1005 [1:12:46<47:53, 10.30s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 727/1005 [1:12:54<44:27,  9.59s/it]

Error: Unable to fetch details from PubMed

 72%|███████▏  | 728/1005 [1:13:01<40:09,  8.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 729/1005 [1:13:09<39:21,  8.56s/it]

Error: Unable to fetch details from PubMed

 73%|███████▎  | 730/1005 [1:13:17<39:03,  8.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 731/1005 [1:13:24<37:02,  8.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 732/1005 [1:13:30<32:44,  7.20s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 733/1005 [1:13:36<31:45,  7.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 734/1005 [1:13:49<39:28,  8.74s/it]

Error: Unable to fetch details from PubMed

 73%|███████▎  | 735/1005 [1:13:57<38:25,  8.54s/it]

Error: Unable to fetch details from PubMed

 73%|███████▎  | 737/1005 [1:14:15<39:35,  8.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 73%|███████▎  | 738/1005 [1:14:26<41:56,  9.42s/it]

Error: Unable to fetch details from PubMed

 74%|███████▎  | 739/1005 [1:14:31<36:38,  8.27s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▎  | 740/1005 [1:14:40<36:51,  8.35s/it]

Error: Unable to fetch details from PubMed

 74%|███████▎  | 741/1005 [1:14:51<39:50,  9.05s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 742/1005 [1:14:58<36:53,  8.42s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 743/1005 [1:15:09<41:09,  9.43s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 744/1005 [1:15:16<37:13,  8.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▍  | 745/1005 [1:15:25<38:09,  8.81s/it]

Error: Unable to fetch details from PubMed

 74%|███████▍  | 746/1005 [1:15:30<32:02,  7.42s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▍  | 747/1005 [1:15:36<30:22,  7.06s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 74%|███████▍  | 748/1005 [1:15:44<31:37,  7.38s/it]

Error: Unable to fetch details from PubMed

 75%|███████▍  | 749/1005 [1:15:52<32:21,  7.58s/it]

Error: Unable to fetch details from PubMed

 75%|███████▍  | 750/1005 [1:15:56<27:31,  6.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▍  | 751/1005 [1:16:05<31:14,  7.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▍  | 752/1005 [1:16:14<33:02,  7.84s/it]

Error: Unable to fetch details from PubMed

 75%|███████▍  | 753/1005 [1:16:21<31:00,  7.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▌  | 754/1005 [1:16:28<31:30,  7.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▌  | 755/1005 [1:16:39<34:47,  8.35s/it]

Error: Unable to fetch details from PubMed

 75%|███████▌  | 756/1005 [1:16:44<30:38,  7.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 75%|███████▌  | 757/1005 [1:16:55<34:44,  8.41s/it]

Error: Unable to fetch details from PubMed

 75%|███████▌  | 758/1005 [1:17:02<32:53,  7.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 759/1005 [1:17:06<28:33,  6.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 760/1005 [1:17:13<27:57,  6.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 761/1005 [1:17:17<25:01,  6.15s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 762/1005 [1:17:24<25:25,  6.28s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 763/1005 [1:17:28<23:13,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 764/1005 [1:17:35<24:08,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 765/1005 [1:17:40<22:33,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▌  | 766/1005 [1:17:47<24:00,  6.03s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▋  | 767/1005 [1:17:52<22:23,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 76%|███████▋  | 768/1005 [1:17:59<24:38,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 769/1005 [1:18:04<22:33,  5.73s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 770/1005 [1:18:11<23:59,  6.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 771/1005 [1:18:15<22:12,  5.70s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 772/1005 [1:18:22<23:19,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 773/1005 [1:18:27<21:32,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 774/1005 [1:18:34<22:53,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 775/1005 [1:18:38<21:13,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 776/1005 [1:18:45<22:27,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 777/1005 [1:18:50<21:19,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 77%|███████▋  | 778/1005 [1:18:57<22:33,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 779/1005 [1:19:02<22:19,  5.93s/it]

Error: Unable to fetch details from PubMed

 78%|███████▊  | 780/1005 [1:19:07<20:40,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 781/1005 [1:19:14<21:48,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 782/1005 [1:19:18<20:30,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 783/1005 [1:19:25<21:41,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 784/1005 [1:19:30<20:08,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 785/1005 [1:19:35<20:12,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 786/1005 [1:19:40<19:32,  5.35s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 787/1005 [1:19:47<20:50,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 78%|███████▊  | 788/1005 [1:19:52<19:42,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 789/1005 [1:19:59<21:58,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 790/1005 [1:20:04<20:26,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▊  | 791/1005 [1:20:09<19:11,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 792/1005 [1:20:15<20:24,  5.75s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 793/1005 [1:20:20<19:03,  5.39s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 794/1005 [1:20:26<20:18,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 795/1005 [1:20:31<18:59,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 796/1005 [1:20:38<20:15,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 797/1005 [1:20:42<18:52,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 79%|███████▉  | 798/1005 [1:20:49<19:59,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 799/1005 [1:20:54<19:32,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 800/1005 [1:21:01<20:21,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 801/1005 [1:21:06<18:48,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 802/1005 [1:21:12<19:55,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|███████▉  | 803/1005 [1:21:17<18:33,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 804/1005 [1:21:23<19:31,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 805/1005 [1:21:28<18:12,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 806/1005 [1:21:36<20:24,  6.15s/it]

Error: Unable to fetch details from PubMed

 80%|████████  | 807/1005 [1:21:40<18:43,  5.68s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 808/1005 [1:21:47<19:41,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 80%|████████  | 809/1005 [1:21:52<18:20,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 810/1005 [1:21:58<19:11,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 811/1005 [1:22:03<17:48,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 812/1005 [1:22:10<19:22,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 813/1005 [1:22:15<17:55,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 814/1005 [1:22:22<18:59,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 815/1005 [1:22:26<17:34,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████  | 816/1005 [1:22:33<18:28,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 817/1005 [1:22:37<17:07,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 818/1005 [1:22:44<18:14,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 81%|████████▏ | 819/1005 [1:22:49<17:04,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 820/1005 [1:22:55<18:01,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 821/1005 [1:23:00<16:44,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 822/1005 [1:23:07<17:41,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 823/1005 [1:23:11<16:31,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 824/1005 [1:23:18<17:32,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 825/1005 [1:23:22<16:17,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 826/1005 [1:23:29<17:17,  5.80s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 827/1005 [1:23:34<16:06,  5.43s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 828/1005 [1:23:40<17:03,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 82%|████████▏ | 829/1005 [1:23:45<15:52,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 830/1005 [1:23:51<16:48,  5.76s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 831/1005 [1:23:57<16:35,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 832/1005 [1:24:04<17:13,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 833/1005 [1:24:08<16:05,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 834/1005 [1:24:15<16:56,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 835/1005 [1:24:20<15:43,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 836/1005 [1:24:26<16:32,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 837/1005 [1:24:31<15:36,  5.57s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 838/1005 [1:24:38<16:49,  6.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 83%|████████▎ | 839/1005 [1:24:43<15:33,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▎ | 840/1005 [1:24:50<16:26,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▎ | 841/1005 [1:24:54<15:10,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 842/1005 [1:25:01<16:16,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 843/1005 [1:25:07<15:37,  5.79s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 844/1005 [1:25:14<16:24,  6.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 845/1005 [1:25:18<15:13,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 846/1005 [1:25:25<16:00,  6.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 847/1005 [1:25:30<14:46,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 848/1005 [1:25:36<15:27,  5.91s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 84%|████████▍ | 849/1005 [1:25:41<14:21,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 850/1005 [1:25:48<15:04,  5.83s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 851/1005 [1:25:53<14:34,  5.68s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 852/1005 [1:25:59<15:13,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 853/1005 [1:26:04<14:09,  5.59s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▍ | 854/1005 [1:26:11<15:07,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 855/1005 [1:26:16<13:59,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 856/1005 [1:26:22<14:39,  5.91s/it]

Error: Unable to fetch details from PubMed

 85%|████████▌ | 857/1005 [1:26:31<16:30,  6.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 858/1005 [1:26:36<15:05,  6.16s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 85%|████████▌ | 859/1005 [1:26:42<15:17,  6.28s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 860/1005 [1:26:47<14:03,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 861/1005 [1:26:54<14:34,  6.07s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 862/1005 [1:26:58<13:23,  5.62s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 863/1005 [1:27:05<14:02,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 864/1005 [1:27:10<13:03,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 865/1005 [1:27:17<13:50,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▌ | 866/1005 [1:27:21<12:47,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 867/1005 [1:27:28<13:33,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 868/1005 [1:27:32<12:31,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 86%|████████▋ | 869/1005 [1:27:39<13:17,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 870/1005 [1:27:44<12:19,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 871/1005 [1:27:50<13:02,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 872/1005 [1:27:55<12:06,  5.46s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 873/1005 [1:28:02<12:47,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 874/1005 [1:28:06<11:53,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 875/1005 [1:28:13<12:31,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 876/1005 [1:28:17<11:38,  5.41s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 877/1005 [1:28:24<12:17,  5.76s/it]

Error: Unable to fetch details from PubMed

 87%|████████▋ | 878/1005 [1:28:30<12:05,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 87%|████████▋ | 879/1005 [1:28:35<11:34,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 880/1005 [1:28:41<12:14,  5.88s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 881/1005 [1:28:46<11:33,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 882/1005 [1:28:53<12:15,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 883/1005 [1:28:58<11:17,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 884/1005 [1:29:05<12:00,  5.96s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 885/1005 [1:29:09<11:12,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 886/1005 [1:29:16<11:50,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 887/1005 [1:29:21<10:53,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 888/1005 [1:29:28<11:36,  5.95s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 88%|████████▊ | 889/1005 [1:29:32<10:45,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▊ | 890/1005 [1:29:39<11:15,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▊ | 891/1005 [1:29:44<10:27,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 892/1005 [1:29:51<11:30,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 893/1005 [1:29:56<10:32,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 894/1005 [1:30:02<10:58,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 895/1005 [1:30:07<10:23,  5.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 896/1005 [1:30:14<11:04,  6.09s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 897/1005 [1:30:19<10:09,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 898/1005 [1:30:26<10:35,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 89%|████████▉ | 899/1005 [1:30:30<09:44,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 900/1005 [1:30:37<10:15,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 901/1005 [1:30:41<09:30,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 902/1005 [1:30:48<09:58,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 903/1005 [1:30:53<09:18,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|████████▉ | 904/1005 [1:31:01<10:25,  6.19s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 905/1005 [1:31:05<09:29,  5.69s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 906/1005 [1:31:12<09:52,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 907/1005 [1:31:16<09:04,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 908/1005 [1:31:23<09:45,  6.04s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 90%|█████████ | 909/1005 [1:31:28<08:57,  5.60s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 910/1005 [1:31:35<09:20,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 911/1005 [1:31:39<08:37,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 912/1005 [1:31:46<09:02,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 913/1005 [1:31:51<08:30,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 914/1005 [1:31:57<08:53,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 915/1005 [1:32:02<08:12,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 916/1005 [1:32:09<08:42,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████ | 917/1005 [1:32:13<08:01,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████▏| 918/1005 [1:32:21<09:03,  6.24s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 91%|█████████▏| 919/1005 [1:32:26<08:13,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 920/1005 [1:32:32<08:28,  5.99s/it]

Error: Unable to fetch details from PubMed

 92%|█████████▏| 921/1005 [1:32:38<08:15,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 922/1005 [1:32:43<07:38,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 923/1005 [1:32:50<08:06,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 924/1005 [1:32:54<07:27,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 925/1005 [1:33:01<07:48,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 926/1005 [1:33:06<07:26,  5.65s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 927/1005 [1:33:13<07:48,  6.01s/it]

Error: Unable to fetch details from PubMed

 92%|█████████▏| 928/1005 [1:33:19<07:36,  5.93s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 92%|█████████▏| 929/1005 [1:33:25<07:45,  6.12s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 930/1005 [1:33:30<07:04,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 931/1005 [1:33:36<07:19,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 932/1005 [1:33:41<06:44,  5.54s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 933/1005 [1:33:48<07:02,  5.87s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 934/1005 [1:33:52<06:30,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 935/1005 [1:33:59<06:50,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 936/1005 [1:34:04<06:29,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 937/1005 [1:34:11<06:43,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 938/1005 [1:34:16<06:19,  5.66s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 93%|█████████▎| 939/1005 [1:34:23<06:43,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 940/1005 [1:34:27<06:08,  5.67s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 941/1005 [1:34:34<06:23,  6.00s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▎| 942/1005 [1:34:39<05:51,  5.58s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 943/1005 [1:34:46<06:10,  5.98s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 944/1005 [1:34:50<05:39,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 945/1005 [1:34:57<05:56,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 946/1005 [1:35:02<05:26,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 947/1005 [1:35:09<05:47,  5.99s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 948/1005 [1:35:13<05:16,  5.55s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 94%|█████████▍| 949/1005 [1:35:20<05:28,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 950/1005 [1:35:24<05:00,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 951/1005 [1:35:31<05:13,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 952/1005 [1:35:36<04:48,  5.44s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 953/1005 [1:35:42<05:03,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▍| 954/1005 [1:35:47<04:39,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 955/1005 [1:35:54<04:54,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 956/1005 [1:35:59<04:30,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 957/1005 [1:36:06<04:48,  6.01s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 958/1005 [1:36:11<04:28,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 95%|█████████▌| 959/1005 [1:36:18<04:40,  6.11s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 960/1005 [1:36:22<04:13,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 961/1005 [1:36:29<04:21,  5.94s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 962/1005 [1:36:34<03:59,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 963/1005 [1:36:40<04:07,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 964/1005 [1:36:45<03:45,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 965/1005 [1:36:52<03:54,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 966/1005 [1:36:56<03:35,  5.53s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▌| 967/1005 [1:37:03<03:42,  5.86s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▋| 968/1005 [1:37:08<03:23,  5.50s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 96%|█████████▋| 969/1005 [1:37:15<03:33,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 970/1005 [1:37:20<03:19,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 971/1005 [1:37:27<03:25,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 972/1005 [1:37:31<03:05,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 973/1005 [1:37:38<03:10,  5.97s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 974/1005 [1:37:43<02:58,  5.77s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 975/1005 [1:37:48<02:44,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 976/1005 [1:37:55<02:48,  5.81s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 977/1005 [1:37:59<02:32,  5.45s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 978/1005 [1:38:06<02:37,  5.84s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 97%|█████████▋| 979/1005 [1:38:11<02:26,  5.64s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 980/1005 [1:38:18<02:30,  6.02s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 981/1005 [1:38:23<02:14,  5.61s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 982/1005 [1:38:29<02:15,  5.90s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 983/1005 [1:38:34<02:01,  5.51s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 984/1005 [1:38:41<02:03,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 985/1005 [1:38:45<01:49,  5.49s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 986/1005 [1:38:52<01:51,  5.85s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 987/1005 [1:38:57<01:38,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 988/1005 [1:39:03<01:38,  5.82s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 98%|█████████▊| 989/1005 [1:39:08<01:28,  5.52s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 990/1005 [1:39:14<01:23,  5.56s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 991/1005 [1:39:18<01:13,  5.26s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▊| 992/1005 [1:39:25<01:14,  5.72s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 993/1005 [1:39:30<01:04,  5.38s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 994/1005 [1:39:36<01:03,  5.74s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 995/1005 [1:39:41<00:54,  5.47s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 996/1005 [1:39:48<00:53,  5.89s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 997/1005 [1:39:52<00:43,  5.48s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 998/1005 [1:39:59<00:41,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

 99%|█████████▉| 999/1005 [1:40:05<00:34,  5.71s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1000/1005 [1:40:12<00:31,  6.30s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1001/1005 [1:40:17<00:23,  5.78s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1002/1005 [1:40:24<00:18,  6.05s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1003/1005 [1:40:28<00:11,  5.63s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|█████████▉| 1004/1005 [1:40:35<00:05,  5.92s/it]

Error: Unable to fetch details from PubMed
Error: Unable to fetch details from PubMed

100%|██████████| 1005/1005 [1:40:39<00:00,  6.01s/it]

Error: Unable to fetch details from PubMed

In [22]:
results = pd.DataFrame(results)[[0, 1, 2, 3]]
results.columns = ["NSC", "drug", "gene", "num"]
results

         NSC          drug       gene  num
0        740  METHOTREXATE  LINC01287    0
1        740  METHOTREXATE     JCHAIN    0
2        740  METHOTREXATE      IGLL5    0
3        740  METHOTREXATE      PVALB    0
4        740  METHOTREXATE    MIR5699    0
...      ...           ...        ...  ...
5020  820919    NVP-BHG712      IGLL5    0
5021  820919    NVP-BHG712  LINC01287    0
5022  820919    NVP-BHG712      HTR1A    0
5023  820919    NVP-BHG712       TLR7    0
5024  820919    NVP-BHG712   SNORD83B    0

[5025 rows x 4 columns]

In [23]:
results.to_csv("result_all_train.csv", index=False)