In [1]:
library(rcellminer) # Load the rcellminer library
library(rcellminerData) # Load the rcellminerData library
library(tidyverse)
library(data.table)

Loading required package: Biobase

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, table,
    tapply, union, unique, unsplit, which.max, which.min


Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: rcellminerData

Consider citing this package: Luna A, et al. rcellminer: exploring molecular profiles and drug response of the NCI-60 cell lines in R. PMID: 26635141; citation("rcellminer")

── Attaching core tidyverse packages ──────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::combine()    masks Biobase::combine(), BiocGenerics::combine()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::lag()        masks stats::lag()
✖ ggplot2::Position() masks BiocGenerics::Position(), base::Position()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [2]:
install.packages("~/Desktop/ctrpData_1.0.8.tar.gz", repos = NULL, type = "source")
install.packages("~/Desktop/gdsc1Data_0.1.1.tar.gz", repos = NULL, type = "source")
install.packages("~/Desktop/gdsc2Data_0.1.1.tar.gz", repos = NULL, type = "source")
install.packages("~/Desktop/gdscDataDec15_1.1.4.tar.gz", repos = NULL, type = "source")
install.packages("~/Downloads/ccleData_1.0.9.tar.gz", repos = NULL, type = "source")

# NCI60 data

In [3]:
# drugAct <- exprs(getAct(rcellminerData::drugData)) # Get drug activity data
# write.csv(drugAct, '../nci_data/drugAct.csv') # Save as a CSV file

expression <- getAllFeatureData(rcellminerData::molData)[["xsq"]]
names <- read.csv("simplified_names.csv", stringsAsFactors = FALSE)
colnames(expression) <- sapply(colnames(expression), function(x) names[names[,1] == x, 2])
expression <- expression[order(row.names(expression)),]
                               
expression <- cbind(Gene = rownames(expression), as.data.frame(expression))
expression <- as.data.table(expression)

setkey(expression, Gene)

n <- nrow(expression)
half <- ceiling(n / 2)

expression_part1 <- expression[1:half]
expression_part2 <- expression[(half + 1):n]

fwrite(expression_part1, '../data/nci_data/gene_exp_part1.csv.gz', 
       compress = "gzip", quote = TRUE)
fwrite(expression_part2, '../data/nci_data/gene_exp_part2.csv.gz',
       compress = "gzip", quote = TRUE)                        

mutation <- getAllFeatureData(rcellminerData::molData)[["mut"]]
names <- read.csv("simplified_names.csv", stringsAsFactors = FALSE)
colnames(mutation) <- sapply(colnames(mutation), function(x) names[names[,1] == x, 2])
mutation <- mutation[order(row.names(mutation)),]

write.csv(mutation, '../data/nci_data/mut.csv') # Save as a CSV file

In [4]:
methylation <- getAllFeatureData(rcellminerData::molData)[["met"]]
names <- read.csv("simplified_names.csv", stringsAsFactors = FALSE)
colnames(methylation) <- sapply(colnames(methylation), function(x) names[names[,1] == x, 2])
methylation <- methylation[order(row.names(methylation)),]
write.csv(methylation, '../data/nci_data/met.csv') # Save as a CSV file

# CTRP data

Mutation data is the same with CCLE

In [5]:
# drugAct <- exprs(getAct(ctrpData::drugData)) # Get drug activity data
# write.csv(drugAct, '../ctrp_data/drugAct.csv') # Save as a CSV file

expression <- getAllFeatureData(ccleData::molData)[["xsq"]]
expression <- expression[order(row.names(expression)),]

expression <- cbind(Gene = rownames(expression), as.data.frame(expression))
expression <- as.data.table(expression)

setkey(expression, Gene)

n <- nrow(expression)
third <- ceiling(n / 3)

expression_part1 <- expression[1:third]
expression_part2 <- expression[(third + 1):(2 * third)]
expression_part3 <- expression[(2 * third + 1):n]

fwrite(expression_part1, '../data/ctrp_data/gene_exp_part1.csv.gz', compress = "gzip")
fwrite(expression_part2, '../data/ctrp_data/gene_exp_part2.csv.gz', compress = "gzip")
fwrite(expression_part3, '../data/ctrp_data/gene_exp_part3.csv.gz', compress = "gzip")

mutation <- getAllFeatureData(ccleData::molData)[["mut"]]
mutation <- mutation[order(row.names(mutation)),]
write.csv(mutation, '../data/ctrp_data/mut.csv') # Save as a CSV file

In [6]:
methylation <- getAllFeatureData(ccleData::molData)[["rrb"]]
methylation <- methylation[order(row.names(methylation)),]
                               
methylation <- cbind(Gene = rownames(methylation), as.data.frame(methylation))
methylation <- as.data.table(methylation)

setkey(methylation, Gene)

n <- nrow(methylation)
half <- ceiling(n / 2)

methylation_part1 <- methylation[1:half]
methylation_part2 <- methylation[(half + 1):n]

fwrite(methylation_part1, '../data/ctrp_data/met_part1.csv.gz', compress = "gzip")
fwrite(methylation_part2, '../data/ctrp_data/met_part2.csv.gz', compress = "gzip")

# GDSC1 & 2
GDSC's expression and mutation data are in gdscDataDec15

In [7]:
# drugAct <- exprs(getAct(gdsc1Data::drugData)) # Get drug activity data
# write.csv(drugAct, '../gdsc1_data/drugAct.csv') # Save as a CSV file

expression <- getAllFeatureData(gdscDataDec15::molData)[["xsq"]]
expression <- expression[order(row.names(expression)),]
                               
expression <- cbind(Gene = rownames(expression), as.data.frame(expression))
expression <- as.data.table(expression)

setkey(expression, Gene)

n <- nrow(expression)
half <- ceiling(n / 2)

expression_part1 <- expression[1:half]
expression_part2 <- expression[(half + 1):n]

fwrite(expression_part1, '../data/gdsc1_data/gene_exp_part1.csv.gz', compress = "gzip")
fwrite(expression_part2, '../data/gdsc1_data/gene_exp_part2.csv.gz', compress = "gzip")

fwrite(expression_part1, '../data/gdsc2_data/gene_exp_part1.csv.gz', compress = "gzip")
fwrite(expression_part2, '../data/gdsc2_data/gene_exp_part2.csv.gz', compress = "gzip")

mutation <- getAllFeatureData(gdscDataDec15::molData)[["mut"]]
mutation <- mutation[order(row.names(mutation)),]
write.csv(mutation, '../data/gdsc1_data/mut.csv') # Save as a CSV file
write.csv(mutation, '../data/gdsc2_data/mut.csv') # Save as a CSV file

In [10]:
expression <- getAllFeatureData(gdscDataDec15::molData)[["xsq"]]
expression <- expression[order(row.names(expression)),]
expression

            201T 22RV1 23132-87 42-MG-BA 451Lu      5637 639-V 647-V 697 769-P
A1BG        NA   NA    NA       NA       0.25096157 NA   NA    NA    NA  NA
A1BG-AS1    NA   NA    NA       NA       2.37573454 NA   NA    NA    NA  NA
A1CF        NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
A2M         NA   NA    NA       NA       6.45121111 NA   NA    NA    NA  NA
A2M-AS1     NA   NA    NA       NA       0.12432814 NA   NA    NA    NA  NA
A2ML1       NA   NA    NA       NA       0.01435529 NA   NA    NA    NA  NA
A2ML1-AS1   NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
A2ML1-AS2   NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
A2MP1       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
A3GALT2     NA   NA    NA       NA       0.12432814 NA   NA    NA    NA  NA
A4GALT      NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
A4GNT       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AAAS        NA   NA    NA       NA       3.87381320 NA   NA    NA    NA  NA
AACS        NA   NA    NA       NA       1.98550043 NA   NA    NA    NA  NA
AACSP1      NA   NA    NA       NA       0.04264434 NA   NA    NA    NA  NA
AADAC       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADACL2     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADACL2-AS1 NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADACL3     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADACL4     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADACP1     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
AADAT       NA   NA    NA       NA       2.20789285 NA   NA    NA    NA  NA
AAED1       NA   NA    NA       NA       1.77399633 NA   NA    NA    NA  NA
AAGAB       NA   NA    NA       NA       3.55704242 NA   NA    NA    NA  NA
AAK1        NA   NA    NA       NA       2.19219417 NA   NA    NA    NA  NA
AAMDC       NA   NA    NA       NA       2.99457972 NA   NA    NA    NA  NA
AAMP        NA   NA    NA       NA       5.27314286 NA   NA    NA    NA  NA
AANAT       NA   NA    NA       NA       0.04264434 NA   NA    NA    NA  NA
AAR2        NA   NA    NA       NA       4.14974712 NA   NA    NA    NA  NA
AARD        NA   NA    NA       NA       0.92599942 NA   NA    NA    NA  NA
⋮           ⋮    ⋮     ⋮        ⋮        ⋮          ⋮    ⋮     ⋮     ⋮   ⋮
ZSCAN5C     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSCAN5DP    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSCAN9      NA   NA    NA       NA       1.23266076 NA   NA    NA    NA  NA
ZSWIM1      NA   NA    NA       NA       2.30451104 NA   NA    NA    NA  NA
ZSWIM2      NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSWIM3      NA   NA    NA       NA       1.29278175 NA   NA    NA    NA  NA
ZSWIM4      NA   NA    NA       NA       1.88362082 NA   NA    NA    NA  NA
ZSWIM5      NA   NA    NA       NA       0.09761080 NA   NA    NA    NA  NA
ZSWIM5P1    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSWIM5P2    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSWIM5P3    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZSWIM6      NA   NA    NA       NA       2.89530262 NA   NA    NA    NA  NA
ZSWIM7      NA   NA    NA       NA       2.64385619 NA   NA    NA    NA  NA
ZSWIM8      NA   NA    NA       NA       3.88947354 NA   NA    NA    NA  NA
ZSWIM8-AS1  NA   NA    NA       NA       0.08406426 NA   NA    NA    NA  NA
ZSWIM9      NA   NA    NA       NA       1.74846123 NA   NA    NA    NA  NA
ZUP1        NA   NA    NA       NA       1.82374936 NA   NA    NA    NA  NA
ZW10        NA   NA    NA       NA       3.08236197 NA   NA    NA    NA  NA
ZWILCH      NA   NA    NA       NA       3.43429462 NA   NA    NA    NA  NA
ZWINT       NA   NA    NA       NA       4.86888427 NA   NA    NA    NA  NA
ZXDA        NA   NA    NA       NA       0.70487196 NA   NA    NA    NA  NA
ZXDB        NA   NA    NA       NA       1.55090066 NA   NA    NA    NA  NA
ZXDC        NA   NA    NA       NA       3.23572706 NA   NA    NA    NA  NA
ZYG11A      NA   NA    NA       NA       0.02856915 NA   NA    NA    NA  NA
ZYG11AP1    NA   NA    NA       NA       0.17632277 NA   NA    NA    NA  NA
ZYG11B      NA   NA    NA       NA       3.21723072 NA   NA    NA    NA  NA
ZYX         NA   NA    NA       NA       5.68397711 NA   NA    NA    NA  NA
ZYXP1       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA  NA
ZZEF1       NA   NA    NA       NA       2.75274859 NA   NA    NA    NA  NA
ZZZ3        NA   NA    NA       NA       2.67581593 NA   NA    NA    NA  NA
            ⋯ YAPC       YH-13      YKG-1 YMB-1-E YT         ZR-75-30
A1BG        ⋯ 0.04264434 0.42223300 NA    NA      0.05658353 0.22650853
A1BG-AS1    ⋯ 0.00000000 2.42760617 NA    NA      0.01435529 2.28688115
A1CF        ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000
A2M         ⋯ 0.00000000 0.16349873 NA    NA      0.01435529 0.13750352
A2M-AS1     ⋯ 0.23878686 0.12432814 NA    NA      0.04264434 0.36737107
A2ML1       ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.38956681
A2ML1-AS1   ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.05658353
A2ML1-AS2   ⋯ 0.00000000 0.00000000 NA    NA      0.13750352 0.00000000
A2MP1       ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.02856915
A3GALT2     ⋯ 0.12432814 0.32192809 NA    NA      0.00000000 0.01435529
A4GALT      ⋯ 2.39506280 0.52606881 NA    NA      0.00000000 2.03210084
A4GNT       ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000
AAAS        ⋯ 3.43295941 3.77715667 NA    NA      3.36317108 3.31179372
AACS        ⋯ 2.27500705 1.56559718 NA    NA      2.25398927 2.24184018
AACSP1      ⋯ 0.02856915 0.00000000 NA    NA      0.00000000 0.00000000
AADAC       ⋯ 1.53605290 0.00000000 NA    NA      0.00000000 0.13750352
AADACL2     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000
AADACL2-AS1 ⋯ 0.02856915 0.00000000 NA    NA      0.00000000 0.00000000
AADACL3     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000
AADACL4     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000
AADACP1     ⋯ 1.72246602 0.00000000 NA    NA      0.00000000 0.00000000
AADAT       ⋯ 2.49825087 2.09761080 NA    NA      0.00000000 0.49569516
AAED1       ⋯ 2.12101540 2.61353165 NA    NA      0.21412481 1.49057013
AAGAB       ⋯ 4.59454855 3.88459792 NA    NA      5.00854067 4.86591881
AAK1        ⋯ 1.72683122 2.39506280 NA    NA      2.79493566 1.48542683
AAMDC       ⋯ 2.65764001 2.49057013 NA    NA      1.82374936 1.61353165
AAMP        ⋯ 5.57954222 4.53977919 NA    NA      4.33342373 4.84147000
AANAT       ⋯ 0.13750352 0.05658353 NA    NA      0.02856915 0.02856915
AAR2        ⋯ 4.08151007 3.59096124 NA    NA      4.17312743 3.72574116
AARD        ⋯ 0.00000000 0.00000000 NA    NA      1.33913738 1.71369581
⋮           ⋱ ⋮          ⋮          ⋮     ⋮       ⋮          ⋮
ZSCAN5C     ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZSCAN5DP    ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZSCAN9      ⋯ 1.3561438  2.18269230 NA    NA      0.00000000 2.7398481
ZSWIM1      ⋯ 2.7761040  2.15704371 NA    NA      2.43028527 2.2986583
ZSWIM2      ⋯ 0.0000000  0.08406426 NA    NA      0.00000000 0.0000000
ZSWIM3      ⋯ 1.9855004  1.33342373 NA    NA      2.97269265 1.0071955
ZSWIM4      ⋯ 2.2326608  2.20789285 NA    NA      2.35895883 1.8196682
ZSWIM5      ⋯ 0.4222330  0.01435529 NA    NA      0.09761080 0.9560567
ZSWIM5P1    ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZSWIM5P2    ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZSWIM5P3    ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZSWIM6      ⋯ 2.7782086  2.86591881 NA    NA      5.79493566 2.5655972
ZSWIM7      ⋯ 1.6461627  1.89917563 NA    NA      1.97819563 1.6415460
ZSWIM8      ⋯ 3.5285713  3.25398927 NA    NA      4.16912328 3.6530600
ZSWIM8-AS1  ⋯ 0.1375035  0.04264434 NA    NA      0.22650853 0.0976108
ZSWIM9      ⋯ 1.6599246  2.84398384 NA    NA      1.93357264 1.6415460
ZUP1        ⋯ 2.7355222  1.94485845 NA    NA      3.06004738 2.3391374
ZW10        ⋯ 4.3023191  3.49825087 NA    NA      3.72465027 3.0000000
ZWILCH      ⋯ 4.2280490  3.43829285 NA    NA      4.18030702 3.1890338
ZWINT       ⋯ 6.0181445  3.80115866 NA    NA      4.79908731 4.4815573
ZXDA        ⋯ 1.4382929  0.76553475 NA    NA      0.02856915 0.8639385
ZXDB        ⋯ 2.3448285  1.41142625 NA    NA      2.14730670 1.7355222
ZXDC        ⋯ 2.9221978  2.16992500 NA    NA      2.55090066 2.6553518
ZYG11A      ⋯ 0.2509616  0.00000000 NA    NA      0.08406426 1.8237494
ZYG11AP1    ⋯ 0.0000000  0.00000000 NA    NA      0.21412481 0.0000000
ZYG11B      ⋯ 2.2110122  3.04264434 NA    NA      3.09085343 2.8579810
ZYX         ⋯ 4.3059705  8.02014657 NA    NA      6.39214566 4.3722556
ZYXP1       ⋯ 0.0000000  0.00000000 NA    NA      0.00000000 0.0000000
ZZEF1       ⋯ 2.0806577  1.94860085 NA    NA      3.16832112 1.9373444
ZZZ3        ⋯ 2.4698860  2.78031010 NA    NA      2.51601515 2.7886857
            SNU-283    BONNA-12   NCI-H740   U-CH2
A1BG        0.05658353 0.08406426 0.48542683 0.02856915
A1BG-AS1    0.01435529 1.26303441 2.12101540 0.04264434
A1CF        1.87184365 0.00000000 0.00000000 0.00000000
A2M         0.00000000 0.05658353 0.02856915 0.15055968
A2M-AS1     0.28688115 0.00000000 0.37851162 0.48542683
A2ML1       0.01435529 0.01435529 0.01435529 0.01435529
A2ML1-AS1   0.00000000 0.00000000 0.07038933 0.00000000
A2ML1-AS2   0.02856915 0.00000000 0.01435529 0.01435529
A2MP1       0.00000000 0.00000000 0.00000000 0.01435529
A3GALT2     0.15055968 0.02856915 0.53605290 0.12432814
A4GALT      0.00000000 2.11436702 0.21412481 0.42223300
A4GNT       0.00000000 0.00000000 0.02856915 0.00000000
AAAS        3.81659971 3.27351589 3.14730670 3.25247621
AACS        2.54101915 2.57531233 2.34766566 2.04264434
AACSP1      0.00000000 0.00000000 0.01435529 0.00000000
AADAC       0.05658353 0.00000000 0.01435529 0.01435529
AADACL2     0.00000000 0.00000000 0.00000000 0.00000000
AADACL2-AS1 0.02856915 0.01435529 0.01435529 0.00000000
AADACL3     0.00000000 0.00000000 0.00000000 0.00000000
AADACL4     0.00000000 0.00000000 0.00000000 0.00000000
AADACP1     0.40053793 0.00000000 0.12432814 0.00000000
AADAT       0.22650853 0.00000000 3.59931779 2.10433666
AAED1       1.81147103 2.09761080 2.85598970 2.84398384
AAGAB       4.64038956 4.36597243 4.27276973 4.14077866
AAK1        1.11103131 2.36737107 1.52606881 2.89724043
AAMDC       2.22342255 1.77399633 2.43829285 3.00898878
AAMP        5.36317108 4.54287710 4.44824023 3.92599942
AANAT       0.00000000 0.02856915 0.08406426 0.05658353
AAR2        4.06867081 3.83289001 3.98550043 3.31759350
AARD        0.12432814 0.33342373 0.80735492 0.85598970
⋮           ⋮          ⋮          ⋮          ⋮
ZSCAN5C     0.00000000 0.00000000 0.00000000 0.00000000
ZSCAN5DP    0.00000000 0.05658353 0.00000000 0.13750352
ZSCAN9      1.62760684 2.56071495 2.87774425 1.53106949
ZSWIM1      2.58736499 2.06350294 2.27798475 1.99276843
ZSWIM2      0.00000000 0.00000000 0.01435529 0.04264434
ZSWIM3      1.79077204 1.19534760 2.29572302 1.16992500
ZSWIM4      1.21412481 2.45417589 2.60169652 1.41683974
ZSWIM5      2.73552218 0.20163386 3.58135125 0.21412481
ZSWIM5P1    0.00000000 0.00000000 0.00000000 0.00000000
ZSWIM5P2    0.00000000 0.00000000 0.00000000 0.00000000
ZSWIM5P3    0.00000000 0.00000000 0.00000000 0.00000000
ZSWIM6      2.37573454 1.71369581 4.04788733 3.26002566
ZSWIM7      1.57046293 1.73552218 1.96347412 1.84799691
ZSWIM8      2.96532255 3.08576455 3.06695024 3.72574116
ZSWIM8-AS1  0.42223300 0.09761080 0.08406426 0.12432814
ZSWIM9      1.75702325 1.28688115 2.32481060 1.87970577
ZUP1        2.71369581 3.47638169 3.48800077 2.01077984
ZW10        3.51601515 3.57288967 3.63343121 3.59215800
ZWILCH      3.25247621 3.35049725 3.82984956 4.14730670
ZWINT       4.85798100 4.74577515 5.89845023 4.80219322
ZXDA        1.32192809 0.87184365 0.79077204 1.26903315
ZXDB        2.08065766 1.36176836 2.12101540 1.59931779
ZXDC        2.49569516 1.59454855 3.61470984 2.37295210
ZYG11A      0.02856915 0.72246602 1.64154603 0.13750352
ZYG11AP1    0.00000000 0.00000000 0.00000000 0.00000000
ZYG11B      2.10433666 1.61823866 4.08661395 2.63691458
ZYX         4.53667462 4.61412087 3.04788733 7.27761287
ZYXP1       0.00000000 0.00000000 0.00000000 0.00000000
ZZEF1       3.91456452 2.33055840 2.11103131 2.27202319
ZZZ3        2.70708299 2.40599236 4.07724300 2.34198575

In [11]:
expression_part1

      Gene        201T 22RV1 23132-87 42-MG-BA 451Lu      5637 639-V 647-V 697
1     A1BG        NA   NA    NA       NA       0.25096157 NA   NA    NA    NA
2     A1BG-AS1    NA   NA    NA       NA       2.37573454 NA   NA    NA    NA
3     A1CF        NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
4     A2M         NA   NA    NA       NA       6.45121111 NA   NA    NA    NA
5     A2M-AS1     NA   NA    NA       NA       0.12432814 NA   NA    NA    NA
6     A2ML1       NA   NA    NA       NA       0.01435529 NA   NA    NA    NA
7     A2ML1-AS1   NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
8     A2ML1-AS2   NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
9     A2MP1       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
10    A3GALT2     NA   NA    NA       NA       0.12432814 NA   NA    NA    NA
11    A4GALT      NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
12    A4GNT       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
13    AAAS        NA   NA    NA       NA       3.87381320 NA   NA    NA    NA
14    AACS        NA   NA    NA       NA       1.98550043 NA   NA    NA    NA
15    AACSP1      NA   NA    NA       NA       0.04264434 NA   NA    NA    NA
16    AADAC       NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
17    AADACL2     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18    AADACL2-AS1 NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
19    AADACL3     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
20    AADACL4     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
21    AADACP1     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
22    AADAT       NA   NA    NA       NA       2.20789285 NA   NA    NA    NA
23    AAED1       NA   NA    NA       NA       1.77399633 NA   NA    NA    NA
24    AAGAB       NA   NA    NA       NA       3.55704242 NA   NA    NA    NA
25    AAK1        NA   NA    NA       NA       2.19219417 NA   NA    NA    NA
26    AAMDC       NA   NA    NA       NA       2.99457972 NA   NA    NA    NA
27    AAMP        NA   NA    NA       NA       5.27314286 NA   NA    NA    NA
28    AANAT       NA   NA    NA       NA       0.04264434 NA   NA    NA    NA
29    AAR2        NA   NA    NA       NA       4.14974712 NA   NA    NA    NA
30    AARD        NA   NA    NA       NA       0.92599942 NA   NA    NA    NA
⋮     ⋮           ⋮    ⋮     ⋮        ⋮        ⋮          ⋮    ⋮     ⋮     ⋮
18603 MTCO2P8     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18604 MTCO2P9     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18605 MTCO3P1     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18606 MTCO3P10    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18607 MTCO3P11    NA   NA    NA       NA       0.04264434 NA   NA    NA    NA
18608 MTCO3P12    NA   NA    NA       NA       2.17632277 NA   NA    NA    NA
18609 MTCO3P13    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18610 MTCO3P15    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18611 MTCO3P16    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18612 MTCO3P17    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18613 MTCO3P18    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18614 MTCO3P19    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18615 MTCO3P2     NA   NA    NA       NA       0.09761080 NA   NA    NA    NA
18616 MTCO3P20    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18617 MTCO3P21    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18618 MTCO3P22    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18619 MTCO3P23    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18620 MTCO3P24    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18621 MTCO3P27    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18622 MTCO3P28    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18623 MTCO3P29    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18624 MTCO3P30    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18625 MTCO3P31    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18626 MTCO3P35    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18627 MTCO3P38    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18628 MTCO3P39    NA   NA    NA       NA       0.04264434 NA   NA    NA    NA
18629 MTCO3P4     NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18630 MTCO3P40    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18631 MTCO3P41    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
18632 MTCO3P42    NA   NA    NA       NA       0.00000000 NA   NA    NA    NA
      ⋯ YAPC       YH-13      YKG-1 YMB-1-E YT         ZR-75-30   SNU-283
1     ⋯ 0.04264434 0.42223300 NA    NA      0.05658353 0.22650853 0.05658353
2     ⋯ 0.00000000 2.42760617 NA    NA      0.01435529 2.28688115 0.01435529
3     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000 1.87184365
4     ⋯ 0.00000000 0.16349873 NA    NA      0.01435529 0.13750352 0.00000000
5     ⋯ 0.23878686 0.12432814 NA    NA      0.04264434 0.36737107 0.28688115
6     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.38956681 0.01435529
7     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.05658353 0.00000000
8     ⋯ 0.00000000 0.00000000 NA    NA      0.13750352 0.00000000 0.02856915
9     ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.02856915 0.00000000
10    ⋯ 0.12432814 0.32192809 NA    NA      0.00000000 0.01435529 0.15055968
11    ⋯ 2.39506280 0.52606881 NA    NA      0.00000000 2.03210084 0.00000000
12    ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000 0.00000000
13    ⋯ 3.43295941 3.77715667 NA    NA      3.36317108 3.31179372 3.81659971
14    ⋯ 2.27500705 1.56559718 NA    NA      2.25398927 2.24184018 2.54101915
15    ⋯ 0.02856915 0.00000000 NA    NA      0.00000000 0.00000000 0.00000000
16    ⋯ 1.53605290 0.00000000 NA    NA      0.00000000 0.13750352 0.05658353
17    ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000 0.00000000
18    ⋯ 0.02856915 0.00000000 NA    NA      0.00000000 0.00000000 0.02856915
19    ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000 0.00000000
20    ⋯ 0.00000000 0.00000000 NA    NA      0.00000000 0.00000000 0.00000000
21    ⋯ 1.72246602 0.00000000 NA    NA      0.00000000 0.00000000 0.40053793
22    ⋯ 2.49825087 2.09761080 NA    NA      0.00000000 0.49569516 0.22650853
23    ⋯ 2.12101540 2.61353165 NA    NA      0.21412481 1.49057013 1.81147103
24    ⋯ 4.59454855 3.88459792 NA    NA      5.00854067 4.86591881 4.64038956
25    ⋯ 1.72683122 2.39506280 NA    NA      2.79493566 1.48542683 1.11103131
26    ⋯ 2.65764001 2.49057013 NA    NA      1.82374936 1.61353165 2.22342255
27    ⋯ 5.57954222 4.53977919 NA    NA      4.33342373 4.84147000 5.36317108
28    ⋯ 0.13750352 0.05658353 NA    NA      0.02856915 0.02856915 0.00000000
29    ⋯ 4.08151007 3.59096124 NA    NA      4.17312743 3.72574116 4.06867081
30    ⋯ 0.00000000 0.00000000 NA    NA      1.33913738 1.71369581 0.12432814
⋮     ⋱ ⋮          ⋮          ⋮     ⋮       ⋮          ⋮          ⋮
18603 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18604 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18605 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18606 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18607 ⋯ 0.01435529 0.1634987  NA    NA      0.21412481 0.02856915 0.04264434
18608 ⋯ 0.71369581 0.5849625  NA    NA      0.55581616 1.89917563 1.94485845
18609 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18610 ⋯ 0.00000000 0.0000000  NA    NA      0.33342373 0.00000000 0.00000000
18611 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18612 ⋯ 0.00000000 0.0000000  NA    NA      0.01435529 0.00000000 0.00000000
18613 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18614 ⋯ 0.00000000 0.0000000  NA    NA      0.05658353 0.00000000 0.02856915
18615 ⋯ 0.05658353 0.0000000  NA    NA      0.09761080 0.00000000 0.11103131
18616 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18617 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18618 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18619 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18620 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.01435529
18621 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18622 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18623 ⋯ 0.00000000 0.0000000  NA    NA      0.01435529 0.02856915 0.00000000
18624 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18625 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18626 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18627 ⋯ 0.00000000 0.0000000  NA    NA      0.02856915 0.00000000 0.00000000
18628 ⋯ 0.09761080 0.0000000  NA    NA      0.01435529 0.00000000 0.18903382
18629 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18630 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18631 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
18632 ⋯ 0.00000000 0.0000000  NA    NA      0.00000000 0.00000000 0.00000000
      BONNA-12   NCI-H740   U-CH2
1     0.08406426 0.48542683 0.02856915
2     1.26303441 2.12101540 0.04264434
3     0.00000000 0.00000000 0.00000000
4     0.05658353 0.02856915 0.15055968
5     0.00000000 0.37851162 0.48542683
6     0.01435529 0.01435529 0.01435529
7     0.00000000 0.07038933 0.00000000
8     0.00000000 0.01435529 0.01435529
9     0.00000000 0.00000000 0.01435529
10    0.02856915 0.53605290 0.12432814
11    2.11436702 0.21412481 0.42223300
12    0.00000000 0.02856915 0.00000000
13    3.27351589 3.14730670 3.25247621
14    2.57531233 2.34766566 2.04264434
15    0.00000000 0.01435529 0.00000000
16    0.00000000 0.01435529 0.01435529
17    0.00000000 0.00000000 0.00000000
18    0.01435529 0.01435529 0.00000000
19    0.00000000 0.00000000 0.00000000
20    0.00000000 0.00000000 0.00000000
21    0.00000000 0.12432814 0.00000000
22    0.00000000 3.59931779 2.10433666
23    2.09761080 2.85598970 2.84398384
24    4.36597243 4.27276973 4.14077866
25    2.36737107 1.52606881 2.89724043
26    1.77399633 2.43829285 3.00898878
27    4.54287710 4.44824023 3.92599942
28    0.02856915 0.08406426 0.05658353
29    3.83289001 3.98550043 3.31759350
30    0.33342373 0.80735492 0.85598970
⋮     ⋮          ⋮          ⋮
18603 0.00000000 0.00000000 0.00000000
18604 0.00000000 0.00000000 0.00000000
18605 0.00000000 0.00000000 0.00000000
18606 0.00000000 0.00000000 0.00000000
18607 0.18903382 0.13750352 0.04264434
18608 1.06350294 1.26903315 0.71369581
18609 0.00000000 0.00000000 0.00000000
18610 0.00000000 0.01435529 0.00000000
18611 0.00000000 0.07038933 0.01435529
18612 0.00000000 0.00000000 0.01435529
18613 0.00000000 0.00000000 0.00000000
18614 0.02856915 0.07038933 0.04264434
18615 0.00000000 0.04264434 0.00000000
18616 0.02856915 0.00000000 0.00000000
18617 0.00000000 0.00000000 0.00000000
18618 0.00000000 0.00000000 0.00000000
18619 0.00000000 0.00000000 0.00000000
18620 0.01435529 0.00000000 0.01435529
18621 0.00000000 0.00000000 0.00000000
18622 0.00000000 0.00000000 0.00000000
18623 0.00000000 0.00000000 0.00000000
18624 0.00000000 0.00000000 0.00000000
18625 0.00000000 0.00000000 0.00000000
18626 0.00000000 0.00000000 0.00000000
18627 0.00000000 0.00000000 0.00000000
18628 0.05658353 0.18903382 0.40053793
18629 0.00000000 0.00000000 0.00000000
18630 0.00000000 0.00000000 0.00000000
18631 0.00000000 0.02856915 0.00000000
18632 0.00000000 0.00000000 0.01435529

In [8]:
# drugAct <- exprs(getAct(gdsc2Data::drugData)) # Get drug activity data
# write.csv(drugAct, '../gdsc2_data/drugAct.csv') # Save as a CSV file

In [9]:
methylation <- getAllFeatureData(gdscDataDec15::molData)[["met"]]
methylation <- methylation[order(row.names(methylation)),]
                               
methylation <- cbind(Gene = rownames(methylation), as.data.frame(methylation))
methylation <- as.data.table(methylation)

setkey(methylation, Gene)

n <- nrow(methylation)
half <- ceiling(n / 2)

methylation_part1 <- methylation[1:half]
methylation_part2 <- methylation[(half + 1):n]

fwrite(methylation_part1, '../data/gdsc1_data/met_part1.csv.gz', compress = "gzip")
fwrite(methylation_part2, '../data/gdsc1_data/met_part2.csv.gz', compress = "gzip")

fwrite(methylation_part1, '../data/gdsc2_data/met_part1.csv.gz', compress = "gzip")
fwrite(methylation_part2, '../data/gdsc2_data/met_part2.csv.gz', compress = "gzip")