In [1]:
import optuna

In [4]:
name = "nci_GAT"
study = optuna.create_study(
    storage="sqlite:///{}.sqlite3".format(name),
    study_name=name,
    load_if_exists=True,
)
res = study.trials_dataframe()
res.dropna(subset=[i for i in res.columns if "values" in i])

[I 2025-03-22 11:44:45,345] A new study created in RDB with name: nci_GAT

Empty DataFrame
Columns: []
Index: []

In [5]:
name = "nci"
study = optuna.create_study(
    storage="sqlite:///{}_{}.sqlite3".format(name, "GCN_MPNN"),
    study_name=name,
    load_if_exists=True,
)
res = study.trials_dataframe()
res.dropna(subset=[i for i in res.columns if "values" in i])

[I 2025-03-22 11:45:04,968] A new study created in RDB with name: nci

Empty DataFrame
Columns: []
Index: []